Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/classes/ClsAsyncOpportunityUpdateTest.cls
/**
 * Created By: Abhijeet Bhandari
 * Created On: 1/12/2024
 * Description: Tect class for ClsAsyncOpportunityUpdate to validate the invocable emthod and the future method.
 */
@isTest
private class ClsAsyncOpportunityUpdateTest {

    @TestSetup
    static void makeData(){
        List<Account> lstAccount = TestDataFactory.createAccount(1,true);   
        List<Opportunity> lstOpportunity = TestDataFactory.createOppty(1,lstAccount[0].Id,true);       
    }
    
    @isTest
    static void testAsyncOpportunityUpdateQuote() {        
        List<Account> lstAccount = [SELECT ID from Account WHERE Name LIKE '%Test Account%'];
        List<List<Opportunity>> lstOpportunityWrapped = new List<List<Opportunity>>();
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        List<Opportunity> lstUpdatedOpportunity = new List<Opportunity>();
        Test.startTest();
            lstOpportunity = [SELECT Id, Deal_Type__c FROM Opportunity WHERE AccountId=:lstAccount[0].Id];
            lstOpportunityWrapped.add(lstOpportunity); 
            system.assert(String.isBlank(lstOpportunity[0].Deal_Type__c));            
            List<SBQQ__Quote__c> lstQuote = TestDataFactory.createQuote(1,lstOpportunity[0].Id,false);  
            lstQuote[0].Deal_Type__c = 'Expansion';
            lstQuote[0].SBQQ__Primary__c = false;          
            insert lstQuote;
            ClsAsyncOpportunityUpdate.updateOpportunities(lstOpportunityWrapped);     
        
            
        Test.stopTest();
    }
}