Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Auto_Number_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Auto_Number_Deal_ID__c</fullName>
    <description>OP4I Deal auto-number of the Opportunity.</description>
    <label>OP4I Deal Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/sbaa__ApprovalStep__c.field-meta.xml
<CustomField>
    <fullName>sbaa__ApprovalStep__c</fullName>
    <description>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</description>
    <inlineHelpText>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</inlineHelpText>
    <label>Approval Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used with Native Approvers; indicates which Approver is responsible for approving the Opportunity.</description>
    <inlineHelpText>Used with Native Approvers; indicates which Approver is responsible for approving the Opportunity.</inlineHelpText>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Auto_Number_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Auto_Number_Deal_ID__c</fullName>
    <description>OP4I Deal auto-number.</description>
    <formula>SBQQ__Opportunity2__r.OP4I_Auto_Number_Deal_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Deal Id</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/classes/ApprovalRequestControllerTest.cls
/**
 * @description
 * This class tests the ApprovalRequestController class.
 */
@isTest
private class ApprovalRequestControllerTest {
    /***********************************************************************************************
    *
    * Test Methods
    *
    ***********************************************************************************************/
    /** 
    @description
        This method sets up the test data for the ApprovalRequestEmailSenderBatchTest class.
        It creates a test user and an approval record for the batch to process.
    */
    @testSetup
    static void setupTestData() {
        // Create a test user
        User testUser = (User)TestFactory.createSObject(
            new User(
                LastName='ApprovalRequestControllerTest'
            ),
            'CRMOpsUserDefaults'
        );

        System.runAs(new User(Id = UserInfo.getUserId())) {
            sbaa__Approver__c approver = (sbaa__Approver__c)TestFactory.createSObject(
                new sbaa__Approver__c(
                    Name = 'Main Approver', 
                    sbaa__User__c = testUser.Id
                )
            );
            
            // Create an Account
            Account testAccount = (Account)TestFactory.createSObject(
                new Account(Name = 'test acc1'), 
                'AccountDefaults'
            );
            
            // Create an Opportunity
            Opportunity testOpportunity = (Opportunity)TestFactory.createSObject(
            new Opportunity(
                Name = 'Test Opportunity',
                CloseDate = Date.today(),
                AccountId = testAccount.Id,
                //SBQQ__RenewedContract__c = testContract.Id,
                OP4I_Auto_Number_Deal_ID__c = '12345'
            ), 'OpportunityDefaults');


            SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
                    SBQQ__Opportunity2__c = testOpportunity.Id,
                    SBQQ__Account__c = testOpportunity.AccountId
                );
            Insert testQuote;
            
            // insert approval
            TestFactory.createSObject(
                new sbaa__Approval__c(
                    sbaa__Status__c = 'Requested',
                    sbaa__ApprovalStep__c = 1,
                    sbaa__RecordField__c = 'Name',
                    sbaa__Approver__c = approver.Id,
                    Quote__c = testQuote.Id
                )
            );
        }
    }

    /**
     * @description
        This method tests the execution of the ApprovalRequestEmailSenderBatch class.
     */
    @isTest
    static void testGetRelevantUserIdsFromApprovals() {
        Test.startTest();
        Set<Id> resultUserIds = ApprovalRequestController.getRelevantUserIdsFromApprovals();
        Test.stopTest();

        User testUser = getUser('ApprovalRequestControllerTest');

        System.assert(resultUserIds.contains(testUser.Id), 'Expected test user ID in result');
        System.assertEquals(1, resultUserIds.size(), 'Should contain only one unique user ID');
    }

    /**
     * @description
        This method tests the execution of the ApprovalRequestEmailSenderBatch class.
     */
    @isTest
    static void testApprovalRequestController() {
        // Use runAs to simulate context
        User testUser = getUser('ApprovalRequestControllerTest');
        System.runAs(testUser) {
            Test.startTest();
            
            ApprovalRequestController controller = new ApprovalRequestController();
            controller.usrId = testUser.Id;

            List<ApprovalRequestController.ApprovalWrapper> wrappers = controller.approvalRequests;
            Test.stopTest();

            // Assertions
            System.assertNotEquals(null, wrappers, 'Approval wrappers should not be null');
            System.assertEquals(1, wrappers.size(), 'Should return 1 approval wrapper');
        }
    }

    /***********************************************************************************************
    *
    * Private Methods
    *
    ***********************************************************************************************/
    /** 
    * @description getter for user
    * @param lastName
    * @return User
    */
    private static User getUser(String lastName) {
        // Fetch the test user
        List<User> users = [SELECT Id, Name, Email FROM User WHERE LastName = :lastName LIMIT 1];
        return users.isEmpty() ? null : users[0];
    }
}