force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Renewal Letter</label>
    <nameField>
        <displayFormat>RL-{0000000}</displayFormat>
        <label>Renewal Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Proforma_Invoice__c/fields/Renewal_Quote__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Performa_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Proforma_Invoice__c/fields/Renewal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Start_Date__c</fullName>
    <description>Start date of the related renewal Quote</description>
    <label>Renewal Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Payment received</fullName>
            </value>
            <value>
                <fullName>Working with Customer for changes</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Allocated</fullName>
            </value>
            <value>
                <fullName>No Response from Customer</fullName>
                <isActive>false</isActive>
                <label>No Response from Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Stage</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Letter__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Letter</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote_Type__c</fullName>
    <description>Created as part of BIZ-47716, to specify the renewal Quote type.
Auto Renewal - Created Automatically by the system when renewal quoted is selected on the contract.
Renewal-Changes - Created by cloning Auto-Renewal Quotes.
COntract consolidation - created while consolidating contracts</description>
    <label>Renewal Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto-Renewal</fullName>
            </value>
            <value>
                <fullName>Consolidated-Quote</fullName>
            </value>
            <value>
                <fullName>Renewal-Changes</fullName>
                <isActive>false</isActive>
                <label>Renewal-Changes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateMissingRenewalLetters.cls
/**
 * @description Batch class to insert renewal letters for quotes with start dates within the next 90 days.
 * This class also updates quotes to trigger tax calculations if the renewal letter is not applicable.
 * Handles batch processing with error logging for failed DML operations.
 * 
 * @author Pooja Hemrajani
 * @jira BIZ-68060
 */

 public without sharing class GenerateMissingRenewalLetters implements Database.Batchable<sObject>, Schedulable  {
    
    /***********************************************************************************************
    *
    * props
    *
    ***********************************************************************************************/
    public Set<Id> quotesForRL;
    private String query;
    private Integer scopeSize;
    private Date startDate = Date.today();
    private Date endDate = Date.today().addDays(90);

    /***********************************************************************************************
    *
    * Constructors
    *
    ***********************************************************************************************/
    /**
    * @description Default Constructor
    **/
    public generateMissingRenewalLetters() {

        this.quotesForRL = new Set<Id>();
        this.query = getDefaultQuery();
        this.scopeSize = 1;
    }

    /**
    * @description parameterized Constructor
    * @param query
    * @param scopeSize
    **/
    public generateMissingRenewalLetters(String query, Integer scopeSize) {
        // Set the query and scope size

        this.quotesForRL = new Set<Id>();
        this.query = (query != null) ? query : getDefaultQuery();
        this.scopeSize = 1;
    }

    /***********************************************************************************************
    *
    * Public Methods
    *
    ***********************************************************************************************/

    /**
    * @description Method that can be used to override the query and scope size
    * @param query
    * @param scopeSize
    **/
    public void executeBatch(String query, Integer scopeSize) {
        GenerateMissingRenewalLetters obj = new GenerateMissingRenewalLetters(query, scopeSize);
        Database.executeBatch(obj, scopeSize);
    }

    /***********************************************************************************************
    *
    * Batch Methods
    *
    ***********************************************************************************************/
    /**
    * @description start method
    * @param bc
    * @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query renewal letters that need to be processed
        String query = this.query;
        return Database.getQueryLocator(query);
    }

    /**
    * @description execute method
    * @param bc
    * @param quotesData
    **/
    public void execute(Database.BatchableContext bc, List<SBQQ__Quote__c> quotesData) {

        List<Proforma_Invoice__c> renewalLettersToInsert = new List<Proforma_Invoice__c>();
        List<SBQQ__Quote__c> quotesToUpdate = new List<SBQQ__Quote__c>();

        for(SBQQ__Quote__c quote: quotesData){
            if (QuoteConstants.AVA_TAX_MSG_UPTO_DATE.equals(quote.AVA_SFCPQ__AvaTaxMessage__c) && quote.SBQQ__StartDate__c != null) {
                // Create a new Renewal Letter
                renewalLettersToInsert.add(new Proforma_Invoice__c(
                    Renewal_Quote__c = quote.Id,
                    Renewal_Start_Date__c = quote.SBQQ__StartDate__c,
                    Status__c = RenewalLetterConstants.STATUS_INITIATED,
                    CurrencyISOCode = quote.CurrencyISOCode
                ));
            } else {
                // Update the quote to trigger tax calculation
                quote.AVA_SFCPQ__Quote_AutomateTaxCalculation__c = true;
                quotesToUpdate.add(quote);
            }
        }

        if (!renewalLettersToInsert.isEmpty()) {
            List<Database.SaveResult> renewalLettersToInsertResults = Database.insert(renewalLettersToInsert, false);
            ResultHandler.logErrors('GenerateMissingRenewalLetters Insert Renewal Letters', renewalLettersToInsert, renewalLettersToInsertResults);
        }
        
        if (!quotesToUpdate.isEmpty()) {
            System.enqueueJob(new UpdateQuoteQueueable(quotesToUpdate));
        }
    }

    /**
    * @description finish method
    * @param bc
    **/
    public void finish(Database.BatchableContext bc) {
        
        System.debug('Batch process completed successfully.');
    }

    /***********************************************************************************************
    *
    * Schedulable Methods
    *
    ***********************************************************************************************/
    /**
    * @description execute method
    * @param sc
    **/
    public void execute(SchedulableContext sc) {
        // Execute the batch job
        executeBatch(this.query, this.scopeSize);
    }

    /***********************************************************************************************
    *
    * Private Methods
    *
    ***********************************************************************************************/
    /**
    * @description set the default query
    * @return String
    **/
    private String getDefaultQuery() {
        Date startDate = Date.today();
        Date endDate = Date.today().addDays(90);
        
        String defaultQuery = 'SELECT Id, AVA_SFCPQ__AvaTaxMessage__c, SBQQ__StartDate__c, AVA_SFCPQ__Quote_AutomateTaxCalculation__c, ' +
                            'Renewal_Letter__c, Renewal_Quote_Type__c, Opportunity_Stage__c, CurrencyISOCode, ' +
                            'SBQQ__Primary__c, SBQQ__Ordered__c ' +
                            'FROM SBQQ__Quote__c ' +
                            'WHERE Renewal_Letter__c = NULL ' +
                            'AND SBQQ__StartDate__c >= :startDate ' +  // Bind variable
                            'AND SBQQ__StartDate__c <= :endDate ' +    // Bind variable
                            'AND Renewal_Quote_Type__c = \'Auto-Renewal\' ' +
                            'AND Opportunity_Stage__c != \'Closed Lost\' ' +
                            'AND SBQQ__Primary__c = TRUE ' +
                            'AND SBQQ__Ordered__c = FALSE ' +
                            'AND (SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Status = \'' + ContractConstants.STATUS_INFORCE + '\' ' +
                            '     OR SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Status = \'' + ContractConstants.STATUS_PARTIALLY_SUPERSEDED + '\') ' +
            				'AND SBQQ__Opportunity2__r.IsClosed = FALSE';
                            
        return defaultQuery;
    }
}