force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores all the custom exceptions coming from Apex Code</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Error_Log__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>This will hold the name of the process which failed.</description>
    <inlineHelpText>Populate &quot;ClassName.methodName&quot; whenever possible</inlineHelpText>
    <label>Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Error_Log__c/fields/Sobject_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Name__c</fullName>
    <description>This will hold the name of the object which got the exception</description>
    <label>Sobject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/ACV_Type__c.field-meta.xml
<CustomField>
    <fullName>ACV_Type__c</fullName>
    <description>ACV Type , twin field on Quote</description>
    <label>ACV Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ACV_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Reconciliation_Notes_OP4I__c.field-meta.xml
<CustomField>
    <fullName>Deal_Reconciliation_Notes_OP4I__c</fullName>
    <label>Deal Reconciliation Notes in OP4I</label>
    <type>TextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <inlineHelpText>&quot;Net Amount&quot; from primary opporttunity</inlineHelpText>
    <label>TCV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Id__c</fullName>
    <description>OP4I Deal Id of the Opportunity.</description>
    <label>OnePlace ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Status__c</fullName>
    <description>To track when an NYMY Deal in OP4I goes to closed won - BIZ-46116</description>
    <label>OP4I Deal Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Quote_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Start_Date__c</fullName>
    <label>Quote Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated License Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Related Opportunity)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Segment_Index__c.field-meta.xml
<CustomField>
    <fullName>Segment_Index__c</fullName>
    <description>BIZ-46116: It will calculate the segment Index of Opportunity for NYMY</description>
    <label>Segment Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>BIZ-77549: Identifies whether the Opportunity or Quote originated from OP4I or Salesforce based on the selected Deal Type.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OP4I</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
                <default>true</default>
                <label>SFDC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date the the billing pause begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Total_Contract_Months__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_Months__c</fullName>
    <label>Total Contract Months</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/ACV_Type__c.field-meta.xml
<CustomField>
    <fullName>ACV_Type__c</fullName>
    <description>ACV Type, twin field on Quote Line</description>
    <label>ACV Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ACV_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/DLIP_OP4I_ID__c.field-meta.xml
<CustomField>
    <fullName>DLIP_OP4I_ID__c</fullName>
    <description>Created as part of BIZ-68739</description>
    <label>DLIP OP4I ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <description>Field to hold value of Net total on the quote line</description>
    <formula>SBQQ__QuoteLine__r.SBQQ__NetTotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/OP4I_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Id__c</fullName>
    <label>OP4I Deal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/OP4I_System_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_System_Id__c</fullName>
    <description>For syncing Opportunity Products Items with OP4I Deal Line Item, BIZ-45223</description>
    <label>OP4I System Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Original_Opportunity_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Opportunity_Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Opportunity Product Id</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Original_Oppty_Text_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Oppty_Text_Id__c</fullName>
    <description>Capture Original Oppty Id in Text - BIZ-71429</description>
    <label>Original Oppty Text Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT( PricebookEntry.Product2.Product_Type__c )</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this Opportunity Product.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Segment_Index__c.field-meta.xml
<CustomField>
    <fullName>Segment_Index__c</fullName>
    <description>Filed used to display segment Index form related quote line</description>
    <label>Segment Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/OP4I_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Id__c</fullName>
    <formula>SBQQ__Quote__r.OP4IDealID__c</formula>
    <label>OP4I Deal Id</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Services Discount</fullName>
            </value>
            <value>
                <fullName>Software Discount (One-Time)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Services (Recurring)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/globalValueSets/ACV_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired Add-On Module</fullName>
    </customValue>
    <customValue>
        <fullName>Acquired New Contracting Entity</fullName>
    </customValue>
    <customValue>
        <fullName>Acquired New Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Acquired New Logo</fullName>
    </customValue>
    <customValue>
        <fullName>Acquired New Product</fullName>
    </customValue>
    <customValue>
        <fullName>Additional ACV</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Functionality</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Licenses</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Services</fullName>
    </customValue>
    <customValue>
        <fullName>Assessment/ POC</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation-Contracting Entity</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation-License</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation-Logo</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation-Product</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting Services</fullName>
    </customValue>
    <customValue>
        <fullName>Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New Contracting Entity</fullName>
    </customValue>
    <customValue>
        <fullName>New Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>New Logo</fullName>
    </customValue>
    <customValue>
        <fullName>New Product</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring Adjustment</fullName>
    </customValue>
    <customValue>
        <fullName>Reduced Functionality</fullName>
    </customValue>
    <customValue>
        <fullName>Services Change Request</fullName>
    </customValue>
    <customValue>
        <fullName>Services Partner</fullName>
    </customValue>
    <customValue>
        <fullName>SFA</fullName>
    </customValue>
    <masterLabel>ACV Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CloneOptyWithLineItems.cls
/**
* @description       : BIZ-46116-This class is an Invocable class having NYMY functionality which is invoked from Opportunity : After Update flow.
* @author            : Pankaj Kumar
* @last modified on  : 09-21-2023
* @last modified by  : Pankaj Kumar
* Modifications Log
* Ver   Date         Author         Modification
* 1.0   07-07-2023   Pankaj Kumar   Initial Version
*
**/
public without sharing class CloneOptyWithLineItems {
    
    /**
    * @description : This method will handle NYMY opty & line Item cloning. 
    * @author Pankaj Kumar | 09-21-2023 
    * @param List<Id> recordId 
    **/ 
    @InvocableMethod(label='CloneOptyWithLineItems' description='Method to clone Opportunity And Opportunity LineItems')
    public static List<Id> cloneOpp(List<Id> recordId){
        if(!System.isBatch() && !System.isFuture()) { 
            cloneOppFuture(recordId);
        }
        return null;
    }
    
    /**
    * @description : This method will clone Opportunity & Opportunity LineItems.
    * @author Pankaj Kumar | 09-21-2023 
    * @param recordId 
    **/
    @future(callout=false)
    public static void cloneOppFuture(List<Id> recordId){
        try{
            Opportunity original = Database.query(allFields('Opportunity')+' Where Id =:recordId Limit 1');
            
            //Cloned Opty Record
            Opportunity clonedRec = original.Clone(false, true, false, false);
            if(clonedRec.Related_Opportunity__c!=null){
                clonedRec.Segment_Index__c = original.Segment_Index__c + 1;
                clonedRec.Quote_Start_Date__c = original.Quote_Start_Date__c.addMonths(12);
            }else{
                clonedRec.Related_Opportunity__c = original.id;
                if(original.Segment_Index__c == null){
                    clonedRec.Segment_Index__c = 2;
                    clonedRec.Quote_Start_Date__c = original.Quote_Start_Date__c.addMonths(original.First_Segment_Months__c.intValue());
                }
                else{
                    clonedRec.Segment_Index__c = original.Segment_Index__c + 1;
                    
                    clonedRec.Quote_Start_Date__c = original.Quote_Start_Date__c.addMonths(12);
                }
            }
            clonedRec.Name = clonedRec.Name + '_NYMYYear' + clonedRec.Segment_Index__c;
            clonedRec.OP4I_Deal_Id__c = '';
            //clonedRec.OP4I_Deal_Id__c = original.OP4I_Deal_Id__c;
            clonedRec.Deal_Type__c = 'NextYear_MultiYear';
            clonedRec.StageName = 'Selected';
            clonedRec.Source_System__c = 'SFDC';
            clonedRec.OP4I_Deal_Status__c = '';
            clonedRec.Deal_Reconciliation_Notes_OP4I__c = null;
            clonedRec.Total_Contract_Months__c = original.Total_Contract_Months__c;
            clonedRec.First_Segment_Months__c = original.First_Segment_Months__c;
            clonedRec.CloseDate = clonedRec.Quote_Start_Date__c;
            clonedRec.ACV_Type__c = original.ACV_Type__c;
            clonedRec.Start_Date__c = original.Start_Date__c;
            clonedRec.Net_Amount__c = original.Net_Amount__c;
            if(clonedRec!=null){
                insert clonedRec;
            }
            
            //Cloned OptyLines
            String strQuery = allFields('OpportunityLineItem')+' Where OpportunityId =:recordId AND Product_Type__c NOT IN (\'Services\', \'Services Discount\', \'Services (Recurring)\')';
            List<OpportunityLineItem> originalOptyLines = Database.query(strQuery);
            Map<Id,OpportunityLineItem> clonedOpportunityLineWithOriginalIdMap = new Map<Id,OpportunityLineItem>();
            List<OpportunityLineItem> clonedOptyLines = new List<OpportunityLineItem>();
            for(OpportunityLineItem ql : originalOptyLines){
                if(ql!=null){
                    OpportunityLineItem clonedLineRec = ql.Clone(false, true, false, false);
                    clonedLineRec.OpportunityId = clonedRec.Id;
                    clonedLineRec.Original_Opportunity_Product_Id__c = null;
                    clonedLineRec.unitprice=null;
                    clonedLineRec.SBQQ__QuoteLine__c=null;
                    clonedLineRec.OP4I_System_Id__c='';
                    clonedLineRec.DLIP_OP4I_ID__c = '';
                    clonedLineRec.OP4I_Deal_Id__c = '';
                    clonedLineRec.Original_Oppty_Text_Id__c = ql.id;
                   	//clonedLineRec.OP4I_Deal_Id__c = original.OP4I_Deal_Id__c;
                    if(clonedLineRec.SBQQ__ParentID__c != null){
                        clonedOptyLines.add(clonedLineRec);
                    } else{
                        clonedOpportunityLineWithOriginalIdMap.put(ql.Id,clonedLineRec);
                    }
                }
            }
            if(clonedOpportunityLineWithOriginalIdMap.values()!=null && clonedOpportunityLineWithOriginalIdMap.values().size()>0){
                insert clonedOpportunityLineWithOriginalIdMap.values();
            }
            for(OpportunityLineItem oli : clonedOptyLines){
                oli.SBQQ__ParentID__c = clonedOpportunityLineWithOriginalIdMap.get(oli.SBQQ__ParentID__c).Id;
            }
            if(clonedOptyLines!=null){
                insert clonedOptyLines;
            }

        }
        catch(Exception e){
            insert new Error_Log__c(
                Process__c = 'CloneOptyWithLineItems cloneOppFuture', 
                Exception_Message__c = e.getMessage(),
                StackTrace__c = e.getStackTraceString(), 
                Sobject_Name__c = 'Opportunity'
            );
        }
    }
    
    /**
    * @description : This method will dynamic query on the sObject. 
    * @author Pankaj Kumar | 09-21-2023 
    * @param objectName
    * @return String 
    **/    
    public static String allFields(String objectName) {
        List<String> fields = new List<String>(Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().keySet());
        String query  = 'SELECT '+String.join(fields, ',')+' FROM '+ObjectName;
        return query;
    }
}