Doc/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

Doc/force-app/main/default/objects/DealEvent__e/DealEvent__e.object-meta.xml
<CustomObject>
    <description>This is used to create and update Quote and Quote Lines between SFDC and OP4I</description>
    <label>DealEvent</label>
    <pluralLabel>DealEvents</pluralLabel>
</CustomObject>

Doc/force-app/main/default/objects/DealEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Initial_Software_Term_Length_Months__c.field-meta.xml
<CustomField>
    <fullName>Initial_Software_Term_Length_Months__c</fullName>
    <inlineHelpText>Please populate the initial term length in months. For a standard deal, this should say 12. For non standard deals, add the additional months in. For example, if you are providing an additional 2 months to the initial term, populate 14 in this field.</inlineHelpText>
    <label>Initial Software Term Length (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DealEventTriggerHandlerTest.cls
@isTest
public class DealEventTriggerHandlerTest {

  static testmethod void testMethod1() {
    Account account = IntappTestObjectfactory.createAccount(true);
        
    Contact con = (Contact) SmartFactory.createSObject('Contact');
    con.AccountId = account.Id; 
    insert con;
    
    Contract ctr = (Contract) SmartFactory.createSObject('Contract');
    ctr.AccountId = account.Id;
    insert ctr;
    
    Opportunity opportunity = (Opportunity) SmartFactory.createSObject('Opportunity');
    opportunity.AccountId = account.Id;
    opportunity.Associated_Contract_OSA__c = ctr.Id;
    opportunity.Contract_Signer__c = con.Id;
    opportunity.Requested_Contract_Expiration__c = Date.today();
    opportunity.Initial_Software_Term_Length_Months__c = 12;
    insert opportunity; 
    
    system.assertequals(opportunity.contactId,null);
  }

  @IsTest
    static void testAfterInsertDealEvent() {

        // ----- 1) Create a Platform Event -----
        DealEvent__e ev = new DealEvent__e(
            Object_Name__c = 'Opportunity',
            Payload__c = 'test payload'
        );

        // ----- 2) Publish the event -----
        Database.SaveResult sr = EventBus.publish(ev);
        System.assert(sr.isSuccess(), 'Platform event should publish successfully');
        Test.getEventBus().deliver();

    }
}