Doc/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

Doc/force-app/main/default/objects/Contract/fields/AVA_SFCPQ__AvaTaxMessage__c.field-meta.xml
<CustomField>
    <fullName>AVA_SFCPQ__AvaTaxMessage__c</fullName>
    <description>Displays AvaTax responses or messages.</description>
    <inlineHelpText>Displays AvaTax responses or messages.</inlineHelpText>
    <label>AvaTax Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/AVA_SFCPQ__Tax_Calculation_Status__c.field-meta.xml
<CustomField>
    <fullName>AVA_SFCPQ__Tax_Calculation_Status__c</fullName>
    <description>Displays the status of the tax.</description>
    <formula>IMAGE( 

CASE( AVA_SFCPQ__AvaTaxMessage__c , 

&quot;Tax Amount Is Up To Date&quot;, &quot;/img/msg_icons/confirm24.png&quot;, 

&quot;Automated Tax Calculation Triggered, Please Refresh Your Browser&quot;, &quot;/img/loading24.gif&quot;, 

&quot;Tax Amount is Outdated&quot;, &quot;/img/msg_icons/warning24.png&quot;, 

&quot;Committed&quot;, &quot;/img/msg_icons/confirm24.png&quot;,

&quot;&quot;, &quot;/img/msg_icons/warning24.png&quot;,

&quot;/img/msg_icons/error24.png&quot;), 

&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Displays the status of the tax.</inlineHelpText>
    <label>Tax Calculation Status</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Consolidated_Quote__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as Part for BIZ-47457. To store the consolidated quote in case of renewal contract consolidation.</description>
    <label>Consolidated Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Consolidated Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Renewal_to_be_created_Before_Days__c.field-meta.xml
<CustomField>
    <fullName>Renewal_to_be_created_Before_Days__c</fullName>
    <description>created to calculate when renewal quote will be created - BIZ-46128</description>
    <formula>IF( Text(Subsidiary__c) = &quot;18:DealCloud, Inc.&quot;  &amp;&amp;  Text(Contract_Master_Terms__c) = &quot;Legacy DealCloud Agreement&quot; , 30,
IF( Text(Subsidiary__c) = &quot;18:DealCloud, Inc.&quot;  &amp;&amp;  Text(Contract_Master_Terms__c)  &lt;&gt;  &quot;Legacy DealCloud Agreement&quot;,60,
90))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal to be created Before (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Quote_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Start_Date__c</fullName>
    <label>Quote Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Renewal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Start_Date__c</fullName>
    <formula>SBQQ__RenewedContract__r.EndDate + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/AVA_SFCPQ__AvaTaxMessage__c.field-meta.xml
<CustomField>
    <fullName>AVA_SFCPQ__AvaTaxMessage__c</fullName>
    <description>Displays AvaTax responses or messages.</description>
    <inlineHelpText>Displays AvaTax responses or messages.</inlineHelpText>
    <label>AvaTax Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/AVA_SFCPQ__Tax_Calculation_Status__c.field-meta.xml
<CustomField>
    <fullName>AVA_SFCPQ__Tax_Calculation_Status__c</fullName>
    <description>Displays the status of the tax.</description>
    <formula>IMAGE( 

CASE(      AVA_SFCPQ__AvaTaxMessage__c      , 

&quot;Tax Amount Is Up To Date&quot;, &quot;/img/msg_icons/confirm24.png&quot;, 

&quot;Automated Tax Calculation Triggered, Please Refresh Your Browser&quot;, &quot;/img/loading24.gif&quot;, 

&quot;Tax Amount is Outdated&quot;, &quot;/img/msg_icons/warning24.png&quot;, 
&quot;&quot;,&quot;&quot;,

&quot;/img/msg_icons/error24.png&quot;), 

&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Displays the status of the tax.</inlineHelpText>
    <label>Tax Calculation Status</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Proforma_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Renewal Letter record</description>
    <label>Proforma Invoice</label>
    <referenceTo>Proforma_Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/Proforma_Invoice__c.object-meta.xml
<CustomObject>
    <label>Renewal Letter</label>
    <nameField>
        <displayFormat>RL-{0000000}</displayFormat>
        <label>Renewal Letter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proforma_Invoice__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Created</fullName>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Order Activated</fullName>
            </value>
            <value>
                <fullName>Invoice Created</fullName>
            </value>
            <value>
                <fullName>Invoice Posted</fullName>
            </value>
            <value>
                <fullName>Payment Posted</fullName>
            </value>
            <value>
                <fullName>Sent Document to Contact</fullName>
            </value>
            <value>
                <fullName>No Payment created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Proforma_Invoice__c/fields/Days_remaining_for_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Days_remaining_for_Renewal__c</fullName>
    <formula>Renewal_Quote__r.SBQQ__StartDate__c -  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days remaining for Renewal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Proforma_Invoice__c/fields/Renewal_Quote__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Performa_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Proforma_Invoice__c/fields/Renewal_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Start_Date__c</fullName>
    <description>Start date of the related renewal Quote</description>
    <label>Renewal Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This field holds the information regarding the current state of renewal letter. This is primarily set in the Auto Renewal flow.
BIZ-66216</description>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proforma_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Payment received</fullName>
            </value>
            <value>
                <fullName>Working with Customer for changes</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Allocated</fullName>
            </value>
            <value>
                <fullName>No Response from Customer</fullName>
                <isActive>false</isActive>
                <label>No Response from Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <description>Sales user should be able to move a Quote to the Pricing Proposal stage when ready to create a Pricing Proposal Document, built as per BIZ-45102
Updated for story BIZ-49730..</description>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Configure Products</fullName>
                <default>true</default>
                <label>Configure Products</label>
            </value>
            <value>
                <fullName>Pricing Proposal</fullName>
            </value>
            <value>
                <fullName>Finalize OSA</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
            </value>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoRenewedQuoteActionsBatch.cls
/**
* @description Batch class for triggering actions on autorenewed quote which are within 30 days for renewal and renewal status is Initiated
* @author Sahal Mohamed
* @jira BIZ-66216
**/
public without sharing class AutoRenewedQuoteActionsBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

    /***********************************************************************************************
    *
    * props
    *
    ***********************************************************************************************/
    public Set<Id> quotesOrdered;
    public Set<Id> quoteIdsToOrder;
    private String query;
    private Integer scopeSize;
    private Set<String> taxMessagesToConsider = new Set<String>{
        'UNABLE_TO_LOCK_ROW', 
        'CANNOT_EXECUTE_FLOW_TRIGGER'
    };

    /***********************************************************************************************
    *
    * Constructors
    *
    ***********************************************************************************************/
    /**
    * @description Default Constructor
    **/
    public autoRenewedQuoteActionsBatch() {
        this.quotesOrdered = new Set<Id>();
        this.query = getDefaultQuery();
        this.scopeSize = 1;
        this.quoteIdsToOrder = new Set<Id>();

    }

    /**
    * @description parameterized Constructor
    * @param query
    * @param scopeSize
    **/
    public autoRenewedQuoteActionsBatch(String query, Integer scopeSize) {
        // Set the query and scope size
        this.quotesOrdered = new Set<Id>();
        this.query = query ?? getDefaultQuery();
        this.scopeSize = scopeSize ?? 1;
        this.quoteIdsToOrder = new Set<Id>();
    }

    /***********************************************************************************************
    *
    * Public Methods
    *
    ***********************************************************************************************/

    /**
    * @description Method that can be used to override the query and scope size
    * @param query
    * @param scopeSize
    **/
    public void executeBatch(String query, Integer scopeSize) {
        AutoRenewedQuoteActionsBatch obj = new AutoRenewedQuoteActionsBatch(query, scopeSize);
        Database.executeBatch(obj, scopeSize);
    }

    /***********************************************************************************************
    *
    * Batch Methods
    *
    ***********************************************************************************************/
    /**
    * @description start method
    * @param bc
    * @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query renewal letters that need to be processed
        String query = this.query;
        return Database.getQueryLocator(query);
    }

    /**
    * @description execute method
    * @param bc
    * @param renewalLetters
    **/
    public void execute(Database.BatchableContext bc, List<Proforma_Invoice__c> renewalLetters) {
        Nebula.Logger.info('AutoRenewedQuoteActionsBatch execute started with ' + renewalLetters.size() + ' renewal letters');
        
        BatchProcessingResult result = processRenewalLetters(renewalLetters);
        updateRecords(result);
        
        Nebula.Logger.info('AutoRenewedQuoteActionsBatch execute completed. Quotes to order: ' + quoteIdsToOrder.size());
        Nebula.Logger.saveLog();
    }

    /**
    * @description Processes renewal letters and returns the results
    * @param renewalLetters
    * @return BatchProcessingResult
    **/
    private BatchProcessingResult processRenewalLetters(List<Proforma_Invoice__c> renewalLetters) {
        BatchProcessingResult result = new BatchProcessingResult();
        
        for (Proforma_Invoice__c renLetter : renewalLetters) {
            processIndividualRenewalLetter(renLetter, result);
        }
        
        return result;
    }

    /**
    * @description Processes an individual renewal letter
    * @param renLetter
    * @param result
    **/
    private void processIndividualRenewalLetter(Proforma_Invoice__c renLetter, BatchProcessingResult result) {
        Nebula.Logger.info('Processing Renewal Letter: ' + renLetter.Id + ', Days Remaining: ' + renLetter.Days_remaining_for_Renewal__c + ', Status: ' + renLetter.Status__c + ', Activity Status: ' + renLetter.Activity_Status__c);
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c(Id = renLetter.Renewal_Quote__c);
        
        updateTaxCalculationIfNeeded(renLetter, quote);
        updateActivityStatusIfNeeded(renLetter);
        result.renLettersToUpdate.add(renLetter);
        
        if (shouldOrderQuote(renLetter)) {
            prepareQuoteForOrdering(renLetter, quote, result);
        }
    }

    /**
    * @description Updates tax calculation if needed
    * @param renLetter
    * @param quote
    **/
    private void updateTaxCalculationIfNeeded(Proforma_Invoice__c renLetter, SBQQ__Quote__c quote) {
        Nebula.Logger.info('Checking tax calculation - AvaTax Message: ' + renLetter.Renewal_Quote__r.AVA_SFCPQ__AvaTaxMessage__c);
        
        if (renLetter.Renewal_Quote__r.AVA_SFCPQ__AvaTaxMessage__c != QuoteConstants.AVA_TAX_MSG_UPTO_DATE && 
            taxMessagesToConsider.contains(renLetter.Renewal_Quote__r.AVA_SFCPQ__AvaTaxMessage__c)) {
            Nebula.Logger.info('Tax calculation needs update - setting AutomateTaxCalculation to true');
            quote.AVA_SFCPQ__Quote_AutomateTaxCalculation__c = true;
            quote.AVA_SFCPQ__AvaTaxMessage__c = QuoteConstants.AVA_TAX_MSG_REFRESH;
        }
    }

    /**
    * @description Updates activity status if needed
    * @param renLetter
    **/
    private void updateActivityStatusIfNeeded(Proforma_Invoice__c renLetter) {
        Decimal renewalBeforeDays = renLetter.Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Renewal_to_be_created_Before_Days__c;
        Nebula.Logger.info('Checking activity status update - Days remaining: ' + renLetter.Days_remaining_for_Renewal__c + ', Renewal before days: ' + renewalBeforeDays);
        
        if (renLetter.Days_remaining_for_Renewal__c <= renewalBeforeDays &&
            renLetter.Activity_Status__c != RenewalLetterConstants.ACTIVITY_STATUS_SEND_DOC_TO_CONTACT &&
            renLetter.Status__c == RenewalLetterConstants.STATUS_INITIATED) {
            
            Nebula.Logger.info('Updating Activity Status to Send Document to Contact');
            renLetter.Activity_Status__c = RenewalLetterConstants.ACTIVITY_STATUS_SEND_DOC_TO_CONTACT;
            renLetter.State__c = 'Activity Status updated to ' + renLetter.Activity_Status__c;
        }
    }

    /**
    * @description Checks if quote should be ordered
    * @param renLetter
    * @return Boolean
    **/
    private Boolean shouldOrderQuote(Proforma_Invoice__c renLetter) {
        Nebula.Logger.info('Checking quote ordering criteria - 30 day check');
        
        return renLetter.Days_remaining_for_Renewal__c <= 30 &&
               renLetter.Status__c == RenewalLetterConstants.STATUS_INITIATED &&
               renLetter.Renewal_Quote__r.SBQQ__Opportunity2__r.StageName != OpportunityConstants.STAGE_CLOSED_WON &&
               (renLetter.Activity_Status__c == RenewalLetterConstants.ACTIVITY_STATUS_SEND_DOC_TO_CONTACT || String.isBlank(renLetter.Activity_Status__c));
    }

    /**
    * @description Prepares quote for ordering
    * @param renLetter
    * @param quote
    * @param result
    **/
    private void prepareQuoteForOrdering(Proforma_Invoice__c renLetter, SBQQ__Quote__c quote, BatchProcessingResult result) {
        Date proposedCloseDate = (renLetter.Renewal_Quote__r.SBQQ__Opportunity2__r.Renewal_Start_Date__c != null)
            ? renLetter.Renewal_Quote__r.SBQQ__Opportunity2__r.Renewal_Start_Date__c.addDays(-30)
            : null;
        Nebula.Logger.info('30-day criteria met - preparing quote for ordering. Quote ID: ' + quote.Id + ', Proposed Close Date: ' + proposedCloseDate);
        
        quote.Quote_Stage__c = QuoteConstants.STATUS_CONTRACT_EXECUTED;
        quote.SBQQ__Primary__C = true;
        result.quotesToUpdate.add(quote);
        
        result.oppsToClose.add(new Opportunity(
            Id = renLetter.Renewal_Quote__r.SBQQ__Opportunity2__c,
            StageName = OpportunityConstants.STAGE_CLOSED_WON,
            CloseDate = proposedCloseDate
        ));
    }

    /**
    * @description Updates records in database
    * @param result
    **/
    private void updateRecords(BatchProcessingResult result) {
        updateRenewalLetters(result.renLettersToUpdate);
        updateQuotes(result.quotesToUpdate);
        updateOpportunities(result.oppsToClose);
        
        for (SBQQ__Quote__c quote : result.quotesToUpdate) {
            quoteIdsToOrder.add(quote.Id);
        }
    }

    /**
    * @description Updates renewal letters
    * @param renLettersToUpdate
    **/
    private void updateRenewalLetters(List<Proforma_Invoice__c> renLettersToUpdate) {
        Nebula.Logger.info('Updating ' + renLettersToUpdate.size() + ' renewal letters');
        try {
            update renLettersToUpdate;
            Nebula.Logger.info('Successfully updated ' + renLettersToUpdate.size() + ' renewal letters');
            
            // Update state tracking
            renLettersToUpdate = RenewalLetterUtil.updateRenewalLetterState(renLettersToUpdate, 'Renewal Letter state updated');
            update renLettersToUpdate;
            Nebula.Logger.info('Successfully updated renewal letter state tracking for ' + renLettersToUpdate.size() + ' records');
        } catch (Exception e) {
            Nebula.Logger.error('AutoRenewedQuoteActionsBatch Update Renewal Letters', renLettersToUpdate, e);
            Nebula.Logger.saveLog();
        }
    }

    /**
    * @description Updates quotes
    * @param quotesToUpdate
    **/
    private void updateQuotes(List<SBQQ__Quote__c> quotesToUpdate) {
        if (quotesToUpdate.isEmpty()) {
            return;
        }
        
        Nebula.Logger.info('Updating ' + quotesToUpdate.size() + ' quotes to Contract Executed status');
        try {
            update quotesToUpdate;
            Nebula.Logger.info('Successfully updated ' + quotesToUpdate.size() + ' quotes to Contract Executed status');
        } catch (Exception e) {
            Nebula.Logger.error('AutoRenewedQuoteActionsBatch Update Quotes', quotesToUpdate, e);
            Nebula.Logger.saveLog();
        }
    }

    /**
    * @description Updates opportunities
    * @param oppsToClose
    **/
    private void updateOpportunities(List<Opportunity> oppsToClose) {
        if (oppsToClose.isEmpty()) {
            return;
        }
        
        Nebula.Logger.info('Closing ' + oppsToClose.size() + ' opportunities');
        try {
            update oppsToClose;
            Nebula.Logger.info('Successfully closed ' + oppsToClose.size() + ' opportunities');
        } catch (Exception e) {
            Nebula.Logger.error('AutoRenewedQuoteActionsBatch Close Opps', oppsToClose, e);
        }
    }

    /**
    * @description Inner class to hold batch processing results
    **/
    private class BatchProcessingResult {
        public List<Opportunity> oppsToClose = new List<Opportunity>();
        public List<Proforma_Invoice__c> renLettersToUpdate = new List<Proforma_Invoice__c>();
        public List<SBQQ__Quote__c> quotesToUpdate = new List<SBQQ__Quote__c>();
    }

    /**
    * @description finish method
    * @param bc
    **/
    public void finish(Database.BatchableContext bc) {
        Nebula.Logger.info('AutoRenewedQuoteActionsBatch finish method started');
        
        if(quoteIdsToOrder.size() > 0) {
            Nebula.Logger.info('Executing OrderQuoteBatch for ' + quoteIdsToOrder.size() + ' quotes: ' + quoteIdsToOrder);
            OrderQuoteBatch obj = new OrderQuoteBatch(quoteIdsToOrder);
            Database.executeBatch(obj, 1);
        } else {
            Nebula.Logger.info('No quotes to order - OrderQuoteBatch will not be executed');
        }
        
        Nebula.Logger.saveLog();
    }

    /***********************************************************************************************
    *
    * Schedulable Methods
    *
    ***********************************************************************************************/
    /**
    * @description execute method
    * @param sc
    **/
    public void execute(SchedulableContext sc) {
        // Execute the batch job
        executeBatch(this.query, this.scopeSize);
    }

    /***********************************************************************************************
    *
    * Private Methods
    *
    ***********************************************************************************************/
    /**
    * @description set the default query
    * @return String
    **/
    private String getDefaultQuery() {
        
        // Set the default query based on the business logic
        String defaultQuery = 'SELECT Id, Activity_Status__c, Days_Remaining_for_Renewal__c , Renewal_Quote__r.AVA_SFCPQ__AvaTaxMessage__c, ' + 
                                    'Renewal_Quote__r.AVA_SFCPQ__Tax_Calculation_Status__c, Status__c, Renewal_Quote__r.SBQQ__Opportunity2__r.Quote_Start_Date__c, ' +
                                    'Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Renewal_to_be_created_Before_Days__c, ' +
            						'Renewal_Quote__r.SBQQ__Opportunity2__r.IsClosed, Renewal_Quote__r.SBQQ__Opportunity2__r.StageName, Renewal_Quote__r.SBQQ__Opportunity2__r.Renewal_Start_Date__c ' +
                                'FROM Proforma_Invoice__c ' +
                                'WHERE Days_remaining_for_Renewal__c <= 90 AND Status__c = \''+RenewalLetterConstants.STATUS_INITIATED+ '\' ' +
                                'AND Renewal_Quote__r.SBQQ__Primary__c = TRUE ' +
                                'AND Renewal_Quote__r.SBQQ__Opportunity2__r.IsClosed = FALSE ' +
                                'AND Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Status != \'' + ContractConstants.STATUS_CANCELLED_LAPSED + '\' ' +
                                'AND Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Status != \'' + ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT + '\' ' +
                                'AND (Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Consolidated_Quote__c = null ' +
                                'OR Renewal_Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Consolidated_Quote__r.SBQQ__Opportunity2__r.StageName != \'' + OpportunityConstants.STAGE_CLOSED_WON + '\')';

        return defaultQuery;
    }

}