Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Expected_Signaure_Date_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Signaure_Date_Booking_Date__c</fullName>
    <label>Expected Signature Date / Booking Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Term_Quote__c/Term_Quote__c.object-meta.xml
<CustomObject>
    <description>Junction object of SBQQ__Quote__c and SBQQ__QuoteTerm__c usied to generate terms for specific quote</description>
    <label>Term Quote</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Term Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Term_Quote__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Doc/force-app/main/default/objects/Term_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/classes/TermQuoteTest.cls
@isTest
public class TermQuoteTest {
    
    testmethod static void testTermQuotes(){
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        quote.Expected_Signaure_Date_Booking_Date__c = System.today().addDays(-75);
        insert quote;
        
        Term_Quote__c termQuote = new Term_Quote__c();
        termQuote.Body__c = '<p>This is a test method </p>';
        termQuote.Quote__c = quote.Id;
        insert termQuote;
        
        termQuote.Body__c = '<p>This is test method testing..</p>';
        update termQuote;
        
        System.assertEquals(termQuote.Body__c,'<p>This is test method testing..</p>');
    } 

}