Doc/force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QTC_GreenboxApproveAll.cls
public without sharing class QTC_GreenboxApproveAll {
    @InvocableMethod(label='Approve all pending approvals')
    public static List<Id> approveAllOpenApprovals(List<String> lstQuoteId){
        List<sbaa__Approval__c> lstApprovals = new List<sbaa__Approval__c>();
        List<String> lstPendingApprovalStatuses = label.QTC_ApproveAllStatuses.split(',');
        List<SBQQ__Quote__c> quoteListToUpdate = new List<SBQQ__Quote__c>();
        Set<Id> quoteIdSet = new Set<Id>();
        lstApprovals = [SELECT Id,Name,Quote__c FROM sbaa__Approval__c WHERE Quote__c  =: lstQuoteId[0].substringBefore('-$-') AND sbaa__Status__c IN :lstPendingApprovalStatuses];
        if(FeatureManagement.checkPermission('Approve_All')){
            for(sbaa__Approval__c oApproval : lstApprovals){
                oApproval.sbaa__Status__c = 'Approved';
                oApproval.sbaa__CommentsLong__c = lstQuoteId[0].substringAfter('-$-');
                oApproval.sbaa__AssignedTo__c = userInfo.getUserId();
                oApproval.sbaa__ApprovedBy__c = userInfo.getUserId();
                quoteIdSet.add(oApproval.Quote__c);
                system.debug('============'+oApproval.Name);
            }
            for(Id quoteId: quoteIdSet){
                quoteListToUpdate.add(new SBQQ__Quote__c(Id=quoteId, ApprovalStatus__c = 'Approved'));
            }
            system.debug('========='+lstApprovals.size());
            update lstApprovals;
            update quoteListToUpdate;
        }        
        return null;
    }
}