force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <label>Product Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Master_Product__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>DO NOT USE Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>Risk and Compliance</fullName>
                <label>Risk &amp; Compliance</label>
            </value>
            <value>
                <fullName>Practice &amp; Finance</fullName>
                <label>Operations &amp; Finance</label>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Partners</fullName>
                <label>Leaders &amp; Professionals</label>
            </value>
            <value>
                <fullName>Content/KM</fullName>
                <label>Knowledge &amp; Content</label>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Compliguard</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Lateral Hire</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Workflow</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Item Master Products</relationshipLabel>
    <relationshipName>Item_Master_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <description>This field contains all the Deployment Types from the Product Lines. Created as part of BIZ-67837</description>
    <formula>TEXT(Product_LineNew__r.Deployment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deployment</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Integrate</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Product_Rollup__c</fullName>
    <label>Product Rollup</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Line_Rollup__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrate Limited License - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - Box Builder</fullName>
            </value>
            <value>
                <fullName>Integrate - Smartlink</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Integrate Standard</fullName>
            </value>
            <value>
                <fullName>Attorny Acknowledgments</fullName>
            </value>
            <value>
                <fullName>Activity Tracker</fullName>
            </value>
            <value>
                <fullName>Advanced Conflicts Cloud</fullName>
            </value>
            <value>
                <fullName>Auditing Package</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Confidentiality Package</fullName>
            </value>
            <value>
                <fullName>Standard (Connected) Conflicts Cloud</fullName>
            </value>
            <value>
                <fullName>Contractors</fullName>
            </value>
            <value>
                <fullName>Regulatory Reporting</fullName>
            </value>
            <value>
                <fullName>DMS Package</fullName>
            </value>
            <value>
                <fullName>Dynamic Groups</fullName>
            </value>
            <value>
                <fullName>Intake Standard - On Prem</fullName>
            </value>
            <value>
                <fullName>Lawyer Portal</fullName>
            </value>
            <value>
                <fullName>Legal Holds</fullName>
            </value>
            <value>
                <fullName>Intake - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Walls 2020 On-Prem (fka Advanced Security)</fullName>
            </value>
            <value>
                <fullName>Team Manager</fullName>
            </value>
            <value>
                <fullName>People, Places &amp; Printers</fullName>
            </value>
            <value>
                <fullName>Additional Security Extensions</fullName>
            </value>
            <value>
                <fullName>Wall Builder</fullName>
            </value>
            <value>
                <fullName>DTE</fullName>
            </value>
            <value>
                <fullName>eBillingHub Module</fullName>
            </value>
            <value>
                <fullName>Time Builder</fullName>
            </value>
            <value>
                <fullName>Self Maintaining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

Doc/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <description>(PM) - A line of products limited to a single practice</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Product_Line__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Knowledge &amp; Content</fullName>
            </value>
            <value>
                <fullName>AI &amp; Platform</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Professionals</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
                <label>Time</label>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
            <value>
                <fullName>OnePlace</fullName>
            </value>
            <value>
                <fullName>Collaborations &amp; Content</fullName>
                <label>Collaboration</label>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product_Rollup__c/Product_Rollup__c.object-meta.xml
<CustomObject>
    <description>This new object in SFDC will carry same info as that of OP4I Product Rollup object</description>
    <label>Product Rollup</label>
    <nameField>
        <label>Product Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rollups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Product_Rollup__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Product Line Object - Product Line Name field</description>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Rollups</relationshipLabel>
    <relationshipName>Product_Rollups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SkuLookupController.cls
/**
 * @description Shared lookup/search controller for the SKU Management App.
 *              Provides search methods for Product2, Product_Line__c, Pricebook2,
 *              Product_Rollup__c, and Item_Master_Product__c.
 *              Returns results compatible with the existing c-lookup component.
 */
public with sharing class SkuLookupController {

    private static final Integer MAX_RESULTS = 20;

    @AuraEnabled(cacheable=true)
    public static List<LookupResult> searchProducts(String searchTerm) {
        if (String.isBlank(searchTerm) || searchTerm.length() < 2) {
            return new List<LookupResult>();
        }
        String key = '%' + String.escapeSingleQuotes(searchTerm.trim()) + '%';
        List<LookupResult> results = new List<LookupResult>();
        for (Product2 p : [
            SELECT Id, Name, ProductCode, Product_LineNew__r.Name, IsActive
            FROM Product2
            WHERE (Name LIKE :key OR ProductCode LIKE :key)
              AND IsActive = true
            ORDER BY Name ASC
            LIMIT :MAX_RESULTS
        ]) {
            String subtitle = p.ProductCode != null ? p.ProductCode : '';
            if (p.Product_LineNew__r != null && p.Product_LineNew__r.Name != null) {
                subtitle += (String.isNotBlank(subtitle) ? ' | ' : '') + p.Product_LineNew__r.Name;
            }
            results.add(new LookupResult(p.Id, p.Name, subtitle, 'standard:product'));
        }
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupResult> searchProductLines(String searchTerm) {
        if (String.isBlank(searchTerm) || searchTerm.length() < 2) {
            return new List<LookupResult>();
        }
        String key = '%' + String.escapeSingleQuotes(searchTerm.trim()) + '%';
        List<LookupResult> results = new List<LookupResult>();
        for (Product_Line__c pl : [
            SELECT Id, Name, Practice__c, Deployment__c
            FROM Product_Line__c
            WHERE Name LIKE :key AND Active__c = true
            ORDER BY Name ASC
            LIMIT :MAX_RESULTS
        ]) {
            String subtitle = '';
            if (pl.Practice__c != null) {
                subtitle = pl.Practice__c;
            }
            if (pl.Deployment__c != null) {
                subtitle += (String.isNotBlank(subtitle) ? ' | ' : '') + pl.Deployment__c;
            }
            results.add(new LookupResult(pl.Id, pl.Name, subtitle, 'standard:product_required'));
        }
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupResult> searchPricebooks(String searchTerm) {
        if (String.isBlank(searchTerm) || searchTerm.length() < 2) {
            return new List<LookupResult>();
        }
        String key = '%' + String.escapeSingleQuotes(searchTerm.trim()) + '%';
        List<LookupResult> results = new List<LookupResult>();
        for (Pricebook2 pb : [
            SELECT Id, Name, IsActive, CurrencyIsoCode
            FROM Pricebook2
            WHERE Name LIKE :key AND IsActive = true
            ORDER BY Name ASC
            LIMIT :MAX_RESULTS
        ]) {
            results.add(new LookupResult(
                pb.Id, pb.Name,
                pb.CurrencyIsoCode != null ? pb.CurrencyIsoCode : '',
                'standard:pricebook'
            ));
        }
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupResult> searchProductRollups(String searchTerm) {
        if (String.isBlank(searchTerm) || searchTerm.length() < 2) {
            return new List<LookupResult>();
        }
        String key = '%' + String.escapeSingleQuotes(searchTerm.trim()) + '%';
        List<LookupResult> results = new List<LookupResult>();
        for (Product_Rollup__c pr : [
            SELECT Id, Name, Product_Line__r.Name, Description__c
            FROM Product_Rollup__c
            WHERE Name LIKE :key
            ORDER BY Name ASC
            LIMIT :MAX_RESULTS
        ]) {
            String subtitle = pr.Product_Line__r != null && pr.Product_Line__r.Name != null
                ? pr.Product_Line__r.Name : '';
            results.add(new LookupResult(pr.Id, pr.Name, subtitle, 'standard:product_item'));
        }
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<LookupResult> searchItemMasterProducts(String searchTerm) {
        if (String.isBlank(searchTerm) || searchTerm.length() < 2) {
            return new List<LookupResult>();
        }
        String key = '%' + String.escapeSingleQuotes(searchTerm.trim()) + '%';
        List<LookupResult> results = new List<LookupResult>();
        for (Item_Master_Product__c imp : [
            SELECT Id, Name, Item_Name__c, Active__c
            FROM Item_Master_Product__c
            WHERE (Name LIKE :key OR Item_Name__c LIKE :key)
            ORDER BY Name ASC
            LIMIT :MAX_RESULTS
        ]) {
            String subtitle = imp.Item_Name__c != null ? imp.Item_Name__c : '';
            if (!imp.Active__c) {
                subtitle += ' (Inactive)';
            }
            results.add(new LookupResult(imp.Id, imp.Name, subtitle, 'standard:product_item_transaction'));
        }
        return results;
    }

    public class LookupResult {
        @AuraEnabled public String id;
        @AuraEnabled public String sObjectType;
        @AuraEnabled public String title;
        @AuraEnabled public String subtitle;
        @AuraEnabled public String icon;

        public LookupResult(String id, String title, String subtitle, String icon) {
            this.id = id;
            this.title = title;
            this.subtitle = subtitle;
            this.icon = icon;
        }
    }
}