force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <label>Product Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Master_Product__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>DO NOT USE Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>Risk and Compliance</fullName>
                <label>Risk &amp; Compliance</label>
            </value>
            <value>
                <fullName>Practice &amp; Finance</fullName>
                <label>Operations &amp; Finance</label>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Partners</fullName>
                <label>Leaders &amp; Professionals</label>
            </value>
            <value>
                <fullName>Content/KM</fullName>
                <label>Knowledge &amp; Content</label>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Compliguard</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Lateral Hire</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Workflow</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <description>This field contains all the Deployment Types from the Product Lines. Created as part of BIZ-67837</description>
    <formula>TEXT(Product_LineNew__r.Deployment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deployment</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Integrate</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Product_Rollup__c</fullName>
    <label>Product Rollup</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Line_Rollup__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrate Limited License - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - Box Builder</fullName>
            </value>
            <value>
                <fullName>Integrate - Smartlink</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Integrate Standard</fullName>
            </value>
            <value>
                <fullName>Attorny Acknowledgments</fullName>
            </value>
            <value>
                <fullName>Activity Tracker</fullName>
            </value>
            <value>
                <fullName>Advanced Conflicts Cloud</fullName>
            </value>
            <value>
                <fullName>Auditing Package</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Confidentiality Package</fullName>
            </value>
            <value>
                <fullName>Standard (Connected) Conflicts Cloud</fullName>
            </value>
            <value>
                <fullName>Contractors</fullName>
            </value>
            <value>
                <fullName>Regulatory Reporting</fullName>
            </value>
            <value>
                <fullName>DMS Package</fullName>
            </value>
            <value>
                <fullName>Dynamic Groups</fullName>
            </value>
            <value>
                <fullName>Intake Standard - On Prem</fullName>
            </value>
            <value>
                <fullName>Lawyer Portal</fullName>
            </value>
            <value>
                <fullName>Legal Holds</fullName>
            </value>
            <value>
                <fullName>Intake - On Prem (Generic)</fullName>
            </value>
            <value>
                <fullName>Walls 2020 On-Prem (fka Advanced Security)</fullName>
            </value>
            <value>
                <fullName>Team Manager</fullName>
            </value>
            <value>
                <fullName>People, Places &amp; Printers</fullName>
            </value>
            <value>
                <fullName>Additional Security Extensions</fullName>
            </value>
            <value>
                <fullName>Wall Builder</fullName>
            </value>
            <value>
                <fullName>DTE</fullName>
            </value>
            <value>
                <fullName>eBillingHub Module</fullName>
            </value>
            <value>
                <fullName>Time Builder</fullName>
            </value>
            <value>
                <fullName>Self Maintaining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

Doc/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <description>(PM) - A line of products limited to a single practice</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is used to determine if this field should be available for use in the Product Line lookup fields.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Product_Line__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <description>Field used to show what the deployment type of the Product Line is. This is used in the data warehouse.</description>
    <label>Deployment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>On-Premise</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product_Line__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Knowledge &amp; Content</fullName>
            </value>
            <value>
                <fullName>AI &amp; Platform</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Professionals</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
                <label>Time</label>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
            <value>
                <fullName>OnePlace</fullName>
            </value>
            <value>
                <fullName>Collaborations &amp; Content</fullName>
                <label>Collaboration</label>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product_Rollup__c/Product_Rollup__c.object-meta.xml
<CustomObject>
    <description>This new object in SFDC will carry same info as that of OP4I Product Rollup object</description>
    <label>Product Rollup</label>
    <nameField>
        <label>Product Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rollups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Product_Rollup__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to Product Line Object - Product Line Name field</description>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Rollups</relationshipLabel>
    <relationshipName>Product_Rollups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SkuLookupControllerTest.cls
@IsTest
private class SkuLookupControllerTest {

    @TestSetup
    static void setupTestData() {
        Product_Line__c productLine = new Product_Line__c(
            Name = 'Test Product Line',
            Active__c = true,
            Deployment__c = 'Cloud',
            Practice__c = 'DealCloud'
        );
        insert productLine;

        Product_Rollup__c productRollup = new Product_Rollup__c(
            Name = 'Test Rollup',
            Product_Line__c = productLine.Id
        );
        insert productRollup;

        Item_Master_Product__c itemMaster = new Item_Master_Product__c(
            Name = 'IMP-TEST001',
            Item_Name__c = 'Test Item Master',
            Active__c = true,
            Product_LineNew__c = productLine.Id
        );
        insert itemMaster;

        Product2 product = new Product2(
            Name = 'Test SKU Product',
            ProductCode = 'TST-001',
            IsActive = true,
            Product_LineNew__c = productLine.Id,
            Item_Master_Product__c = itemMaster.Id
        );
        insert product;

        Id stdPricebookId = Test.getStandardPricebookId();

        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = stdPricebookId,
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true,
            UseStandardPrice = false
        );
        insert pbe;
    }

    @IsTest
    static void testSearchProducts() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProducts('Test SKU');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find at least one product');
        System.assertEquals('Test SKU Product', results[0].title, 'Product name should match');
    }

    @IsTest
    static void testSearchProductsShortTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProducts('T');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for short search terms');
    }

    @IsTest
    static void testSearchProductsBlankTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProducts('');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for blank search terms');
    }

    @IsTest
    static void testSearchProductsByCode() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProducts('TST-001');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find product by code');
    }

    @IsTest
    static void testSearchProductLines() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProductLines('Test Product');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find at least one product line');
        System.assertEquals('Test Product Line', results[0].title, 'Product line name should match');
    }

    @IsTest
    static void testSearchProductLinesShortTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProductLines('T');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for short search terms');
    }

    @IsTest
    static void testSearchPricebooks() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchPricebooks('Standard');
        Test.stopTest();

        // Standard pricebook may or may not match depending on org setup
        System.assertNotEquals(null, results, 'Should return a non-null list');
    }

    @IsTest
    static void testSearchPricebooksShortTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchPricebooks('S');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for short search terms');
    }

    @IsTest
    static void testSearchProductRollups() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProductRollups('Test Rollup');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find at least one product rollup');
        System.assertEquals('Test Rollup', results[0].title, 'Product rollup name should match');
    }

    @IsTest
    static void testSearchProductRollupsShortTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchProductRollups('T');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for short search terms');
    }

    @IsTest
    static void testSearchItemMasterProducts() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchItemMasterProducts('IMP-TEST');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find at least one item master');
        System.assertEquals('IMP-TEST001', results[0].title, 'Item master name should match');
    }

    @IsTest
    static void testSearchItemMasterProductsByItemName() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchItemMasterProducts('Test Item');
        Test.stopTest();

        System.assertNotEquals(0, results.size(), 'Should find item master by item name');
    }

    @IsTest
    static void testSearchItemMasterProductsShortTerm() {
        Test.startTest();
        List<SkuLookupController.LookupResult> results = SkuLookupController.searchItemMasterProducts('I');
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty for short search terms');
    }
}