Doc/force-app/main/default/objects/SBQQ__RelatedContent__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <description>Created as part of BIZ-65215</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SOW -  Draft</fullName>
    </customValue>
    <customValue>
        <fullName>SOW - Ready for Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>MSSA - Ready for Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>MSSA - Ready for Signature (not attached to OSA)</fullName>
    </customValue>
    <customValue>
        <fullName>MSSA - Signed</fullName>
    </customValue>
    <customValue>
        <fullName>OSA - Redlined</fullName>
    </customValue>
    <customValue>
        <fullName>OSA - Signed</fullName>
    </customValue>
    <customValue>
        <fullName>OSA/MSSA Packaged - Redlined</fullName>
    </customValue>
    <customValue>
        <fullName>OSA/MSSA Packaged - Signed</fullName>
    </customValue>
    <customValue>
        <fullName>MSSA Related Document</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Amendment - Redlined</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Amendment - Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Configurator</fullName>
    </customValue>
    <customValue>
        <fullName>PSE</fullName>
    </customValue>
    <customValue>
        <fullName>Demo Cheat Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>Account Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Rel Intel Pre-Sales Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase Order</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge Transfer Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Partnership Agreement / Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Sales &amp; Marketing Content</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Technical Content</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Capability Content</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Management Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Standard Solution Proposal (SSP)</fullName>
    </customValue>
    <customValue>
        <fullName>RAGSBRUV</fullName>
    </customValue>
    <customValue>
        <fullName>Firm Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Conga Generated OSA</fullName>
    </customValue>
    <description>Global list for document types</description>
    <masterLabel>Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AttachmentTriggerHandler.cls
public class AttachmentTriggerHandler {
	public Static void attachmentAfterInsert(map<Id,Attachment> mapNewAttachment) {
        Map<Id,Set<String>> mapAttachmentIdSetOfAdditionalDoc = new Map<Id,Set<String>>();
        List<SBQQ__RelatedContent__c> lstAdditionalDocumentInsert = new List<SBQQ__RelatedContent__c>();
        List<SBQQ__RelatedContent__c> lstAdditionalDocumentDelete = new List<SBQQ__RelatedContent__c>();
        Set<Id> setAttachmentIds = new Set<Id>();
        Set<Id> setQuoteIds = new Set<Id>();
        
        for(Attachment oAttachment : mapNewAttachment.values()){
            if(oAttachment.ParentId.getSObjectType().getDescribe().getName().equalsIgnoreCase('SBQQ__Quote__c') && (oAttachment.Name.containsIgnoreCase('bundle') || oAttachment.Name.containsIgnoreCase('_Amendment_'))){
                setAttachmentIds.add(oAttachment.Id);
                setQuoteIds.add(oAttachment.ParentId);
            }
        }
        
        // Added Document Type via BIZ-73733
        lstAdditionalDocumentDelete = [SELECT ID FROM SBQQ__RelatedContent__c WHERE SBQQ__Quote__c IN :setQuoteIds AND (NAME LIKE '%_bundle_%' OR NAME LIKE '%_Amendment_%') AND Document_Type__c = 'Conga Generated OSA'];
        
        if(setAttachmentIds != null && setAttachmentIds.size() > 0){
        	for(SBQQ__RelatedContent__c oAdditionalDocument : [SELECT Id, SBQQ__ExternalId__c FROM SBQQ__RelatedContent__c WHERE SBQQ__ExternalId__c IN :setAttachmentIds]){
                Set<String> setAdditionalDocIds = new Set<String>();
                if(mapAttachmentIdSetOfAdditionalDoc != null && mapAttachmentIdSetOfAdditionalDoc.containsKey(oAdditionalDocument.SBQQ__ExternalId__c)){
                    setAdditionalDocIds.addAll(mapAttachmentIdSetOfAdditionalDoc.get(oAdditionalDocument.SBQQ__ExternalId__c));               
                }
                setAdditionalDocIds.add(oAdditionalDocument.Id);
                mapAttachmentIdSetOfAdditionalDoc.put(oAdditionalDocument.SBQQ__ExternalId__c,setAdditionalDocIds);              
            }
            
            for(Attachment oAttachment : mapNewAttachment.values()){
                if(!mapAttachmentIdSetOfAdditionalDoc.containsKey(oAttachment.Id)){
                    // Added Document Type via BIZ-73733
                    SBQQ__RelatedContent__c relatedContent = new SBQQ__RelatedContent__c(
                        Name=oAttachment.Name, 
                        SBQQ__DisplayOrder__c=1, 
                        SBQQ__ExternalId__c=oAttachment.Id, 
                        SBQQ__Quote__c=oAttachment.parentId, 
                        SBQQ__Required__c=true
                    );
                    if (UserInfo.getName() != Label.Biz_App_UserName) {
                        relatedContent.Document_Type__c = 'Conga Generated OSA';
                    }
                    lstAdditionalDocumentInsert.add(relatedContent);   
                }            
            }
            if(lstAdditionalDocumentDelete!=null && lstAdditionalDocumentDelete.size()>0){
                for(SBQQ__RelatedContent__c oAdditionalDocument: lstAdditionalDocumentDelete){
                    oAdditionalDocument.SBQQ__Quote__c = null;
                    oAdditionalDocument.SBQQ__ExternalId__c = oAdditionalDocument.Id;
                }
                update lstAdditionalDocumentDelete;
                delete lstAdditionalDocumentDelete;
            }
            if(lstAdditionalDocumentInsert!=null && lstAdditionalDocumentInsert.size() > 0){
                insert lstAdditionalDocumentInsert;
            }   
        }        
    }
}