Doc/force-app/main/default/objects/Intapp_Pricing__c/Intapp_Pricing__c.object-meta.xml
<CustomObject>
    <label>Intapp Pricing</label>
    <nameField>
        <label>Intapp Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intapp Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Intapp_Pricing__c/fields/Intapp_ID__c.field-meta.xml
<CustomField>
    <fullName>Intapp_ID__c</fullName>
    <description>This will hold the OP4I Internal ID - to keep the mapping in sync between both the systems Intapp Pricing Object</description>
    <label>Intapp ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Intapp_Pricing__c/fields/Premium_price__c.field-meta.xml
<CustomField>
    <fullName>Premium_price__c</fullName>
    <label>Premium price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/Intapp_Pricing__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Field holds the value of price including support</description>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Intapp_Pricing__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Intapp Pricings</relationshipLabel>
    <relationshipName>Intapp_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intapp_Pricing__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Field to hold value of product code</description>
    <label>Product Code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Intapp_Pricing__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier A</fullName>
            </value>
            <value>
                <fullName>Tier B</fullName>
            </value>
            <value>
                <fullName>Tier C</fullName>
            </value>
            <value>
                <fullName>Tier D</fullName>
            </value>
            <value>
                <fullName>Tier E</fullName>
            </value>
            <value>
                <fullName>Tier (none)</fullName>
            </value>
            <value>
                <fullName>EM1</fullName>
            </value>
            <value>
                <fullName>EM2</fullName>
            </value>
            <value>
                <fullName>EM3</fullName>
            </value>
            <value>
                <fullName>EM4</fullName>
            </value>
            <value>
                <fullName>EM5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntappPricingHandlerTest.cls
@isTest public class IntappPricingHandlerTest {
    /* Test */
    @isTest 
    static void testMethod1(){
        Intapp_Pricing__c intapppriceObj = (Intapp_Pricing__c) SmartFactory.createSObject('Intapp_Pricing__c');
        intapppriceObj.Name = 'Testintappprice';
        intapppriceObj.CurrencyIsoCode = 'USD';
        intapppriceObj.Tier__c = 'Tier A';
        intapppriceObj.Price_Book__c = Test.getStandardPricebookId();
        intapppriceObj.Product_Code__c = 'Test Product';
        intapppriceObj.Price__c = 50;
        insert intapppriceObj;
        List<Intapp_Pricing__c> pList = new List<Intapp_Pricing__c>();
        List<Intapp_Pricing__c> pList2 = new List<Intapp_Pricing__c>();
        pList.add(intapppriceObj);
        Test.startTest();
        IntappPricingHandler.intappPriceAfterInsert(pList);
        pList2.add(intapppriceObj);
        pList2[0].Intapp_ID__c = 'test';
        pList2[0].Premium_price__c = 123;
        update pList2;
        system.assertNotEquals(null,pList2,'Product');
        Test.stopTest();
    }
}