force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for POC, will hold Account information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Captures full Address of the Account</description>
    <label>Address</label>
    <type>Address</type>
</CustomField>

Doc/force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Default Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReportToAddressBatchTest.cls
@isTest
public class ReportToAddressBatchTest {
    
    @isTest
    static void testSameAddressWithBilling() {
        // Create accounts
        List<Account> testAccts = new List<Account>();
        Account testAccount = IntappTestObjectFactory.createaccount(false);
        testAccount.Type = 'Client';
        testAccount.BillingCity = 'Idaho';
        testAccount.ShippingCity = 'Idaho';
        testAccount.BillingCountry = 'United States';
        testAccount.ShippingCountry = 'United States';
        testAccount.BillingStreet = '5012 Coulter Lane';
        testAccount.ShippingStreet = '5012 Coulter Lane';
        testAccount.BillingState = 'Alaska';
        testAccount.ShippingState = 'Alaska';
        testAccount.BillingPostalCode = '23005';
        testAccount.ShippingPostalCode = '23005';
        testAccts.add(testAccount);
        insert testAccts;

        Address__c address = new Address__c();
        address.Address__Street__s = '5012 Coulter Lane';
        address.Address__City__s = 'Idaho';
        address.Address__StateCode__s = 'AK';
        address.Address__CountryCode__s = 'US';
        address.Address__PostalCode__s = '23005';
        address.Type__c = 'Billing';
        address.Account__c = testAccount.Id;
        insert address;
        
        Test.startTest();
        ReportToAddressBatch reportToAddressBatchObj = new ReportToAddressBatch();
        Database.executeBatch(reportToAddressBatchObj, 10);
        Test.stopTest();
        System.assertEquals(1, testAccts.size());
    }
    
    @isTest
    static void testSameAddressWithShipping() {
        // Create accounts
        List<Account> testAccts = new List<Account>();
        Account testAccount = IntappTestObjectFactory.createaccount(false);
        testAccount.Type = 'Client';
        testAccount.BillingCity = 'Arlington';
        testAccount.ShippingCity = 'Arlington';
        testAccount.BillingCountry = 'United States';
        testAccount.ShippingCountry = 'United States';
        testAccount.BillingStreet = '4148 Coulter Lane';
        testAccount.ShippingStreet = '4148 Coulter Lane';
        testAccount.BillingState = 'Alaska';
        testAccount.ShippingState = 'Alaska';
        testAccount.BillingPostalCode =  '23005';
        testAccount.ShippingPostalCode = '23005';
        testAccts.add(testAccount);

        insert testAccts;
        
        Address__c address = new Address__c();
        address.Address__Street__s = '4148 Coulter Lane';
        address.Address__City__s = 'Arlington';
        address.Address__StateCode__s = 'ID';
        address.Address__CountryCode__s = 'US';
        address.Address__PostalCode__s = '23005';
        address.Type__c = 'Shipping';
        address.Account__c = testAccount.Id;
        insert address;
        
        Test.startTest();
        ReportToAddressBatch reportToAddressBatchObj = new ReportToAddressBatch();
        Database.executeBatch(reportToAddressBatchObj, 10);
        Test.stopTest();
        System.assertEquals(1, testAccts.size());
    }
    
    @isTest
    static void testDifferentAddress() {
        // Create accounts
        List<Account> testAccts = new List<Account>();
        Account testAccount = IntappTestObjectFactory.createaccount(false);
        testAccount.Type = 'Client';
        testAccount.BillingCity = 'Arlington';
        testAccount.ShippingCity = 'Chicago';
        testAccount.BillingCountry = 'United States';
        testAccount.ShippingCountry = 'United States';
        testAccount.BillingStreet = '4148 Coulter Lane';
        testAccount.ShippingStreet = '4028 Jewell Road';
        testAccount.BillingState = 'Alaska';
        testAccount.ShippingState = 'Idaho';
        testAccount.BillingPostalCode =  '23005';
        testAccount.ShippingPostalCode = '55404';
        testAccts.add(testAccount);

        insert testAccts;

        Address__c address = new Address__c();
        address.Address__Street__s = '4148 Coulter Lane';
        address.Address__City__s = 'Arlington';
        address.Address__StateCode__s = 'AK';
        address.Address__CountryCode__s = 'US';
        address.Address__PostalCode__s = '23005';
        address.Type__c = 'Shipping';
        address.Account__c = testAccount.Id;
        insert address;
        
        Address__c address1 = new Address__c();
        address1.Address__Street__s = '4028 Jewell Road';
        address1.Address__City__s = 'Chicago';
        address1.Address__StateCode__s = 'ID';
        address1.Address__CountryCode__s = 'US';
        address1.Address__PostalCode__s = '55404';
        address1.Type__c = 'Billing';
        address1.Account__c = testAccount.Id;
        insert address1;
        
        Test.startTest();
        ReportToAddressBatch reportToAddressBatchObj = new ReportToAddressBatch();
        Database.executeBatch(reportToAddressBatchObj, 10);
        Test.stopTest();
        System.assertEquals(1, testAccts.size());
    }
    
    @isTest
    static void testNoAddress() {
        // Create accounts
        List<Account> testAccts = new List<Account>();
        Account testAccount = IntappTestObjectFactory.createaccount(false);
        testAccount.Type = 'Client';
        testAccts.add(testAccount);

        insert testAccts;

        Test.startTest();
        ReportToAddressBatch reportToAddressBatchObj = new ReportToAddressBatch();
        Database.executeBatch(reportToAddressBatchObj, 10);
        Test.stopTest();
        System.assertEquals(1, testAccts.size());
    }
}