Doc/force-app/main/default/objects/Automation_Controls__c/Automation_Controls__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Automation Controls</label>
</CustomObject>

force-app/main/default/objects/Automation_Controls__c/fields/Bypass_Flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Flows</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Controls__c/fields/Contract_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Contract_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Contractline_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Contractline_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contractline Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Controls__c/fields/Opportunity_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Controls__c/fields/OpportunityLine_Bypass__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLine_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OpportunityLine Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Quote_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Quote_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Quoteline_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Quoteline_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quoteline Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This checkbox tracks whether or not an Opportunity Product is still active for renewal Opportunities. For example, if this product is cancelled, the checkbox is unchecked, and a separate cancellation Opportunity is created.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/ACV__c.field-meta.xml
<CustomField>
    <fullName>ACV__c</fullName>
    <description>Field is used to state the annual contract value</description>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/ACV_Change__c.field-meta.xml
<CustomField>
    <fullName>ACV_Change__c</fullName>
    <description>BIZ-53197</description>
    <label>ACV Change</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Opportunity Line Item is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/DLIP_OP4I_ID__c.field-meta.xml
<CustomField>
    <fullName>DLIP_OP4I_ID__c</fullName>
    <description>Created as part of BIZ-68739</description>
    <label>DLIP OP4I ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Ghost_Mapping_Payload__c.field-meta.xml
<CustomField>
    <fullName>Ghost_Mapping_Payload__c</fullName>
    <label>Ghost Mapping Payload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/OP4I_System_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_System_Id__c</fullName>
    <description>For syncing Opportunity Products Items with OP4I Deal Line Item, BIZ-45223</description>
    <label>OP4I System Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Opportunity_Prod_Updated__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Prod_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Prod Updated</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Original_Oppty_Text_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Oppty_Text_Id__c</fullName>
    <description>Capture Original Oppty Id in Text - BIZ-71429</description>
    <label>Original Oppty Text Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this Opportunity Product.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Segment_Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-68140 - Reference to the parent Static Bundle Opportunity Line Item for segmentation tracking of Static Components.</description>
    <label>Segment Bundle Line</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product (Segment Bundle Line)</relationshipLabel>
    <relationshipName>Segment_Bundle_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>Subscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscriptions</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product_Sub</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Start_Date__c</fullName>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ACV__c.field-meta.xml
<CustomField>
    <fullName>ACV__c</fullName>
    <formula>IF(
OR(TEXT(SBQQ__ChargeType__c) = &quot;&quot;, AND(CONTAINS(Text( Product_Type__c ),&quot;Services&quot;), NOT(ISPICKVAL(Product_Type__c,&quot;Services (Recurring)&quot;)))),
0,
IF(
ISPICKVAL(SBQQ__ChargeType__c, &quot;One-Time&quot;),
SBQQ__NetPrice__c,
IF(
ISPICKVAL(SBQQ__ChargeType__c, &quot;Recurring&quot;),
Customer_Sale_Price_Per_Month__c * SBQQ__EffectiveQuantity__c * 12,
0
)
)
)</formula>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ACV_Change__c.field-meta.xml
<CustomField>
    <fullName>ACV_Change__c</fullName>
    <label>ACV Change</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Quote Line is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Ghost_Mapping_Payload__c.field-meta.xml
<CustomField>
    <fullName>Ghost_Mapping_Payload__c</fullName>
    <formula>&quot;{&quot; &amp;
&quot;\&quot;ACV__c\&quot;:&quot; &amp; TEXT(ACV__c) &amp; &quot;,&quot; &amp;
IF(
ISBLANK(ACV_Change__c), 
&quot;&quot;, 
&quot;\&quot;ACV_Change__c\&quot;:&quot; &amp; TEXT(ACV_Change__c) &amp; &quot;,&quot;
) &amp;
&quot;\&quot;OP4I_Deal_Id__c\&quot;:\&quot;&quot; &amp; OP4I_Deal_Id__c &amp; &quot;\&quot;,&quot; &amp;
IF(
ISBLANK(SBQQ__RenewedSubscription__c),
&quot;&quot;,
&quot;\&quot;Subscriptions__c\&quot;:\&quot;&quot; &amp; SBQQ__RenewedSubscription__c &amp; &quot;\&quot;,&quot;
) &amp;
&quot;\&quot;Customer_Sales_Price_Per_Month__c\&quot;:\&quot;&quot; &amp; TEXT(Customer_Sale_Price_Per_Month__c) &amp; &quot;\&quot;,&quot; &amp;
&quot;\&quot;Term_Start_Date__c\&quot;:\&quot;&quot; &amp; TEXT(SBQQ__StartDate__c) &amp; &quot;\&quot;,&quot; &amp;
&quot;\&quot;Term_End_Date__c\&quot;:\&quot;&quot; &amp; TEXT(SBQQ__EndDate__c) &amp; &quot;\&quot;&quot; &amp;
&quot;}&quot;</formula>
    <label>Ghost Mapping Payload</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Item_Key__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Key__c</fullName>
    <description>BIZ-68140 - A unique identifier for the Quote Line item.</description>
    <label>Line Item Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Segment_Bundle_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line_Id__c</fullName>
    <description>BIZ-68140 - Identifies the associated Segment Bundle Line for the Quote Line, linking it to the relevant bundle configuration.</description>
    <label>Segment Bundle Line Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/ACV__c.field-meta.xml
<CustomField>
    <fullName>ACV__c</fullName>
    <description>BIZ-79917</description>
    <formula>SBQQ__SegmentQuantity__c *  Customer_Sale_Price_Per_Month__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/ACV_Change__c.field-meta.xml
<CustomField>
    <fullName>ACV_Change__c</fullName>
    <label>ACV Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Subscription is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Last_Segment_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Last_Segment_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Segment Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions (Last Segment Subscription)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Segment_Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-68140 - Reference to the parent Static Bundle Subscription for segmentation tracking of Static Components.</description>
    <label>Segment Bundle Line</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions (Segment Bundle Line)</relationshipLabel>
    <relationshipName>Segment_Bundle_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/CPQ_Option_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Static Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Static Component</fullName>
    </customValue>
    <description>BIZ-68318</description>
    <masterLabel>CPQ Option Type</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityProductTriggerHandlerTest.cls
/**
 * @description Test class for OpportunityProductTriggerHandler and OpportunityProductTriggerHelper.
 *              Tests the functionality of OpportunityLineItem trigger operations including:
 *              - Segment bundle linking and relationship management
 *              - OP4I sync retriggering when bundle system IDs change
 *              - Ghost quote line field mapping and ACV calculations
 *              - After insert, update, and delete event handling
 *              - Publishing logic for OpportunityLineItems
 * @author Pooja Hemrajani
 */
@IsTest
public class OpportunityProductTriggerHandlerTest {

    /***********************************************************************************************************
     * 
     * TEST DATA SETUP
     * 
     ***********************************************************************************************************/
    /**
     * @description Sets up test data for all test methods including Account, Opportunity, Quote,
     *              QuoteLines, Products, PricebookEntries, and initial OpportunityLineItems.
     */
    @TestSetup
    static void setupTestData() {
        // 0) Automation Controls — bypass only non-OLI triggers & flows during data setup.
        //    Keep OpportunityLine_Bypass__c = false so OLI triggers fire and cover
        //    the full handler/helper code paths (beforeInsert, afterInsert, afterUpdate, afterDelete).
        insert new Automation_Controls__c(
            SetupOwnerId              = UserInfo.getUserId(),
            Active__c                 = true,
            Bypass_Flows__c           = true,           // Prevent flows from cascading SOQL
            Opportunity_Bypass__c     = true,           // Prevent Opp trigger chains
            OpportunityLine_Bypass__c = false,          // LET OLI triggers fire for coverage
            Bypass_Triggers__c        = false,          // Allow Apex triggers
            Quote_Bypass__c           = true,
            Quoteline_Bypass__c       = true,
            Contract_Bypass__c        = true,
            Contractline_Bypass__c    = true
        );

        // 1) Account & Opportunity
        Account acct = (Account) TestFactory.createSObject(new Account());

        Opportunity opp = (Opportunity) TestFactory.createSObject(
            new Opportunity(AccountId = acct.Id)
        );

        // 2) Quote
        SBQQ__Quote__c quote = (SBQQ__Quote__c) TestFactory.createSObject(
            new SBQQ__Quote__c(SBQQ__Opportunity2__c = opp.Id)
        );

        // 3) Product & PricebookEntry
        Product2 prod = (Product2) TestFactory.createSObject(
            new Product2(Name = 'TestProd', ProductCode = 'TPC-001')
        );

        PricebookEntry pbe = (PricebookEntry) TestFactory.createSObject(
            new PricebookEntry(Product2Id = prod.Id, UnitPrice = 100)
        );

        // 4) Two QuoteLines: one bundle parent, one component child
        SBQQ__QuoteLine__c bundleQL = (SBQQ__QuoteLine__c) TestFactory.createSObject(
            new SBQQ__QuoteLine__c(
                SBQQ__Quote__c   = quote.Id,
                SBQQ__Product__c = prod.Id,
                SBQQ__Quantity__c = 5,
                Line_Item_Key__c = 'PARENT_KEY'
            )
        );

        SBQQ__QuoteLine__c compQL = (SBQQ__QuoteLine__c) TestFactory.createSObject(
            new SBQQ__QuoteLine__c(
                SBQQ__Quote__c            = quote.Id,
                SBQQ__Product__c          = prod.Id,
                SBQQ__Quantity__c         = 2,
                Segment_Bundle_Line_Id__c = 'PARENT_KEY'
            )
        );

        // 5) An existing bundle-type OLI for reuse
        OpportunityLineItem existingOli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = opp.Id,
                PricebookEntryId   = pbe.Id,
                Quantity           = 1,
                TotalPrice         = 100,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQL.Id
            )
        );
    }

    /************************************************************************************************************
     * 
     * TEST METHODS
     * 
     ************************************************************************************************************/
    /**
     * @description Tests that the first update block in updateSegmentedBundleId correctly links
     *              a component OpportunityLineItem to its bundle parent using Original_Oppty_Text_Id__c.
     *              Verifies that Segment_Bundle_Line__c is properly set after the update.
     */
    @IsTest
    static void testFirstUpdateBlock_IsExecuted() {
        Id oppId       = getOppId();
        Id pbeId       = getPbeId();
        Id bundleOliId = getBundleOliId();
        Id compQLId    = getCompQLId();

        // Create component OLI linking back to existing bundle OLI
        OpportunityLineItem child = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 1,
                TotalPrice                = 10,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Original_Oppty_Text_Id__c = bundleOliId,
                Segment_Bundle_Line__c    = bundleOliId
            )
        );

        Test.startTest();
            OpportunityProductTriggerHelper.updateSegmentedBundleId(
                new List<OpportunityLineItem>{ child }
            );
        Test.stopTest();

        System.assertEquals(
            bundleOliId,
            getOliById(child.Id).Segment_Bundle_Line__c,
            'Child OLI should link back to the bundle OLI via the first update block.'
        );
    }

    /**
     * @description Tests that inserting a static bundle and component OpportunityLineItem together
     *              automatically sets the Segment_Bundle_Line__c field on the component to reference
     *              the bundle parent. Verifies the relationship is established during insert.
     */
    @IsTest
    static void testInsertStaticBundleAndComponentSetsSegment() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId
            )
        );
        OpportunityLineItem comp = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 2,
                TotalPrice                = 200,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Original_Oppty_Text_Id__c = bundleQLId
            )
        );

        // No nested Test.startTest() here
        insert new List<OpportunityLineItem>{ bundle, comp };

        System.assertEquals(
            bundle.Id,
            getOliById(comp.Id).Segment_Bundle_Line__c,
            'After insert, static component should link to its bundle.'
        );
    }

    /**
     * @description Tests that deleting a bundle OpportunityLineItem clears the Segment_Bundle_Line__c
     *              field on child component OpportunityLineItems. Verifies the cleanup logic works
     *              correctly when the parent bundle is removed.
     */
    @IsTest
    static void testDeleteBundleClearsChildSegment() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId
            )
        );
        OpportunityLineItem comp = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 2,
                TotalPrice                = 200,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Original_Oppty_Text_Id__c = bundle.Id
            )
        );
        insert new List<OpportunityLineItem>{ bundle, comp };

        // Verify precondition
        System.assertNotEquals(
            null,
            getOliById(comp.Id).Segment_Bundle_Line__c,
            'Component should have a segment link before delete'
        );

        Test.startTest();
            delete bundle;
        Test.stopTest();

        System.assertEquals(
            null,
            getOliById(comp.Id).Segment_Bundle_Line__c,
            'Deleting bundle should clear the child segment link.'
        );
    }

    /**
     * @description Tests that updating a component OpportunityLineItem preserves the Segment_Bundle_Line__c
     *              relationship to its bundle parent. Verifies that the link persists through updates.
     */
    @IsTest
    static void testUpdateComponentReLinksToBundle() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId
            )
        );
        OpportunityLineItem comp = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 2,
                TotalPrice                = 200,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Original_Oppty_Text_Id__c = bundle.Id
            )
        );
        insert new List<OpportunityLineItem>{ bundle, comp };

        // Update the component
        comp.Quantity += 10;

        Test.startTest();
            update comp;
        Test.stopTest();

        System.assertNotEquals(
            null,
            getOliById(comp.Id).Segment_Bundle_Line__c,
            'After update, component should still link to its bundle.'
        );
    }

    /**
     * @description Tests the after delete event handler for OpportunityLineItems. Verifies that
     *              the delete branch in opportunityProductEventafterDelete executes without exceptions
     *              for non-migration opportunities with OpportunityLineItems that have no QuoteLine.
     */
    @IsTest
    static void testAfterDelete_PublishDeleteBranch_RealData() {
        // Mark Opp as non-migration and blank Renewal
        Opportunity opp = new Opportunity(
            Id           = getOppId(),
            RecordTypeId = getNonMigrationRecordTypeId()
        );
        update opp;

        // Insert OLI with no quote line
        OpportunityLineItem oldOli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = opp.Id,
                PricebookEntryId   = getPbeId(),
                Quantity           = 1,
                TotalPrice         = 50,
                SBQQ__QuoteLine__c = null
            )
        );

        Test.startTest();
            OpportunityProductTriggerHelper.opportunityProductEventafterDelete(
                new List<OpportunityLineItem>{ getOliById(oldOli.Id) }
            );
        Test.stopTest();

        System.assertEquals(
            true,
            true,
            'Delete branch executed without exception'
        );
    }

    /**
     * @description Tests the after update event handler for OpportunityLineItems. Verifies that
     *              opportunityProductEventafterUpdate executes without exceptions when OpportunityLineItems
     *              have valid OP4I_System_Id__c and DLIP_OP4I_ID__c values.
     */
    @IsTest
    static void testOpportunityProductEventAfterUpdate() {
        OpportunityLineItem oli = getOliById(getBundleOliId());

        // Populate system fields so the 'isValidByOptionType' check passes
        oli.OP4I_System_Id__c = 'SYS-123';
        oli.DLIP_OP4I_ID__c   = 'DLIP-456';

        Map<Id, OpportunityLineItem> oldMap = new Map<Id,OpportunityLineItem>{
            oli.Id => oli.clone(false, true)
        };

        Test.startTest();
            OpportunityProductTriggerHelper.opportunityProductEventafterUpdate(
                new List<OpportunityLineItem>{ oli },
                oldMap
            );
        Test.stopTest();

        System.assertEquals(
            true,
            true,
            'AfterUpdate logic executed without exception'
        );
    }

    /**
     * @description Tests the updateOLIFromGhostQL method with subscription data to verify ACV change
     *              calculations. Creates a renewal subscription scenario and verifies that ACV__c and
     *              ACV_Change__c are correctly calculated from the Ghost_Mapping_Payload__c JSON payload.
     *              Also verifies that Quantity and other fields are properly mapped from the payload.
     */
    @IsTest
    static void testUpdateOLIFromGhostQL_WithSubscriptionACVChange() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();
        update new Opportunity(Id = oppId, Deal_Type__c = 'Renewal');

        // Create "last segment" subscription whose values will drive PrevACV
        // PrevACV formula in helper: (NetPrice * Qty * 12) / Segment_Months
        // Choose values to make math easy:
        // NetPrice = 100, Qty = 2, Segment_Months = 6
        // PrevACV = (100 * 2 * 12) / 6 = 400
        SBQQ__Subscription__c lastSegmentSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c         = 100,
                SBQQ__Quantity__c         = 2,
                SBQQ__SegmentStartDate__c = Date.today(),
                SBQQ__SegmentEndDate__c   = Date.today().addMonths(12)
            )
        );

        // Current (renewed) subscription referencing the last segment subscription
        SBQQ__Subscription__c renewedSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c            = 150,
                SBQQ__Quantity__c            = 3,
                SBQQ__SegmentStartDate__c    = Date.today(),
                SBQQ__SegmentEndDate__c      = Date.today().addMonths(12),
                Last_Segment_Subscription__c = lastSegmentSub.Id
            )
        );

        // Create an OpportunityLineItem that will be updated via Ghost payload
        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 1,
                TotalPrice       = 100,
                Subscriptions__c = renewedSub.Id
            )
        );

        // Reload (simulate trigger context usage)
        oli = getOliById(oli.Id);

        // Provide Ghost payload setting a new ACV__c value (e.g., 550)
        // Expected ACV_Change__c = 550 (current) - 400 (prevACV) = 150
        String termStartDate = Date.today().addDays(30).format();
        oli.Ghost_Mapping_Payload__c = '{"ACV__c":550,"Quantity":5, "Term_Start_Date__c": "' + termStartDate + '", "Opportunity_Prod_Updated__c":"true"}';

        Test.startTest();
            OpportunityProductTriggerHelper.updateOLIFromGhostQL(
                new List<OpportunityLineItem>{ oli }
            );
        Test.stopTest();

        // Persist before-style modifications
        update oli;

        // Assert results
        OpportunityLineItem after = getOliById(oli.Id);

        System.assertEquals(550, after.ACV__c, 'ACV__c should map from payload');
        System.assertEquals(5, Integer.valueOf(after.Quantity), 'Quantity should update from payload');
    }

    /**
     * @description Tests that checkSegmentBundleForRetrigger sets Retrigger_OP4I_Sync__c to true on
     *              component OpportunityLineItems when the bundle parent's OP4I_System_Id__c changes.
     *              Creates a bundle OLI and a component OLI that references it via Segment_Bundle_Line__c,
     *              then updates the bundle's OP4I_System_Id__c and verifies the component is retriggered.
     */
    @IsTest
    static void testCheckSegmentBundleForRetrigger() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        // Create bundle OLI (parent)
        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId,
                OP4I_System_Id__c  = 'OP4I-OLD-123'
            )
        );

        // Create component OLI (child) that references the bundle via Segment_Bundle_Line__c
        OpportunityLineItem comp = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 2,
                TotalPrice                = 200,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Segment_Bundle_Line__c    = bundle.Id,
                Retrigger_OP4I_Sync__c    = false
            )
        );

        // Create old map with original OP4I_System_Id__c
        Map<Id, OpportunityLineItem> oldMap = new Map<Id, OpportunityLineItem>{
            bundle.Id => new OpportunityLineItem(
                Id = bundle.Id,
                OP4I_System_Id__c = 'OP4I-OLD-123'
            )
        };

        // Update bundle's OP4I_System_Id__c to trigger the retrigger logic
        bundle.OP4I_System_Id__c = 'OP4I-NEW-456';

        Test.startTest();
            OpportunityProductTriggerHelper.checkSegmentBundleForRetrigger(
                new List<OpportunityLineItem>{ bundle },
                oldMap
            );
        Test.stopTest();

        // Verify that the component OLI's Retrigger_OP4I_Sync__c was set to true
        System.assertEquals(
            true,
            getOliById(comp.Id).Retrigger_OP4I_Sync__c,
            'Component OLI should have Retrigger_OP4I_Sync__c set to true when bundle OP4I_System_Id__c changes'
        );
    }

    /**
     * @description Tests that checkSegmentBundleForRetrigger correctly handles multiple component
     *              OpportunityLineItems when a bundle parent's OP4I_System_Id__c changes. Creates
     *              a bundle OLI and two component OLIs that reference it, then verifies both components
     *              have Retrigger_OP4I_Sync__c set to true after the bundle's OP4I_System_Id__c is updated.
     */
    @IsTest
    static void testCheckSegmentBundleForRetrigger_MultipleComponents() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        // Create bundle OLI (parent)
        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId,
                OP4I_System_Id__c  = 'OP4I-ORIGINAL'
            )
        );

        // Create two component OLIs that reference the bundle
        OpportunityLineItem comp1 = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 2,
                TotalPrice                = 200,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Segment_Bundle_Line__c    = bundle.Id,
                Retrigger_OP4I_Sync__c    = false
            )
        );
        OpportunityLineItem comp2 = (OpportunityLineItem) TestFactory.buildSObject(
            new OpportunityLineItem(
                OpportunityId             = oppId,
                PricebookEntryId          = pbeId,
                Quantity                  = 3,
                TotalPrice                = 300,
                CPQ_Option_Type__c        = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c        = compQLId,
                Segment_Bundle_Line__c    = bundle.Id,
                Retrigger_OP4I_Sync__c    = false
            )
        );
        insert new List<OpportunityLineItem>{ comp1, comp2 };

        // Create old map
        Map<Id, OpportunityLineItem> oldMap = new Map<Id, OpportunityLineItem>{
            bundle.Id => new OpportunityLineItem(
                Id = bundle.Id,
                OP4I_System_Id__c = 'OP4I-ORIGINAL'
            )
        };

        // Update bundle's OP4I_System_Id__c
        bundle.OP4I_System_Id__c = 'OP4I-UPDATED';

        Test.startTest();
            OpportunityProductTriggerHelper.checkSegmentBundleForRetrigger(
                new List<OpportunityLineItem>{ bundle },
                oldMap
            );
        Test.stopTest();

        // Verify both component OLIs have Retrigger_OP4I_Sync__c set to true
        for (Id compId : new List<Id>{ comp1.Id, comp2.Id }) {
            System.assertEquals(
                true,
                getOliById(compId).Retrigger_OP4I_Sync__c,
                'All component OLIs should have Retrigger_OP4I_Sync__c set to true when bundle OP4I_System_Id__c changes'
            );
        }
    }

    /**
     * @description Tests updateRenewalSegmentedBundleId — links a renewal OLI to its bundle parent
     *              using the Subscriptions__r.Segment_Bundle_Line__c relationship. Verifies that
     *              Segment_Bundle_Line__c is correctly set on the component OLI.
     */
    @IsTest
    static void testUpdateRenewalSegmentedBundleId() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();

        // Create subscriptions: bundle parent and component child linked via Segment_Bundle_Line__c
        SBQQ__Subscription__c bundleSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c = 100,
                SBQQ__Quantity__c = 1,
                SBQQ__SegmentStartDate__c = Date.today(),
                SBQQ__SegmentEndDate__c   = Date.today().addMonths(12)
            )
        );

        SBQQ__Subscription__c compSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c = 50,
                SBQQ__Quantity__c = 2,
                SBQQ__SegmentStartDate__c = Date.today(),
                SBQQ__SegmentEndDate__c   = Date.today().addMonths(12),
                Segment_Bundle_Line__c    = bundleSub.Id
            )
        );

        // Create OLIs referencing these subscriptions
        OpportunityLineItem bundleOli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 1,
                TotalPrice       = 100,
                Subscriptions__c = bundleSub.Id
            )
        );

        OpportunityLineItem compOli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 2,
                TotalPrice       = 100,
                Subscriptions__c = compSub.Id
            )
        );

        Test.startTest();
            OpportunityProductTriggerHelper.updateRenewalSegmentedBundleId(
                new List<OpportunityLineItem>{ bundleOli, compOli }
            );
        Test.stopTest();

        System.assertEquals(
            bundleOli.Id,
            getOliById(compOli.Id).Segment_Bundle_Line__c,
            'Component OLI should link to bundle OLI via subscription Segment_Bundle_Line__c'
        );
    }

    /**
     * @description Tests opportunityProductEventafterDelete cancel branch — when an OLI with a
     *              Renewal_Quote_Type and linked QuoteLine (qty=0) is deleted, it should be
     *              scheduled for cancellation via OpportunityProductDelayScheduler.
     */
    @IsTest
    static void testAfterDelete_CancelBranch() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();
        Id bundleQLId = getBundleQLId();

        // Set Opp to non-migration with a Renewal_Quote_Type (formula on OLI reads from Opp)
        update new Opportunity(
            Id                    = oppId,
            RecordTypeId          = getNonMigrationRecordTypeId(),
            Renewal_Quote_Type__c = 'Renewal-Changes'
        );

        // Zero-out the quote line quantity to trigger cancel branch
        update new SBQQ__QuoteLine__c(Id = bundleQLId, SBQQ__Quantity__c = 0);

        // Create OLI with QuoteLine — Renewal_Quote_Type__c is a formula from the Opportunity
        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 1,
                TotalPrice         = 50,
                SBQQ__QuoteLine__c = bundleQLId
            )
        );

        OpportunityLineItem loaded = getOliById(oli.Id);

        Test.startTest();
            OpportunityProductTriggerHelper.opportunityProductEventafterDelete(
                new List<OpportunityLineItem>{ loaded }
            );
        Test.stopTest();

        // The cancel branch schedules a job — no assertion exception means it executed
        System.assertEquals(true, true, 'Cancel branch executed without exception');
    }

    /**
     * @description Tests opportunityProductEventafterInsert — verifies that the after-insert
     *              handler processes OLIs for non-migration opportunities without exception.
     */
    @IsTest
    static void testOpportunityProductEventAfterInsert() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();

        // Mark Opp as non-migration
        update new Opportunity(Id = oppId, RecordTypeId = getNonMigrationRecordTypeId());

        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 1,
                TotalPrice         = 100,
                OP4I_System_Id__c  = 'OP4I-INS-001',
                DLIP_OP4I_ID__c    = 'DLIP-INS-001'
            )
        );

        Test.startTest();
            OpportunityProductTriggerHelper.opportunityProductEventafterInsert(
                new List<OpportunityLineItem>{ oli },
                false
            );
        Test.stopTest();

        System.assertEquals(true, true, 'AfterInsert logic executed without exception');
    }

    /**
     * @description Tests opportunityProductEventafterInsert with bIsBefore=true to cover
     *              the Auto-Renewal OP4I_System_Id__c assignment path (line 329-331).
     */
    @IsTest
    static void testAfterInsert_BeforeContext_AutoRenewal() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();

        // Set Opp to non-migration + Auto-Renewal
        update new Opportunity(
            Id                   = oppId,
            RecordTypeId         = getNonMigrationRecordTypeId(),
            Renewal_Quote_Type__c = 'Auto-Renewal'
        );

        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 1,
                TotalPrice         = 100,
                OP4I_System_Id__c  = 'NON-OP4I-VALUE'
            )
        );

        Test.startTest();
            OpportunityProductTriggerHelper.opportunityProductEventafterInsert(
                new List<OpportunityLineItem>{ oli },
                true
            );
        Test.stopTest();

        System.assertEquals(true, true, 'Before-context Auto-Renewal insert executed without exception');
    }

    /**
     * @description Tests updateOLIFromGhostQL for a Static Component subscription — verifies
     *              that ACV_Change__c is NOT calculated (remains null) for static components.
     */
    @IsTest
    static void testUpdateOLIFromGhostQL_StaticComponentSkipsACVChange() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();
        update new Opportunity(Id = oppId, Deal_Type__c = 'Renewal');

        // Last segment subscription with explicit ProrateMultiplier for prevACV calc
        SBQQ__Subscription__c lastSegSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c          = 100,
                SBQQ__SegmentQuantity__c   = 2,
                SBQQ__Quantity__c          = 2,
                SBQQ__ProrateMultiplier__c = 12,
                SBQQ__SegmentStartDate__c  = Date.today(),
                SBQQ__SegmentEndDate__c    = Date.today().addMonths(12)
            )
        );

        // Renewed subscription marked as Static Component
        SBQQ__Subscription__c renewedSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c            = 150,
                SBQQ__SegmentQuantity__c     = 3,
                SBQQ__Quantity__c            = 3,
                SBQQ__ProrateMultiplier__c   = 12,
                SBQQ__SegmentStartDate__c    = Date.today(),
                SBQQ__SegmentEndDate__c      = Date.today().addMonths(12),
                Last_Segment_Subscription__c = lastSegSub.Id,
                CPQ_Option_Type__c           = 'Static Component'
            )
        );

        // Verify the subscription actually persisted CPQ_Option_Type__c
        SBQQ__Subscription__c verifiedSub = [
            SELECT CPQ_Option_Type__c FROM SBQQ__Subscription__c WHERE Id = :renewedSub.Id
        ];
        System.assertEquals('Static Component', verifiedSub.CPQ_Option_Type__c,
            'Subscription should have CPQ_Option_Type__c = Static Component');

        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 1,
                TotalPrice       = 100,
                Subscriptions__c = renewedSub.Id
            )
        );

        oli = getOliById(oli.Id);
        String termStartDate = Date.today().addDays(30).format();
        oli.Ghost_Mapping_Payload__c = '{"ACV__c":550,"Quantity":5,"Term_Start_Date__c":"' + termStartDate + '","Opportunity_Prod_Updated__c":"true"}';
        oli.ACV_Change__c = 0;

        Test.startTest();
            OpportunityProductTriggerHelper.updateOLIFromGhostQL(
                new List<OpportunityLineItem>{ oli }
            );
        Test.stopTest();

        // For static components: prevACV = (100*2*12)/12 = 200, acv = 550
        // But the static component check should skip the calc entirely
        System.assertEquals(0, oli.ACV_Change__c,
            'Static component ACV_Change should remain 0 — subscription calc must be skipped');
        System.assertEquals(550, oli.ACV__c, 'ACV__c should still be mapped from payload');
    }

    /**
     * @description Tests updateOLIFromGhostQL when the renewed subscription uses a revised subscription
     *              (amendment path) — covers lines 466-469 in OpportunityProductTriggerHelper.
     */
    @IsTest
    static void testUpdateOLIFromGhostQL_RevisedSubscriptionPath() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();
        update new Opportunity(Id = oppId, Deal_Type__c = 'Renewal');

        // "Last segment" subscription
        SBQQ__Subscription__c lastSegSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c         = 100,
                SBQQ__Quantity__c         = 2,
                SBQQ__SegmentStartDate__c = Date.today(),
                SBQQ__SegmentEndDate__c   = Date.today().addMonths(12)
            )
        );

        // Revised subscription that references the last-segment as its RevisedSubscription
        // PrevACV = (200 * 3 * 12) / 12 = 600
        SBQQ__Subscription__c revisedSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c            = 200,
                SBQQ__SegmentQuantity__c     = 3,
                SBQQ__Quantity__c            = 3,
                SBQQ__ProrateMultiplier__c   = 12,
                SBQQ__SegmentStartDate__c    = Date.today(),
                SBQQ__SegmentEndDate__c      = Date.today().addMonths(12),
                SBQQ__RevisedSubscription__c = lastSegSub.Id
            )
        );

        // Renewed subscription with Last_Segment_Subscription pointing to lastSegSub
        SBQQ__Subscription__c renewedSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c            = 150,
                SBQQ__Quantity__c            = 3,
                SBQQ__SegmentStartDate__c    = Date.today(),
                SBQQ__SegmentEndDate__c      = Date.today().addMonths(12),
                Last_Segment_Subscription__c = lastSegSub.Id
            )
        );

        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 1,
                TotalPrice       = 100,
                Subscriptions__c = renewedSub.Id
            )
        );

        oli = getOliById(oli.Id);
        String termStartDate = Date.today().addDays(30).format();
        oli.Ghost_Mapping_Payload__c = '{"ACV__c":700,"Quantity":5,"Term_Start_Date__c":"' + termStartDate + '","Opportunity_Prod_Updated__c":"true"}';

        Test.startTest();
            OpportunityProductTriggerHelper.updateOLIFromGhostQL(
                new List<OpportunityLineItem>{ oli }
            );
        Test.stopTest();

        update oli;

        OpportunityLineItem after = getOliById(oli.Id);
        // PrevACV from revised sub = (200 * 3 * 12) / 12 = 600
        // ACV_Change = 700 - 600 = 100
        System.assertEquals(100.00, after.ACV_Change__c, 'ACV_Change should use revised subscription for previous ACV');
    }

    /**
     * @description Tests updateOLIFromGhostQL fallback — when a subscription has no
     *              Last_Segment_Subscription and SegmentIndex=1, uses self as lastSegSub.
     *              Covers lines 458-459 in OpportunityProductTriggerHelper.
     */
    @IsTest
    static void testUpdateOLIFromGhostQL_SegmentIndex1Fallback() {
        Id oppId = getOppId();
        Id pbeId = getPbeId();
        update new Opportunity(Id = oppId, Deal_Type__c = 'Renewal');

        // Renewed subscription with SegmentIndex=1, no Last_Segment_Subscription
        // Uses self as lastSegSub. PrevACV = (100 * 2 * 12) / 12 = 200
        SBQQ__Subscription__c renewedSub = (SBQQ__Subscription__c) TestFactory.createSObject(
            new SBQQ__Subscription__c(
                SBQQ__NetPrice__c          = 100,
                SBQQ__SegmentQuantity__c   = 2,
                SBQQ__Quantity__c          = 2,
                SBQQ__ProrateMultiplier__c = 12,
                SBQQ__SegmentStartDate__c  = Date.today(),
                SBQQ__SegmentEndDate__c    = Date.today().addMonths(12),
                SBQQ__SegmentIndex__c      = 1
            )
        );

        OpportunityLineItem oli = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId    = oppId,
                PricebookEntryId = pbeId,
                Quantity         = 1,
                TotalPrice       = 100,
                Subscriptions__c = renewedSub.Id
            )
        );

        oli = getOliById(oli.Id);
        String termStartDate = Date.today().addDays(30).format();
        oli.Ghost_Mapping_Payload__c = '{"ACV__c":350,"Quantity":3,"Term_Start_Date__c":"' + termStartDate + '","Opportunity_Prod_Updated__c":"true"}';

        Test.startTest();
            OpportunityProductTriggerHelper.updateOLIFromGhostQL(
                new List<OpportunityLineItem>{ oli }
            );
        Test.stopTest();

        update oli;

        OpportunityLineItem after = getOliById(oli.Id);
        // PrevACV = (100 * 2 * 12) / 12 = 200
        // ACV_Change = 350 - 200 = 150
        System.assertEquals(150.00, after.ACV_Change__c, 'ACV_Change should use self as lastSegSub when SegmentIndex=1');
    }

    /**
     * @description Tests checkSegmentBundleForRetrigger when OP4I_System_Id__c has NOT changed —
     *              verifies early return (line 541) and no records are updated.
     */
    @IsTest
    static void testCheckSegmentBundleForRetrigger_NoChange() {
        Id oppId      = getOppId();
        Id bundleQLId = getBundleQLId();
        Id compQLId   = getCompQLId();
        Id pbeId      = getPbeId();

        OpportunityLineItem bundle = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId      = oppId,
                PricebookEntryId   = pbeId,
                Quantity           = 5,
                TotalPrice         = 500,
                CPQ_Option_Type__c = OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE,
                SBQQ__QuoteLine__c = bundleQLId,
                OP4I_System_Id__c  = 'OP4I-SAME'
            )
        );

        OpportunityLineItem comp = (OpportunityLineItem) TestFactory.createSObject(
            new OpportunityLineItem(
                OpportunityId          = oppId,
                PricebookEntryId       = pbeId,
                Quantity               = 2,
                TotalPrice             = 200,
                CPQ_Option_Type__c     = OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT,
                SBQQ__QuoteLine__c     = compQLId,
                Segment_Bundle_Line__c = bundle.Id,
                Retrigger_OP4I_Sync__c = false
            )
        );

        // Old and new have SAME OP4I_System_Id__c — no change
        Map<Id, OpportunityLineItem> oldMap = new Map<Id, OpportunityLineItem>{
            bundle.Id => new OpportunityLineItem(Id = bundle.Id, OP4I_System_Id__c = 'OP4I-SAME')
        };

        Test.startTest();
            OpportunityProductTriggerHelper.checkSegmentBundleForRetrigger(
                new List<OpportunityLineItem>{ bundle },
                oldMap
            );
        Test.stopTest();

        System.assertEquals(
            false,
            getOliById(comp.Id).Retrigger_OP4I_Sync__c,
            'Component should NOT be retriggered when OP4I_System_Id__c has not changed'
        );
    }

    /**
     * @description Tests checkSegmentBundleForRetrigger with null inputs — verifies
     *              the method returns without error (line 530).
     */
    @IsTest
    static void testCheckSegmentBundleForRetrigger_NullInputs() {
        Test.startTest();
            OpportunityProductTriggerHelper.checkSegmentBundleForRetrigger(null, null);
        Test.stopTest();

        System.assertEquals(true, true, 'Null input guard executed without exception');
    }

    /************************************************************************************************************
     * 
     * HELPER METHODS
     * 
     ************************************************************************************************************/
    /**
     * @description Retrieves the first Opportunity ID from test data.
     * @return Id The Opportunity ID.
     */
    private static Id getOppId() {
        return [SELECT Id FROM Opportunity LIMIT 1].Id;
    }

    /**
     * @description Retrieves the bundle QuoteLine ID using the Line_Item_Key__c.
     * @return Id The bundle QuoteLine ID.
     */
    private static Id getBundleQLId() {
        return [
            SELECT Id 
            FROM SBQQ__QuoteLine__c 
            WHERE Line_Item_Key__c = 'PARENT_KEY' 
            LIMIT 1
        ].Id;
    }

    /**
     * @description Retrieves the component QuoteLine ID using the Segment_Bundle_Line_Id__c.
     * @return Id The component QuoteLine ID.
     */
    private static Id getCompQLId() {
        return [
            SELECT Id 
            FROM SBQQ__QuoteLine__c 
            WHERE Segment_Bundle_Line_Id__c = 'PARENT_KEY' 
            LIMIT 1
        ].Id;
    }

    /**
     * @description Retrieves the first PricebookEntry ID from test data.
     * @return Id The PricebookEntry ID.
     */
    private static Id getPbeId() {
        return [SELECT Id FROM PricebookEntry LIMIT 1].Id;
    }

    /**
     * @description Retrieves the bundle OpportunityLineItem ID using CPQ_Option_Type__c.
     * @return Id The bundle OpportunityLineItem ID.
     */
    private static Id getBundleOliId() {
        return [
            SELECT Id 
            FROM OpportunityLineItem 
            WHERE CPQ_Option_Type__c = :OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE 
            LIMIT 1
        ].Id;
    }

    /**
     * @description Retrieves a non-migration Opportunity RecordType ID for testing.
     * @return Id A non-migration Opportunity RecordType ID.
     */
    private static Id getNonMigrationRecordTypeId() {
        Id migRt = RecordTypeUtil.getRecordTypeId(
            Opportunity.SObjectType, 
            OpportunityConstants.RT_MIGRATION_OPP
        );
        return [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType='Opportunity' 
              AND Id != :migRt 
            LIMIT 1
        ].Id;
    }

    /**
     * @description Reloads an OpportunityLineItem by Id with all fields used across tests.
     * @param oliId The OpportunityLineItem Id to reload.
     * @return OpportunityLineItem The fully-loaded record.
     */
    private static OpportunityLineItem getOliById(Id oliId) {
        return [
            SELECT Id, Segment_Bundle_Line__c, Retrigger_OP4I_Sync__c,
                   ACV__c, ACV_Change__c, Quantity, Subscriptions__c,
                   Ghost_Mapping_Payload__c, SBQQ__QuoteLine__c, OpportunityId,
                   CPQ_Option_Type__c, OP4I_System_Id__c, DLIP_OP4I_ID__c,
                   Renewal_Quote_Type__c, CreatedDate,
                   Opportunity.RecordTypeId, Opportunity.Renewal_Quote_Type__c
            FROM OpportunityLineItem
            WHERE Id = :oliId
        ];
    }
}