force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <label>Product Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_License_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_License_Type__c</fullName>
    <description>If software, is this an Annual or Perpetual software license?</description>
    <inlineHelpText>If software, is this an Annual or Perpetual software license?</inlineHelpText>
    <label>Software License Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Early Adopter</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

Doc/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Product Customer</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>Product Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IntappTestObjectFactoryTest.cls
/**
 * @description Test class refactored for IntappTestObjectFactory.
 *              Covers object creation methods using various flags.
 * @author      Manisha
 * @date        2025-06-30
 * @jira        BIZ-70776
 */
@isTest
private class IntappTestObjectFactoryTest {
    Account account = new Account();
    
    @isTest
    static void testCreateSubscription() {
        Subscription__c subscription = IntappTestObjectFactory.createSubscription(false);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateAccount() {
        Account account = IntappTestObjectFactory.createAccount(false);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateAccount2() {
        Account account = IntappTestObjectFactory.createAccount();
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateInvoice() {
        Account account = new Account();
        Invoice__c invoice = IntappTestObjectFactory.createInvoice(false);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateContract() {
        Account account = new Account();
        Contract contract = IntappTestObjectFactory.createContract(account.Id);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateContact() {
        Contact contact = IntappTestObjectFactory.createContact(false);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateContact1() {
        Contact contact = IntappTestObjectFactory.createContact(true);
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateContact2() {
        Contact contact = IntappTestObjectFactory.createContact();
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateOpportunity() {
        Opportunity opportunity = IntappTestObjectFactory.createOpportunity();
        System.assertEquals(account.Id, account.Id);
    }
    
    @isTest
    static void testCreateUser() {
        User userRec = IntappTestObjectFactory.createUser();
        System.assertNotEquals(userRec.LastName, null);
    }
    
    @isTest
    static void testCreateSBQQQuote() {
        SBQQ__Quote__c quoteRec = IntappTestObjectFactory.createSBQQQuote();
        System.assertEquals(quoteRec.Id, null);
    }
    
    @isTest
    static void testCreateApproversMatrix() {
        Approvers_Matrix__c approversMatrix = IntappTestObjectFactory.createApproversMatrix();
        System.assertEquals(approversMatrix.Id, null);
    }
    
    @isTest
    static void testCreateItemMaster() {
        Item_Master_Product__c item = IntappTestObjectFactory.createItemMaster(false);
        System.assertEquals(item.Id, null);
    }

    @isTest
    static void testCreateProduct() {
        Product2 prod = IntappTestObjectFactory.createProduct(false);
        System.assertEquals(prod.Id, null);
    }
    
    @isTest
    static void testCreateCampaign() {
        Campaign cmp = IntappTestObjectFactory.createCampaign(false);
        System.assertEquals(cmp.Id, null);
    }
    
    @isTest
    static void testCreateOpportunityLineItem() {
        Account a = (Account) SmartFactory.createSObject('Account');
        a.Industry = 'Legal';
        insert a;
        
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = a.Id;
        insert c;
        
        Contact con = (Contact) SmartFactory.createSObject('Contact');
        con.AccountId=a.Id;
        insert con;
        
        Opportunity opp = (Opportunity) SmartFactory.createSObject('Opportunity');
        opp.AccountId = a.Id;
        opp.Associated_Contract_OSA__c = c.Id;
        opp.Contract_Signer__c = con.Id;
        insert opp;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Item_Master_Product__c imp = (Item_Master_Product__c) SmartFactory.createSObject('Item_Master_Product__c');
        imp.Name = 'Name Test';
        insert imp;
        Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            isActive = true,
            Product_License_Type__c = 'Annual',
            Item_Master_Product__c = imp.Id
        );
        insert prod;
        
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        OpportunityLineItem oli = IntappTestObjectFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 2,true);
        System.assertNotEquals(oli.Id, null);
    }
}