Doc/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for POC, will hold Account information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Captures full Address of the Account</description>
    <label>Address</label>
    <type>Address</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/Automation_Controls__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Automation Controls</label>
</CustomObject>

force-app/main/default/objects/Automation_Controls__c/fields/Bypass_Flows__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flows__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Controls__c/fields/Order_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Order_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
  ISPICKVAL(StatusCode,&quot;Activated&quot;),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures Bill To address</description>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Billing_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contracts (Bill To Address)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Account with whom we have the billing relationship.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/OP4I_Auto_Number_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Auto_Number_Deal_ID__c</fullName>
    <description>BIZ-62901 same as Order OP4I Deal ID (OP4I_Auto_Number_Deal_ID__c)</description>
    <formula>SBQQ__Quote__r.OP4I_Auto_Number_Deal_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Deal ID</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Auto_Number_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Auto_Number_Deal_ID__c</fullName>
    <description>OP4I Deal auto-number of the Opportunity.</description>
    <label>OP4I Deal Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__AmendedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__AmendedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the relationship to your Amended Contract.</description>
    <inlineHelpText>Lookup to your Amended Contract.</inlineHelpText>
    <label>Amended Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Amendment Opportunities</relationshipLabel>
    <relationshipName>AmendmentOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
    <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Captures Bill To address</description>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Billing_Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with whom we have the billing relationship.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Billing Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <description>Related Contract&apos;s Number</description>
    <label>ContractNumber</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-47145</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Is_RMA_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_RMA_Order__c</fullName>
    <label>Is RMA Order</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/Master_Contract__c.field-meta.xml
<CustomField>
    <fullName>Master_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-70022 - This field will have the original contract value</description>
    <label>Master Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Amendment Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/OP4I_Auto_Number_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Auto_Number_Deal_ID__c</fullName>
    <description>BIZ-63414</description>
    <formula>SBQQ__Quote__r.OP4I_Auto_Number_Deal_ID__c</formula>
    <label>OP4I Deal Id</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Order/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the order is contracted.</description>
    <inlineHelpText>Indicates if the order is contracted.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contract of the subscription that is created from this order product.</description>
    <inlineHelpText>The contract of the subscription that is created from this order product.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the order product is contracted.</description>
    <inlineHelpText>Indicates if the order product is contracted.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__ProductSubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductSubscriptionType__c</fullName>
    <description>Set the order item&apos;s product subscription type.</description>
    <inlineHelpText>Set the order item&apos;s product subscription type.</inlineHelpText>
    <label>Product Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__SubscriptionType</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__Subscription__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscription created from this order product</description>
    <inlineHelpText>Subscription created from this order product</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>SubscriptionOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Indicates the subscription type to determine contract&apos;s pricing.</description>
    <inlineHelpText>Indicates the subscription type to determine contract&apos;s pricing.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__ProductSubscriptionType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SBQQ__SubscriptionType</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OrderItem/fields/SBQQ__TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TerminatedDate__c</fullName>
    <description>Date that this order product&apos;s related subscription was terminated</description>
    <inlineHelpText>Date that this order product&apos;s related subscription was terminated</inlineHelpText>
    <label>Terminated Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
    <inlineHelpText>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewable</fullName>
                <default>true</default>
                <label>Renewable</label>
            </value>
            <value>
                <fullName>One-time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/classes/OrderTriggerHandlerTest.cls
/**
 * @description Test class for OrderTriggerHelper
**/
@isTest
public class OrderTriggerHandlerTest {

    /***********************************************************************************************
    *
    * Test Setup
    *
    ***********************************************************************************************/
    @testSetup 
    /**
     * @description Test Setup
     */
    static void setup() {
        Product2  testProduct = (Product2)TestFactory.buildSObject(
                new Product2(
                    Name = 'Test Product', 
                    IsActive = true
                ), 'ProductDefaults'
            );

        insert new List<Product2>{ testProduct };

        PricebookEntry   testPbe = (PricebookEntry  )TestFactory.buildSObject(
                new PricebookEntry (
                    Product2Id = testProduct.Id,
                    UnitPrice = 100
                ), 'PricebookEntryDefaults'
            );

        insert new List<PricebookEntry >{ testPbe };

        // Create Account
        Account activeAccount = (Account)TestFactory.buildSObject(
                new Account(
                    Name = 'Test Account', 
                    Type = AccountConstants.TYPE_CLIENT
                ), 'AccountDefaults'
            );

            insert new List<Account>{ activeAccount};

        Address__c billToAddress = new Address__c(Account__c = activeAccount.Id);
        insert billToAddress;

        // Create Contract to be superseded

        Contract oldContract = (Contract)TestFactory.buildSObject(
            new Contract(
                Name = 'ActiveContract',
                AccountId = activeAccount.Id,
                StartDate = Date.today().addMonths(-12),
                EndDate = Date.today().addMonths(12),
                Billing_Account__c = activeAccount.Id,
                Bill_To_Address__c = billToAddress.Id
            ), 'ContractDefaults'
        );

        insert new List<Contract>{ oldContract};
            
        // Create Opportunity with specific deal type and linked to the contract
        Opportunity opp = (Opportunity)TestFactory.buildSObject(
                new Opportunity(
                    Name = 'Test Opportunity',
                    StageName = OpportunityConstants.STAGE_PROSPECTING,
                    CloseDate = Date.today(),
                    Deal_Type__c = OpportunityConstants.DEAL_TYPE_AMENDMENT_TO_SUPERCEDE,
                    AccountId = activeAccount.Id,
                    Associated_Contract_OSA__c = oldContract.Id,
                    SBQQ__AmendedContract__c = oldContract.Id,
                    OP4I_Auto_Number_Deal_ID__c = 'Test Opp'
                ), 'OpportunityDefaults'
            );

        // create nymy opp
        Opportunity nymyOpp = (Opportunity)TestFactory.buildSObject(
                new Opportunity(
                    Name = 'NYMY Opportunity',
                    StageName = OpportunityConstants.STAGE_PROSPECTING,
                    CloseDate = Date.today(),
                    Deal_Type__c = OpportunityConstants.DEAL_TYPE_NYMY,
                    AccountId = activeAccount.Id,
                    Associated_Contract_OSA__c = oldContract.Id,
                    OP4I_Auto_Number_Deal_ID__c = 'NYMY Opp'
                ), 'OpportunityDefaults'
            );
        // Mock related opportunity for the contract (to be closed)
        Opportunity renewalOpp = (Opportunity)TestFactory.buildSObject(
            new Opportunity(
                Name = 'Renewal Opp',
                StageName = OpportunityConstants.STAGE_PROSPECTING,
                CloseDate = Date.today(),
                Deal_Type__c = OpportunityConstants.DEAL_TYPE_AMENDMENT_TO_SUPERCEDE,
                AccountId = activeAccount.Id,
                SBQQ__AmendedContract__c = oldContract.Id,
                OP4I_Auto_Number_Deal_ID__c = 'Renewal Opp'

            ), 'OpportunityDefaults'
        );

        // Created amended opp for the contract
        Opportunity amendedOpp = (Opportunity)TestFactory.buildSObject(
            new Opportunity(
                Name = 'Amendment Opp',
                StageName = OpportunityConstants.STAGE_PROSPECTING,
                CloseDate = Date.today(),
                Deal_Type__c = OpportunityConstants.DEAL_TYPE_CANCELLATION,
                AccountId = activeAccount.Id,
                SBQQ__AmendedContract__c = oldContract.Id,
                OP4I_Auto_Number_Deal_ID__c = 'Amendment Opp'
            ), 'OpportunityDefaults'
        );
        insert new List<Opportunity>{ opp, nymyOpp, renewalOpp, amendedOpp};

        // Create Order (old and new version)
        Order oldOrder = (Order)TestFactory.buildSObject(
                new Order(
                    Name = 'Old Order',
                    AccountId = activeAccount.Id,
                    OpportunityId = opp.Id,
                    Status =  OrderConstants.STATUS_DRAFT,
                    Is_RMA_Order__c = 'Yes',
                    Pricebook2Id = Test.getStandardPricebookId(),
                    Billing_Account__c = activeAccount.Id,
                    Bill_To_Address__c = billToAddress.Id
                ), 'OrderDefaults'
            );

            Order newOrder = (Order)TestFactory.buildSObject(
                new Order(
                    Name = 'New Order',
                    AccountId = activeAccount.Id,
                    OpportunityId = renewalOpp.Id,
                    Status =  OrderConstants.STATUS_DRAFT,
                    Is_RMA_Order__c = 'Yes',
                    Pricebook2Id = Test.getStandardPricebookId(),
                    Billing_Account__c = activeAccount.Id,
                    Bill_To_Address__c = billToAddress.Id
                ), 'OrderDefaults'
            );

             Order rmaOrder = (Order)TestFactory.buildSObject(
                new Order(
                    Name = 'RMA Order',
                    AccountId = activeAccount.Id,
                    OpportunityId = amendedOpp.Id,
                    Status =  OrderConstants.STATUS_DRAFT,
                    Is_RMA_Order__c = 'Yes',
                    Pricebook2Id = Test.getStandardPricebookId(),
                    Billing_Account__c = activeAccount.Id,
                    Bill_To_Address__c = billToAddress.Id
                ), 'OrderDefaults'
            );

            insert new List<Order>{ oldOrder, newOrder, rmaOrder};

            OrderItem testOrderItem1 = (OrderItem)TestFactory.buildSObject(
                new OrderItem(
                    OrderId = oldOrder.Id,
                    Quantity = 10,
                    UnitPrice = 100,
                    PricebookEntryId = testPbe.Id
                ), 'OrderItemDefaults'
            );
            OrderItem testOrderItem2 = (OrderItem)TestFactory.buildSObject(
                new OrderItem(
                    OrderId = newOrder.Id,
                    Quantity = -10,
                    UnitPrice = 100,
                    PricebookEntryId = testPbe.Id
                ), 'OrderItemDefaults'
            );
            OrderItem testOrderItem3 = (OrderItem)TestFactory.buildSObject(
                new OrderItem(
                    OrderId = rmaOrder.Id,
                    Quantity = -10,
                    UnitPrice = 100,
                    PricebookEntryId = testPbe.Id
                ), 'OrderItemDefaults'
            );
            insert new List<OrderItem>{ testOrderItem1, testOrderItem2, testOrderItem3 };
    }

    /***********************************************************************************************
    *
    * Test methods
    *
    ***********************************************************************************************/
    /**
     * @description Full cancellation via Queueable: all recurring subs terminated -> contract = Cancelled/Lapsed, opps closed, account lapsed
     */
    @isTest
    static void setContractAsCancelledTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            ),
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('RMA Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_CANCELLED_LAPSED, updatedContract.Status, 'Contract should be marked as Cancelled');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName, 'Opportunity should be moved to ' + OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED);

        Account account = getAccount();
        System.assertEquals(AccountConstants.TYPE_CLIENT_LAPSED, account.Type, 'Account must be ' + AccountConstants.TYPE_CLIENT_LAPSED);
    }

    /**
     * @description Full supersession via Queueable: all recurring subs terminated -> contract = Superseded, opps closed
     */
    @isTest
    static void setContractAsSupercededTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            ),
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('New Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};
        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            newOrder.ContractNumber__c = '12345';
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT, updatedContract.Status, 'Contract should be marked as Superseded');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName, 'Opportunity should be moved to ' + OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED);
    }

    /**
     * @description Partial cancellation guard: when one subscription is still active (no TerminatedDate),
     *              the Queueable skips the contract. Contract stays In Force, NYMY stays open, account not lapsed.
     */
    @isTest
    static void setContractAsCancelled_PartialTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            ),
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable'
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('RMA Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertNotEquals(ContractConstants.STATUS_CANCELLED_LAPSED, updatedContract.Status,
            'Contract should NOT be cancelled when active recurring subscriptions remain');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertNotEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName,
            'NYMY Opp should remain open when partial cancellation is detected');

        Account account = getAccount();
        System.assertEquals(AccountConstants.TYPE_CLIENT, account.Type,
            'Account should remain Client when contract is not cancelled');
    }

    /**
     * @description Partial supersession guard: when one subscription is still active (no TerminatedDate),
     *              the Queueable skips the contract. Contract stays In Force, NYMY stays open.
     */
    @isTest
    static void setContractAsSuperceded_PartialTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            ),
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable'
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('New Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};
        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            newOrder.ContractNumber__c = '12345';
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertNotEquals(ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT, updatedContract.Status,
            'Contract should NOT be superseded when active recurring subscriptions remain');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertNotEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName,
            'NYMY Opp should remain open when partial supersession is detected');
    }

    /**
     * @description Full cancellation on a contract that already has a closed renewal opp.
     *              Only the open NYMY opp should be closed; the already-closed renewal stays as-is.
     */
    @isTest
    static void setContractAsCancelled_WithPriorRenewalTest() {
        Contract oldContract = getContract();
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Opportunity closedRenewalOpp = (Opportunity) TestFactory.buildSObject(
            new Opportunity(
                Name = 'Prior Renewal Opp',
                StageName = OpportunityConstants.STAGE_PROSPECTING,
                CloseDate = Date.today().addMonths(-3),
                Type = OpportunityConstants.TYPE_RENEWAL,
                AccountId = testAccount.Id,
                SBQQ__RenewedContract__c = oldContract.Id,
                OP4I_Auto_Number_Deal_ID__c = 'Prior Renewal'
            ), 'OpportunityDefaults'
        );
        insert closedRenewalOpp;

        closedRenewalOpp.StageName = OpportunityConstants.STAGE_CLOSED_WON;
        update closedRenewalOpp;

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('RMA Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_CANCELLED_LAPSED, updatedContract.Status, 'Contract should be marked as Cancelled');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName, 'Open NYMY Opp should be closed');

        Opportunity closedRenewal = getOpportunity('Prior Renewal Opp');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_WON, closedRenewal.StageName, 'Already-closed renewal should remain Closed Won');

        Account account = getAccount();
        System.assertEquals(AccountConstants.TYPE_CLIENT_LAPSED, account.Type, 'Account must be ' + AccountConstants.TYPE_CLIENT_LAPSED);
    }

    /**
     * @description Full supersession on a contract that already has a closed renewal opp.
     *              Only the open NYMY opp should be closed; the already-closed renewal stays as-is.
     */
    @isTest
    static void setContractAsSuperceded_WithPriorRenewalTest() {
        Contract oldContract = getContract();
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Opportunity closedRenewalOpp = (Opportunity) TestFactory.buildSObject(
            new Opportunity(
                Name = 'Prior Renewal Opp',
                StageName = OpportunityConstants.STAGE_PROSPECTING,
                CloseDate = Date.today().addMonths(-3),
                Type = OpportunityConstants.TYPE_RENEWAL,
                AccountId = testAccount.Id,
                SBQQ__RenewedContract__c = oldContract.Id,
                OP4I_Auto_Number_Deal_ID__c = 'Prior Renewal'
            ), 'OpportunityDefaults'
        );
        insert closedRenewalOpp;

        closedRenewalOpp.StageName = OpportunityConstants.STAGE_CLOSED_WON;
        update closedRenewalOpp;

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('New Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};
        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            newOrder.ContractNumber__c = '12345';
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT, updatedContract.Status, 'Contract should be marked as Superseded');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName, 'Open NYMY Opp should be closed');

        Opportunity closedRenewal = getOpportunity('Prior Renewal Opp');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_WON, closedRenewal.StageName, 'Already-closed renewal should remain Closed Won');
    }

    /**
     * @description Cancellation of a contract already in Partially Cancelled status should
     *              NOT incorrectly lapse the account when other active contracts exist.
     *              Validates the fix for the Codex review finding on PR #5660.
     */
    @isTest
    static void setContractAsCancelled_FromPartialStatusTest() {
        Contract oldContract = getContract();
        Account testAccount = getAccount();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        oldContract.Status = ContractConstants.STATUS_PARTIALLY_SUPERSEDED;
        update oldContract;

        Contract secondContract = (Contract)TestFactory.buildSObject(
            new Contract(
                Name = 'Second Active Contract',
                AccountId = testAccount.Id,
                StartDate = Date.today().addMonths(-6),
                EndDate = Date.today().addMonths(18)
            ), 'ContractDefaults'
        );
        insert secondContract;

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('RMA Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        Test.startTest();
            newOrder.SBQQ__Contracted__c = true;
            update newOrder;
        Test.stopTest();

        Contract updatedContract = [SELECT Id, Status FROM Contract WHERE Id = :oldContract.Id];
        System.assertEquals(ContractConstants.STATUS_CANCELLED_LAPSED, updatedContract.Status,
            'Contract should still be cancelled even from Partially Cancelled status');

        Opportunity nymyOpp = getOpportunity('NYMY Opportunity');
        System.assertEquals(OpportunityConstants.STAGE_CLOSED_SHOULD_NEVER_HAVE_OPENED, nymyOpp.StageName,
            'NYMY Opp should be closed');

        Account account = getAccount();
        System.assertEquals(AccountConstants.TYPE_CLIENT, account.Type,
            'Account should NOT be lapsed because another active contract exists');
    }

    /**
     * @description Status guard: when contract is already Cancelled / Lapsed, re-touching the
     *              RMA order should not enqueue a redundant Queueable or cause errors.
     *              Validates the filterContractsNotInStatus guard (BIZ-69730).
     */
    @isTest
    static void setContractAsCancelled_AlreadyCancelledNoOpTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order rmaOrder = getOrder('RMA Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        rmaOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, rmaOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        rmaOrder.SBQQ__Contracted__c = true;
        update rmaOrder;

        oldContract.Status = ContractConstants.STATUS_CANCELLED_LAPSED;
        update oldContract;

        Test.startTest();
            rmaOrder.ContractNumber__c = 'RETRIGGER';
            update rmaOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_CANCELLED_LAPSED, updatedContract.Status,
            'Contract should remain Cancelled / Lapsed when order is re-touched');
    }

    /**
     * @description Status guard: when contract is already Superseded by Newer Contract,
     *              re-touching the RMA order should not enqueue a redundant Queueable or cause errors.
     *              Validates the filterContractsNotInStatus guard (BIZ-69730).
     */
    @isTest
    static void setContractAsSuperceded_AlreadySupercededNoOpTest() {
        Contract oldContract = getContract();
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];

        insert new List<SBQQ__Subscription__c>{
            (SBQQ__Subscription__c) TestFactory.buildSObject(
                new SBQQ__Subscription__c(
                    SBQQ__Contract__c = oldContract.Id,
                    SBQQ__Product__c = testProduct.Id,
                    SBQQ__ProductSubscriptionType__c = 'Renewable',
                    SBQQ__SubscriptionType__c = 'Renewable',
                    SBQQ__TerminatedDate__c = Date.today()
                ), 'SBQQSubScriptionDefaults'
            )
        };

        Order oldOrder = getOrder('Old Order');
        Order newOrder = getOrder('New Order');

        oldOrder.Status = OrderConstants.STATUS_ACTIVATED;
        newOrder.Status = OrderConstants.STATUS_ACTIVATED;
        update new List<Order> {oldOrder, newOrder};

        oldOrder.SBQQ__Contracted__c = true;
        update oldOrder;

        newOrder.SBQQ__Contracted__c = true;
        update newOrder;

        oldContract.Status = ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT;
        update oldContract;

        Test.startTest();
            newOrder.ContractNumber__c = 'RETRIGGER';
            update newOrder;
        Test.stopTest();

        Contract updatedContract = getContract();
        System.assertEquals(ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT, updatedContract.Status,
            'Contract should remain Superseded when order is re-touched');
    }

    /**
     * @description Test that populateMasterContract sets Master_Contract__c from the
     *              Opportunity's SBQQ__AmendedContract__c when an Order is inserted.
     */
    @isTest
    static void populateMasterContractTest() {
        Account acc = getAccount();
        Address__c addr = getAddress();
        Contract existingContract = getContract();
        Opportunity amendmentOpp = getOpportunityByDealId('Renewal Opp');

        Order testOrder = (Order)TestFactory.buildSObject(
            new Order(
                Name = 'Master Contract Order',
                AccountId = acc.Id,
                OpportunityId = amendmentOpp.Id,
                Status = OrderConstants.STATUS_DRAFT,
                Is_RMA_Order__c = 'Yes',
                Pricebook2Id = Test.getStandardPricebookId(),
                Billing_Account__c = acc.Id,
                Bill_To_Address__c = addr.Id
            ), 'OrderDefaults'
        );

        Test.startTest();
            insert testOrder;
        Test.stopTest();

        Order insertedOrder = getOrder('Master Contract Order');
        System.assertEquals(existingContract.Id, insertedOrder.Master_Contract__c,
            'Master_Contract__c should be populated from Opportunity.SBQQ__AmendedContract__c');
    }

    /**
     * @description Test that populateMasterContract does NOT set Master_Contract__c
     *              when the Opportunity has no SBQQ__AmendedContract__c.
     *              Bypasses Order_Before_Insert_Update flow which requires Bill_To_Address__c
     *              to be populated from the Quote or amended Contract.
     */
    @isTest
    static void populateMasterContractNoAmendedContractTest() {
        Account acc = getAccount();
        Address__c addr = getAddress();

        Automation_Controls__c controls = Automation_Controls__c.getInstance();
        controls.Active__c = true;
        controls.Bypass_Flows__c = true;
        controls.Order_Bypass__c = true;
        upsert controls;

        Opportunity noAmendOpp = (Opportunity) TestFactory.buildSObject(
            new Opportunity(
                Name = 'No Amend Opp',
                StageName = OpportunityConstants.STAGE_PROSPECTING,
                CloseDate = Date.today(),
                Deal_Type__c = OpportunityConstants.DEAL_TYPE_AMENDMENT_TO_SUPERCEDE,
                AccountId = acc.Id,
                OP4I_Auto_Number_Deal_ID__c = 'No Amend Opp'
            ), 'OpportunityDefaults'
        );
        insert noAmendOpp;

        Order testOrder = (Order)TestFactory.buildSObject(
            new Order(
                Name = 'No Master Contract Order',
                AccountId = acc.Id,
                OpportunityId = noAmendOpp.Id,
                Status = OrderConstants.STATUS_DRAFT,
                Pricebook2Id = Test.getStandardPricebookId(),
                Billing_Account__c = acc.Id,
                Bill_To_Address__c = addr.Id
            ), 'OrderDefaults'
        );

        Test.startTest();
            insert testOrder;
        Test.stopTest();

        Order insertedOrder = getOrder('No Master Contract Order');
        System.assertEquals(null, insertedOrder.Master_Contract__c,
            'Master_Contract__c should be null when Opportunity has no amended contract');
    }

    /***********************************************************************************************
    *
    * Data Getters
    *
    ***********************************************************************************************/
    /**
     * @description get order by name
     * @param name
     * @return Order
     */
    private static Order getOrder(String name) {
        return [SELECT Id, Name, Master_Contract__c FROM Order WHERE Name =:name];
    }

    /**
     * @description get contract
     * @return Contract
     */
    private static Contract getContract() {
        return [SELECT Id, Name, Status, Consolidated_Quote__c FROM Contract LIMIT 1];
    }

    /**
     * @description get opportunity
     * @param name
     * @return Opportunity
     */
    private static Opportunity getOpportunity(String name) {
        String compareString = '%' + name + '%';
        return [SELECT Id, StageName FROM Opportunity WHERE Name LIKE :compareString LIMIT 1];
    }

    /**
     * @description get opportunity by OP4I_Auto_Number_Deal_ID__c
     * @param dealId
     * @return Opportunity
     */
    private static Opportunity getOpportunityByDealId(String dealId) {
        return [SELECT Id, StageName FROM Opportunity WHERE OP4I_Auto_Number_Deal_ID__c = :dealId LIMIT 1];
    }

    /**
     * @description get account
     * @return Account
     */
    private static Account getAccount() {
        return [SELECT Id, Type FROM Account LIMIT 1];
    }

    /**
     * @description get address
     * @return Address__c
     */
    private static Address__c getAddress() {
        return [SELECT Id FROM Address__c LIMIT 1];
    }
}