Doc/force-app/main/default/objects/Account/fields/AVA_MAPPER__Business_Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>AVA_MAPPER__Business_Identification_Number__c</fullName>
    <inlineHelpText>Please enter your Business Identification / VAT Number. This will be used for reverse charge VAT calculations.</inlineHelpText>
    <label>Business Identification Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Invoicing_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email__c</fullName>
    <label>Invoicing Email</label>
    <type>Email</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Subsidiaries__c.field-meta.xml
<CustomField>
    <fullName>Subsidiaries__c</fullName>
    <description>Available subsidiaries in NetSuite (C - Customer, P - Prospect)</description>
    <inlineHelpText>Available subsidiaries in NetSuite (C - Customer, P - Prospect)</inlineHelpText>
    <label>NS Subsidiaries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--DO NOT SELECT--</fullName>
            </value>
            <value>
                <fullName>01C</fullName>
            </value>
            <value>
                <fullName>05C</fullName>
            </value>
            <value>
                <fullName>08C</fullName>
            </value>
            <value>
                <fullName>18C</fullName>
            </value>
            <value>
                <fullName>23C</fullName>
            </value>
            <value>
                <fullName>28C</fullName>
            </value>
            <value>
                <fullName>35C</fullName>
            </value>
            <value>
                <fullName>37C</fullName>
            </value>
            <value>
                <fullName>40C</fullName>
            </value>
            <value>
                <fullName>42C</fullName>
            </value>
            <value>
                <fullName>44C</fullName>
            </value>
            <value>
                <fullName>46C</fullName>
            </value>
            <value>
                <fullName>50C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:The Frayman Group, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:Intapp Singapore Pte. Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>42:Intapp Employee Compliance, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>44:Intapp Germany GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>08:Intapp Pty, Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>40:Intapp Ireland Limited</fullName>
    </customValue>
    <customValue>
        <fullName>46:Intapp Netherlands B.V.</fullName>
    </customValue>
    <customValue>
        <fullName>50:TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Delphai Subsidiary (placeholder)</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet Subsidiary</fullName>
        <isActive>false</isActive>
        <label>TermSheet Subsidiary</label>
    </customValue>
    <customValue>
        <fullName>46:Transform Data International</fullName>
        <isActive>false</isActive>
        <label>46:Transform Data International</label>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>42:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
        <isActive>false</isActive>
        <label>05:400 TFG - US</label>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
        <isActive>false</isActive>
        <label>28:OnePlace Pte Ltd</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntegrationHandler.cls
public class IntegrationHandler {
    public static void accountEventAfterUpdate(List<Account> newList, Map<Id,Account> oldMap){
        List<Account> listToPublish = new List<Account>(); 
        if(!newList.isEmpty()){
            for(Account acc : newList){
                Boolean isValid = acc.Name!= oldMap.get(acc.Id).name 
                    || acc.VAT_Number__c!=oldMap.get(acc.Id).VAT_Number__c 
                    || acc.Invoicing_Email__c!=oldMap.get(acc.Id).Invoicing_Email__c 
                    || acc.BillingCountry!=oldMap.get(acc.Id).BillingCountry 
                    || acc.billingStreet!=oldMap.get(acc.Id).billingStreet 
                    || acc.billingState!=oldMap.get(acc.Id).billingState
                    || acc.billingPostalCode!=oldMap.get(acc.Id).billingPostalCode 
                    || acc.shippingCountry!=oldMap.get(acc.Id).shippingCountry 
                    || acc.shippingStreet!=oldMap.get(acc.Id).shippingStreet 
                    || acc.shippingCity!=oldMap.get(acc.Id).shippingCity 
                    || acc.shippingState!=oldMap.get(acc.Id).shippingState 
                    || acc.shippingPostalCode!=oldMap.get(acc.Id).shippingPostalCode 
                    || acc.AVA_MAPPER__Business_Identification_Number__c!=oldMap.get(acc.Id).AVA_MAPPER__Business_Identification_Number__c;
                if(acc.Subsidiaries__c != null && acc.Subsidiary__c != null && isValid
                ){
                    listToPublish.add(acc);
                }
            }
            if(!listtoPublish.isEmpty()){
                IntegrationUtility.publishsObjectRecords(listToPublish,'Account');
            }
        }
    }
}