Doc/force-app/main/default/objects/Account/fields/Bill_To_Entity__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account wide Bill To – OSA will be papered to/billed to this entity for all OSAs going forward. If blank then OSA/bill to will default to Account name/address.</inlineHelpText>
    <label>Bill To Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Services Companies bill to account)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Master_Terms_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Terms_Contract_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What is the OSA number?</inlineHelpText>
    <label>Intapp Master Terms: Contract Number</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Account with whom we have the billing relationship.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Contract_Master_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Master_Terms__c</fullName>
    <description>Built according to BIZ-47359</description>
    <label>Contract Master Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Master_Terms</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/OP4I_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Contract_Id__c</fullName>
    <label>OP4I Contract Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated License Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Related Opportunity)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>BIZ-64132. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Contract_Master_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Master_Terms__c</fullName>
    <label>Contract Master Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL Terms</fullName>
            </value>
            <value>
                <fullName>Existing Terms Cloud</fullName>
                <label>Existing Intapp MSSA Plus Cloud</label>
            </value>
            <value>
                <fullName>Existing Terms</fullName>
                <label>Existing Intapp MSSA Terms</label>
            </value>
            <value>
                <fullName>Existing Terms with Annex</fullName>
                <label>Existing Intapp MSSA plus Annex</label>
            </value>
            <value>
                <fullName>MSSA Attached</fullName>
                <label>New Intapp MSSA Attached</label>
            </value>
            <value>
                <fullName>Training</fullName>
                <label>Intapp Partner and Training</label>
            </value>
            <value>
                <fullName>OnePlace Legacy</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Custom Master Term from Account</fullName>
            </value>
            <value>
                <fullName>Repstor Legacy Agreement Attached</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <label>Intapp Reseller</label>
            </value>
            <value>
                <fullName>Repstor G-Cloud</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA signed by Customer Affiliate</fullName>
            </value>
            <value>
                <fullName>Legacy DealCloud Agreement</fullName>
            </value>
            <value>
                <fullName>New MSSA Signed Separate</fullName>
            </value>
            <value>
                <fullName>Prime</fullName>
                <label>Partner and Prime</label>
            </value>
            <value>
                <fullName>Repstor Legacy Term</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA plus Cloud and Annex</fullName>
            </value>
            <value>
                <fullName>Repstor Retro-Booking</fullName>
            </value>
            <value>
                <fullName>Repstor Legacy</fullName>
            </value>
            <value>
                <fullName>Legacy DealCloud Agreement Plus IPA</fullName>
            </value>
            <value>
                <fullName>TermSheet</fullName>
            </value>
            <value>
                <fullName>Existing Terms Plus Prime</fullName>
                <isActive>false</isActive>
                <label>Existing Terms Plus Prime</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/OP4I_Entitlement_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Entitlement_Id__c</fullName>
    <label>OP4I Entitlement Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <label>Related Opportunity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Master_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>URL Terms</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Terms Cloud</fullName>
        <label>Existing Intapp MSSA Plus Cloud</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms</fullName>
        <label>Existing Intapp MSSA Terms</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms with Annex</fullName>
        <label>Existing Intapp MSSA plus Annex</label>
    </customValue>
    <customValue>
        <fullName>MSSA Attached</fullName>
        <label>New Intapp MSSA Attached</label>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>OnePlace Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Trial</fullName>
    </customValue>
    <customValue>
        <fullName>Custom Master Term from Account</fullName>
    </customValue>
    <customValue>
        <fullName>Repstor Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <label>Intapp Reseller</label>
    </customValue>
    <customValue>
        <fullName>Repstor G-Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Intapp MSSA signed by Customer Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy DealCloud Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>New MSSA Signed Separate</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Intapp MSSA plus Cloud and Annex</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy TermSheet Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Repstor Retro-Booking</fullName>
        <isActive>false</isActive>
        <label>Repstor Retro-Booking</label>
    </customValue>
    <customValue>
        <fullName>Prime</fullName>
        <isActive>false</isActive>
        <label>Partner and Prime</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms Plus Prime</fullName>
        <isActive>false</isActive>
        <label>Existing Terms Plus Prime</label>
    </customValue>
    <description>Built according to BIZ-47359</description>
    <masterLabel>Contract Master Terms</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:The Frayman Group, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:Intapp Singapore Pte. Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>42:Intapp Employee Compliance, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>44:Intapp Germany GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>08:Intapp Pty, Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>40:Intapp Ireland Limited</fullName>
    </customValue>
    <customValue>
        <fullName>46:Intapp Netherlands B.V.</fullName>
    </customValue>
    <customValue>
        <fullName>50:TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Delphai Subsidiary (placeholder)</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet Subsidiary</fullName>
        <isActive>false</isActive>
        <label>TermSheet Subsidiary</label>
    </customValue>
    <customValue>
        <fullName>46:Transform Data International</fullName>
        <isActive>false</isActive>
        <label>46:Transform Data International</label>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>42:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
        <isActive>false</isActive>
        <label>05:400 TFG - US</label>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
        <isActive>false</isActive>
        <label>28:OnePlace Pte Ltd</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractTriggerHelper.cls
/********************************************************************************     
*  Name             :  ContractTriggerHelper
*  Author           :  Hiforte Technologies
*  Description      :  Helper class for Contract trigger operations: populates Billing Account, 
						identifies and publishes eligible sObjects (Account, Opportunity, Contract, Subscription),
*              			and builds dynamic SOQL queries used by the trigger framework.          
*  Change history   :  
*  Date             Author                          Description
*  06/01/14         Vasu Pulipati, Ratan Paul        Created
*  21/03/25         Ratan Paul                      Updated as part of BIZ-66427 and implemented trigger framework and
                                                    moved all logic from ContractTriggerHandler to contractTriggerHelper class. and optimise the code
*  27/04/26         Manisha S                       BIZ-75817 Added populateMasterTermsContractNumber to auto-populate
                                                    Intapp Master Terms: Contract Number on Account
*  28/04/26         Manisha S                       BIZ-75817 (AC update) Simplified populateMasterTermsContractNumber:
                                                    removed Account.Type, Opportunity.StageName, and QT-0002 QuoteTerm
                                                    checks; added Quote.SBQQ__Type__c != 'Amendment' check
*  18/05/26         BIZ-82935                       Removed updateRenewalOpps() — Contract→Opportunity sync retired; Opportunity is now the source of truth for Renewal Hold
********************************************************************************/
public without sharing class ContractTriggerHelper {

    /**
     * @description Populates the Billing Account field on Contracts.
     * If the Billing Account is not already set, it uses the Account's Bill To Entity or defaults to the Account itself.
     * @param newContracts The list of Contract records to update.
     */
    public static void populateBillingAccount(List<Contract> newContracts){
        Map<Id, Id> mapAcct2ParentId = new Map<Id, Id>();
        for(Contract con: newContracts){
            if(con.AccountId != null && con.Billing_Account__c == null){
                mapAcct2ParentId.put(con.AccountId, null);
            }
        }
        for(Account a: [select Id, Bill_To_Entity__c from Account where Id in :mapAcct2ParentId.keySet()]){
            mapAcct2ParentId.put(a.Id, a.Bill_To_Entity__c);
        }
        for(Contract con: newContracts){
            if(con.AccountId != null && con.Billing_Account__c == null){
                con.Billing_Account__c = (mapAcct2ParentId.get(con.AccountId) != null)? mapAcct2ParentId.get(con.AccountId) : con.AccountId;
            }
        }    
    }
    
    /**
     * @description Processes and publishes eligible records for Contracts, Opportunities, Accounts, and Subscriptions.  
     * This method identifies records that have undergone significant changes and need to be synchronized 
     * with external systems by querying and publishing them accordingly.
     * @param contractNewList The list of newly inserted or updated Contract records.
     * @param contractOldMap A map of old Contract records, keyed by their IDs, to track field changes.
     */
    public static void publishEligibleSobjectRecords(list<Contract> contractNewList, Map<Id,Contract> contractOldMap) {
        List<Account> eligibleAccountList = new List<Account>();
        List<Opportunity> eligibleOpportunityList = new List<Opportunity>();
        List<Contract> lstOfContractsToSend = new List<Contract>();
        List<SBQQ__Subscription__c> eligibleSubscriptionList = new List<SBQQ__Subscription__c>();
        Set<id> setOfAccountId = new Set<id>();
        Set<id> setOfOpportunityId = new Set<id>();
        Set<id> setOfContractId = new Set<id>();
        
        /* BIZ-55114 Start */
        for(Contract contractObj : contractNewList){
            if(contractObj.OP4I_Contract_Id__c != null || contractObj.OP4I_Error__c !=null){
                lstOfContractsToSend.add(contractObj);  
            }
            if(contractObj.SBQQ__Opportunity__c != null && contractObj.OP4I_Contract_Id__c != contractOldMap.get(contractObj.id).OP4I_Contract_Id__c){
                setOfOpportunityId.add(contractObj.SBQQ__Opportunity__c);    
                setOfContractId.add(contractObj.Id);                    
            }               
            
            if(contractObj.Status == 'In Force' && contractObj.Subsidiary__c != null && contractObj.Subsidiary__c != contractOldMap.get(contractObj.id).Subsidiary__c){
                setOfAccountId.add(contractObj.AccountId);
            } 
        }
        
        if(!lstOfContractsToSend.IsEmpty() && lstOfContractsToSend.size() > 0){
            IntegrationUtility.publishEligibleSobjectRecords(lstOfContractsToSend,contractOldMap,'Contract');    
        }
        /* BIZ-55114 End */
        
        if(!setOfAccountId.isEmpty()){
            String strQuery = createQuery('Account',setOfAccountId);
            String strQueryUpd = strQuery.replace('setOfsObjectIds' , 'setOfAccountId');
            eligibleAccountList = Database.query(strQueryUpd);
        }
        
        if(!setOfOpportunityId.isEmpty()){
            List<Opportunity> lstOfOpportunities = [Select id from Opportunity where Related_Opportunity__c IN: setOfOpportunityId];
            if(lstOfOpportunities != null && !lstOfOpportunities.IsEmpty()){
                for(Opportunity opp : lstOfOpportunities){
                    setOfOpportunityId.add(opp.id);
                }                     
            }
            String strQuery = createQuery('Opportunity',setOfOpportunityId);
            String strQueryUpd = strQuery.replace('setOfsObjectIds' , 'setOfOpportunityId');
            eligibleOpportunityList = Database.query(strQueryUpd);
        }
        if(!setOfContractId.isEmpty()){                
            String strQuery = createQuerySubscription('SBQQ__Subscription__c',setOfContractId);
            String strQueryUpd = strQuery.replace('setOfsObjectIds' , 'setOfContractId');
            eligibleSubscriptionList = Database.query(strQueryUpd);
        }
        
        if(!eligibleAccountList.isEmpty()){
            IntegrationUtility.publishsObjectRecords(eligibleAccountList,'Account');
        }
        
        /* published Opportunities as part of BIZ-54487 */
        if(!eligibleOpportunityList.isEmpty()){
            IntegrationUtility.publishsObjectRecords(eligibleOpportunityList,'Opportunity');
        }
        if(!eligibleSubscriptionList.isEmpty()){
            IntegrationUtility.publishsObjectRecords(eligibleSubscriptionList,'SBQQ__Subscription__c');
        }
    }

    /**
     * @description Invocable method to publish an event after a Contract record is inserted.
     * This method is designed to be called from a Flow.
     * @param contractNewList The list of newly inserted Contract records.
     */
    @InvocableMethod(label='Send Updated Payload')
    public static void publishAfterInsertEventFromFlow(list<Contract> contractNewList) {  
        IntegrationUtility.publishsObjectRecords(contractNewList,'Contract');
    }

    /**
     * @description Constructs a dynamic SOQL query to fetch all fields for a given SObject.
     * @param sObjName The API name of the SObject (e.g., 'Account', 'Opportunity').
     * @param setOfsObjectIds The set of record IDs to be queried.
     * @return A string containing the dynamically generated SOQL query.
     */
    public static string createQuery(String sObjName , Set<Id> setOfsObjectIds) {
        Set<String> fieldNames = new Set<String>();
        Schema.SObjectType targetObjType = ((SObject)Type.forName(sObjName).newInstance()).getSObjectType();
        Map<String, Schema.SObjectField> fieldMap = targetObjType.getDescribe().fields.getMap();
        fieldNames = fieldMap.keyset();
        List<String> fields = new List<String>(fieldNames);
        String query =  ' SELECT ' +
            String.join( fields, ',' ) +
            ' FROM ' +
            sObjName +
            ' WHERE ' +
            ' Id IN: setOfsObjectIds';
        
        String strQuery1 = query.remove('{');
        String strQuery2 = strQuery1.remove('}');
        
        return strQuery2;
    } 
    
    /**
     * @description Constructs a dynamic SOQL query to fetch Subscription records linked to a given Contract.
     * @param sObjName The API name of the SObject (e.g., 'SBQQ__Subscription__c').
     * @param setOfsObjectIds The set of Contract IDs used to fetch related Subscriptions.
     * @return A string containing the dynamically generated SOQL query.
     */
    public static string createQuerySubscription(String sObjName , Set<Id> setOfsObjectIds) {
        Set<String> fieldNames = new Set<String>();
        Schema.SObjectType targetObjType = ((SObject)Type.forName(sObjName).newInstance()).getSObjectType();
        Map<String, Schema.SObjectField> fieldMap = targetObjType.getDescribe().fields.getMap();
        fieldNames = fieldMap.keyset();
        List<String> fields = new List<String>(fieldNames);
        String query =  ' SELECT ' +
            String.join( fields, ',' ) +
            ' FROM ' +
            sObjName +
            ' WHERE ' +
            ' SBQQ__Contract__c IN: setOfsObjectIds AND ' +
            ' OP4I_Entitlement_Id__c != null ';

        String strQuery1 = query.remove('{');
        String strQuery2 = strQuery1.remove('}');

        return strQuery2;
    }

    /**
     * @description Populates Master_Terms_Contract_Number__c on Account when a new Contract
     * is created and all qualifying conditions are met (BIZ-75817).
     * Conditions:
     *   - Account.Master_Terms_Contract_Number__c is blank
     *   - Quote.Contract_Master_Terms__c = 'URL Terms'
     *   - Quote.SBQQ__Type__c != 'Amendment'
     *   - Quote.Deal_Type__c != 'Services_Only'
     * @param newContracts List of newly inserted Contract records.
     */
    public static void populateMasterTermsContractNumber(List<Contract> newContracts) {
        // Guard: null/empty input
        if (newContracts == null || newContracts.isEmpty()) {
            return;
        }

        try {
            // Step 1: Filter contracts that have required lookups populated
            Set<Id> contractIds = new Set<Id>();
            for (Contract con : newContracts) {
                if (con != null
                    && con.Id != null
                    && con.AccountId != null
                    && con.SBQQ__Quote__c != null) {
                    contractIds.add(con.Id);
                }
            }
            if (contractIds.isEmpty()) {
                return;
            }

            // Step 2: Fetch Contracts with related Account and Quote in a single query
            List<Contract> contractsWithRelations = [
                SELECT Id, AccountId, SBQQ__Quote__c,
                       Account.Master_Terms_Contract_Number__c,
                       SBQQ__Quote__r.Contract_Master_Terms__c,
                       SBQQ__Quote__r.Deal_Type__c,
                       SBQQ__Quote__r.SBQQ__Type__c
                FROM Contract
                WHERE Id IN :contractIds
            ];
            if (contractsWithRelations.isEmpty()) {
                return;
            }

            // Step 3: Build the Account update map (first-wins for duplicate AccountIds)
            Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
            for (Contract con : contractsWithRelations) {
                // Null-safe checks on relationship fields
                if (con.Account == null || con.SBQQ__Quote__r == null) {
                    continue;
                }
                // Account: lookup must be blank
                if (con.Account.Master_Terms_Contract_Number__c != null) {
                    continue;
                }
                // Quote: URL Terms AND not Amendment AND not Services_Only
                if (con.SBQQ__Quote__r.Contract_Master_Terms__c != QuoteConstants.CONTRACT_MASTER_TERMS_URL
                    || con.SBQQ__Quote__r.SBQQ__Type__c == QuoteConstants.TYPE_AMENDMENT
                    || con.SBQQ__Quote__r.Deal_Type__c == QuoteConstants.DEAL_TYPE_SERVICES_ONLY) {
                    continue;
                }
                // first-wins: skip if AccountId already mapped
                if (accountsToUpdate.containsKey(con.AccountId)) {
                    continue;
                }
                accountsToUpdate.put(con.AccountId, new Account(
                    Id = con.AccountId,
                    Master_Terms_Contract_Number__c = con.Id
                ));
            }

            // Step 4: Bulk update Accounts with partial success enabled
            if (!accountsToUpdate.isEmpty()) {
                List<Account> accountsList = accountsToUpdate.values();
                Database.SaveResult[] saveResults = Database.update(accountsList, false);
                for (Integer i = 0; i < saveResults.size(); i++) {
                    if (!saveResults[i].isSuccess()) {
                        String errorMsg = '';
                        for (Database.Error err : saveResults[i].getErrors()) {
                            errorMsg += err.getStatusCode() + ': ' + err.getMessage() + '; ';
                        }
                        Nebula.Logger.error(
                            'BIZ-75817 Account update failed for Id=' + accountsList[i].Id + ' - ' + errorMsg
                        ).addTag('BIZ-75817');
                    }
                }
                Nebula.Logger.saveLog();
            }
        } catch (Exception e) {
            // Catch-all to prevent trigger failure
            Nebula.Logger.error(
                'BIZ-75817 ContractTriggerHelper.populateMasterTermsContractNumber failed: '
                + e.getMessage() + '\n' + e.getStackTraceString(), e
            ).addTag('BIZ-75817');
            Nebula.Logger.saveLog();
        }
    }
}