Doc/force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-Legal - APAC</fullName>
            </value>
            <value>
                <fullName>02-Legal - Growth EMEA</fullName>
            </value>
            <value>
                <fullName>03-Legal - Pursuit Global</fullName>
            </value>
            <value>
                <fullName>04-Legal - Growth NA East</fullName>
            </value>
            <value>
                <fullName>05-Legal - Growth NA West</fullName>
            </value>
            <value>
                <fullName>06-Legal - Growth NA Central</fullName>
            </value>
            <value>
                <fullName>07-Legal - Growth NA Portfolio</fullName>
            </value>
            <value>
                <fullName>08-A&amp;C - Big 4</fullName>
            </value>
            <value>
                <fullName>09-A&amp;C - Accounting</fullName>
            </value>
            <value>
                <fullName>10-A&amp;C - Consulting</fullName>
            </value>
            <value>
                <fullName>11-FS New Sales - IB&amp;A Enterprise</fullName>
            </value>
            <value>
                <fullName>12-FS New Sales - PCM Enterprise</fullName>
            </value>
            <value>
                <fullName>13-FS New Sales - Americas Mid-Market</fullName>
            </value>
            <value>
                <fullName>14-FS New Sales - EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>15-FS New Sales - EMEA Mid-Market</fullName>
            </value>
            <value>
                <fullName>16-FS New Sales - APAC</fullName>
            </value>
            <value>
                <fullName>17-FS AM - PCM Enterprise Central</fullName>
            </value>
            <value>
                <fullName>18-FS AM - PCM Enterprise East</fullName>
            </value>
            <value>
                <fullName>19-FS AM - PCM Mid-Market Growth</fullName>
            </value>
            <value>
                <fullName>20-FS AM - PCM Mid-Market Retention</fullName>
            </value>
            <value>
                <fullName>21-FS AM - IB&amp;A Mid-Market</fullName>
            </value>
            <value>
                <fullName>22-FS AM - IB&amp;A Enterprise</fullName>
            </value>
            <value>
                <fullName>23-FS AM - EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>24-FS AM - EMEA Mid-Market</fullName>
            </value>
            <value>
                <fullName>25-FS AM - APAC</fullName>
            </value>
            <value>
                <fullName>26-RA New Sales</fullName>
            </value>
            <value>
                <fullName>27-RA AM</fullName>
            </value>
            <value>
                <fullName>28-Other</fullName>
            </value>
            <value>
                <fullName>29-Partner Reseller Channel</fullName>
            </value>
            <value>
                <fullName>02-Legal - EMEA</fullName>
                <isActive>false</isActive>
                <label>02-Legal - EMEA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

Doc/force-app/main/default/objects/Contract/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <description>&apos;First invoice period (number of months)</description>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Quote mapping twin field  BIZ-49780</description>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/License_Basis__c/License_Basis__c.object-meta.xml
<CustomObject>
    <description>This object stores the license basis data as related to Product Lines</description>
    <label>License Basis</label>
    <nameField>
        <label>License Basis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Basis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Initial_Software_Term_Length_Months__c.field-meta.xml
<CustomField>
    <fullName>Initial_Software_Term_Length_Months__c</fullName>
    <inlineHelpText>Please populate the initial term length in months. For a standard deal, this should say 12. For non standard deals, add the additional months in. For example, if you are providing an additional 2 months to the initial term, populate 14 in this field.</inlineHelpText>
    <label>Initial Software Term Length (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/sbaa__ApprovalStep__c.field-meta.xml
<CustomField>
    <fullName>sbaa__ApprovalStep__c</fullName>
    <description>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</description>
    <inlineHelpText>Used with Native Approvals to indicate the step in the approval process this Opportunity is in</inlineHelpText>
    <label>Approval Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <defaultValue>12</defaultValue>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Firmwide</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/User/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>To display OP4I Sales Segment of User. Created as part of BIZ-50210.</description>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Op4I_Sales_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/QTC_GreenboxApproveAllTest.cls
@isTest
public class QTC_GreenboxApproveAllTest {
    @testSetup
    static void setup(){
        Account account = (Account) SmartFactory.createSObject('Account');
        account.Industry = 'Test Industry';
        account.BillingCountry = 'Test';
        account.OP4I_Sales_Segment__c = '';
        insert account;
        
        Contact con = (Contact) SmartFactory.createSObject('Contact');
        con.AccountId = account.Id; 
        insert con;
        
        Contract ctr = (Contract) SmartFactory.createSObject('Contract');
        ctr.AccountId = account.Id;
        insert ctr;
        
        Opportunity opportunity = (Opportunity) SmartFactory.createSObject('Opportunity');
        opportunity.AccountId = account.Id;
        opportunity.Associated_Contract_OSA__c = ctr.Id;
        opportunity.Contract_Signer__c = con.Id;
        opportunity.Requested_Contract_Expiration__c = Date.today();
        opportunity.Initial_Software_Term_Length_Months__c = 12;
        insert opportunity;
        
        
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.OP4I_Sales_Segment__c = '03-Legal EMEA';
        newQuote.SBQQ__Opportunity2__c = opportunity.Id;
        newQuote.SBQQ__Account__c = account.Id;
        newQuote.SBQQ__SubscriptionTerm__c = 36;
        newQuote.First_Segment_Months__c = 12;
        newQuote.License_Basis__c = 'Lawyers';
        newQuote.ApprovalStatus__c = 'Pending';
        newQuote.SBQQ__StartDate__c = system.today();
        insert newQuote;
        
        
        
        
    }
    
    @isTest static void processRecords(){   
        Profile pr = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];
        //Contact con = [SELECT Id FROM Contact LIMIT 1]; 
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                             localesidkey='en_US', profileid = pr.Id, country='United States',IsActive =true,
                             timezonesidkey='America/Los_Angeles', username='testrituNagi383@gmail.com');
        
        insert user;
        
        
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Approve_All'];
        
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = user.Id,
            PermissionSetId = ps.Id
            
        );
        insert psa;
       
        Test.startTest();
        System.runAs(user) {
            System.assertEquals(true, FeatureManagement.checkPermission('Approve_All'));
            SBQQ__Quote__c quoteLst = [SELECT Id, ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];
            List<String> quoteId = new List<String>();
            //for(SBQQ__Quote__c qt : quoteLst){
                quoteId.add(quoteLst.Id+'-$-');
            //}
            
            sbaa__Approval__c oApproval = new sbaa__Approval__c();
            oApproval.sbaa__Status__c = 'Assigned';
            oApproval.sbaa__AssignedTo__c = user.Id;
            oApproval.sbaa__ApprovedBy__c = user.Id;
            oApproval.sbaa__ApprovalStep__c = 1.00;
            oApproval.sbaa__RecordField__c = '1';
            oApproval.Quote__c = quoteLst.Id;
            insert oApproval;
            
            QTC_GreenboxApproveAll.approveAllOpenApprovals(quoteId); 
        }
        Test.stopTest();
    }
}