Doc/force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01-Legal - APAC</fullName>
            </value>
            <value>
                <fullName>02-Legal - Growth EMEA</fullName>
            </value>
            <value>
                <fullName>03-Legal - Pursuit Global</fullName>
            </value>
            <value>
                <fullName>04-Legal - Growth NA East</fullName>
            </value>
            <value>
                <fullName>05-Legal - Growth NA West</fullName>
            </value>
            <value>
                <fullName>06-Legal - Growth NA Central</fullName>
            </value>
            <value>
                <fullName>07-Legal - Growth NA Portfolio</fullName>
            </value>
            <value>
                <fullName>08-A&amp;C - Big 4</fullName>
            </value>
            <value>
                <fullName>09-A&amp;C - Accounting</fullName>
            </value>
            <value>
                <fullName>10-A&amp;C - Consulting</fullName>
            </value>
            <value>
                <fullName>11-FS New Sales - IB&amp;A Enterprise</fullName>
            </value>
            <value>
                <fullName>12-FS New Sales - PCM Enterprise</fullName>
            </value>
            <value>
                <fullName>13-FS New Sales - Americas Mid-Market</fullName>
            </value>
            <value>
                <fullName>14-FS New Sales - EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>15-FS New Sales - EMEA Mid-Market</fullName>
            </value>
            <value>
                <fullName>16-FS New Sales - APAC</fullName>
            </value>
            <value>
                <fullName>17-FS AM - PCM Enterprise Central</fullName>
            </value>
            <value>
                <fullName>18-FS AM - PCM Enterprise East</fullName>
            </value>
            <value>
                <fullName>19-FS AM - PCM Mid-Market Growth</fullName>
            </value>
            <value>
                <fullName>20-FS AM - PCM Mid-Market Retention</fullName>
            </value>
            <value>
                <fullName>21-FS AM - IB&amp;A Mid-Market</fullName>
            </value>
            <value>
                <fullName>22-FS AM - IB&amp;A Enterprise</fullName>
            </value>
            <value>
                <fullName>23-FS AM - EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>24-FS AM - EMEA Mid-Market</fullName>
            </value>
            <value>
                <fullName>25-FS AM - APAC</fullName>
            </value>
            <value>
                <fullName>26-RA New Sales</fullName>
            </value>
            <value>
                <fullName>27-RA AM</fullName>
            </value>
            <value>
                <fullName>28-Other</fullName>
            </value>
            <value>
                <fullName>29-Partner Reseller Channel</fullName>
            </value>
            <value>
                <fullName>02-Legal - EMEA</fullName>
                <isActive>false</isActive>
                <label>02-Legal - EMEA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/Automation_Controls__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Automation Controls</label>
</CustomObject>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Controls__c/fields/Data_Id__c.field-meta.xml
<CustomField>
    <fullName>Data_Id__c</fullName>
    <description>Comma separated value, If any ID in this list found, the trigger/flow execution would be bypassed even in bulk operations.</description>
    <inlineHelpText>MAINTAIN CAUTION. If any ID in this list found, the trigger/flow execution would be bypassed even in bulk operations.</inlineHelpText>
    <label>Data Id</label>
    <type>TextArea</type>
</CustomField>

Doc/force-app/main/default/objects/Automation_Controls__c/fields/Quote_Bypass__c.field-meta.xml
<CustomField>
    <fullName>Quote_Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Bypass</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

Doc/force-app/main/default/objects/Contract/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
  ISPICKVAL(StatusCode,&quot;Activated&quot;),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <description>&apos;First invoice period (number of months)</description>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Quote mapping twin field  BIZ-49780</description>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/License_Basis__c/License_Basis__c.object-meta.xml
<CustomObject>
    <description>This object stores the license basis data as related to Product Lines</description>
    <label>License Basis</label>
    <nameField>
        <label>License Basis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Basis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Initial_Software_Term_Length_Months__c.field-meta.xml
<CustomField>
    <fullName>Initial_Software_Term_Length_Months__c</fullName>
    <inlineHelpText>Please populate the initial term length in months. For a standard deal, this should say 12. For non standard deals, add the additional months in. For example, if you are providing an additional 2 months to the initial term, populate 14 in this field.</inlineHelpText>
    <label>Initial Software Term Length (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <defaultValue>12</defaultValue>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Firmwide</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/User/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>To display OP4I Sales Segment of User. Created as part of BIZ-50210.</description>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Op4I_Sales_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutomationPreferenceTest.cls
/**
* @description       : Test class for AutomationPreference. This class provides comprehensive test coverage for
*                      the automation preference utility functionality, including validation of automation execution
*                      control based on Automation_Controls__c custom setting configuration. Tests cover various
*                      scenarios including global bypass, selective bypass with Data_Id__c, and inactive controls.
* @author            : Sahal Mohamed
* Created Date       : Jan-08-2026
**/
@isTest
public class AutomationPreferenceTest {
    
    /***********************************************************************************************
    *
    * Test Setup and Helper Methods
    *
    ***********************************************************************************************/
    
    /**
    * @description Creates test data including accounts, contacts, contracts, opportunities, quotes,
    *              users, and approver matrix records for use in test methods. This method is called
    *              automatically by the test framework before each test method execution.
    **/
    @testSetup
    static void setupTestData() {
        // Create User first (setup object) to avoid MIXED_DML_OPERATION
        User testUser = (User)TestFactory.createSObject(
            new User(
                LastName = 'Testing',
                FirstName = 'Test',
                Email = 'test@testintapp.com'
            ), 'AdminUserDefaults'
        );
        
        // Use System.runAs to separate setup object from non-setup objects
        System.runAs(testUser) {
            // Create Account using TestFactory
            Account account = (Account)TestFactory.createSObject(
                new Account(
                    Name = 'Test Account',
                    BillingCountry = 'United States'
                ), 'AccountDefaults'
            );
            
            // Create Contact using TestFactory
            Contact contact = (Contact)TestFactory.createSObject(
                new Contact(
                    AccountId = account.Id,
                    FirstName = 'Test',
                    LastName = 'Contact'
                ), 'ContactDefaults'
            );
            
            // Create Contract using TestFactory
            Contract contract = (Contract)TestFactory.createSObject(
                new Contract(
                    AccountId = account.Id,
                    StartDate = Date.today(),
                    ContractTerm = 12
                ), 'ContractDefaults'
            );
            
            // Create Opportunity using TestFactory
            Opportunity opportunity = (Opportunity)TestFactory.createSObject(
                new Opportunity(
                    AccountId = account.Id,
                    Name = 'Test Opportunity',
                    StageName = 'Prospecting',
                    CloseDate = Date.today().addDays(30),
                    Associated_Contract_OSA__c = contract.Id,
                    Contract_Signer__c = contact.Id,
                    Requested_Contract_Expiration__c = Date.today(),
                    Initial_Software_Term_Length_Months__c = 12
                ), 'OpportunityDefaults'
            );
            
            // Create Approvers Matrix using TestFactory (no defaults class, so use buildSObject)
            Approvers_Matrix__c approverMatrix = (Approvers_Matrix__c)TestFactory.buildSObject(
                new Approvers_Matrix__c(
                    Sales_Segment__c = '03-Legal EMEA',
                    Approver_Role__c = 'Segment Lead',
                    Approver_User__c = testUser.Id
                )
            );
            insert approverMatrix;
            
            // Create Quote using TestFactory
            TestFactory.createSObject(
                new SBQQ__Quote__c(
                    OP4I_Sales_Segment__c = '03-Legal EMEA',
                    SBQQ__Opportunity2__c = opportunity.Id,
                    SBQQ__Account__c = account.Id,
                    SBQQ__SubscriptionTerm__c = 36,
                    First_Segment_Months__c = 12,
                    License_Basis__c = 'Lawyers',
                    SBQQ__StartDate__c = System.today()
                ), 'SBQQQuoteDefaults'
            );
        }
    }
    
    /***********************************************************************************************
    *
    * Test Methods
    *
    ***********************************************************************************************/
    
    /**
    * @description Tests that automation execution is bypassed (returns false) when Automation_Controls__c
    *              is active, bypass is enabled, and Data_Id__c is blank. This validates the global bypass
    *              functionality where all records of the specified object type are bypassed when Data_Id__c
    *              is null or blank.
    **/
    @isTest
    static void testBypassWithDataIdBlank() {
        // Get test quote
        List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        
        // Create Automation Controls with blank Data_Id__c (global bypass)
        Automation_Controls__c automationControl = new Automation_Controls__c(
            SetupOwnerId = UserInfo.getUserId(),
            Active__c = true,
            Bypass_Triggers__c = true,
            Quote_Bypass__c = true,
            Data_Id__c = null
        );
        insert automationControl;
        
        Test.startTest();
        Map<Id, Boolean> result = AutomationPreference.validateExecution('SBQQ__Quote__c', quotes);
        Test.stopTest();
        
        // Should not execute (false) when Data_Id__c is blank and bypass is enabled
        System.assertEquals(false, result.get(quotes[0].Id), 'Should not execute if Data_Id__c is blank');
    }
    
    /**
    * @description Tests that automation execution is bypassed (returns false) when Automation_Controls__c
    *              Data_Id__c matches the record ID. This validates the selective bypass functionality
    *              where only specific records identified by Data_Id__c are bypassed from automation execution.
    **/
    @isTest
    static void testBypassWithDataIdMatch() {
        // Get test quote
        List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id recordId = quotes[0].Id;
        
        // Create Automation Controls with matching Data_Id__c (selective bypass)
        Automation_Controls__c automationControl = new Automation_Controls__c(
            SetupOwnerId = UserInfo.getUserId(),
            Active__c = true,
            Bypass_Triggers__c = true,
            Quote_Bypass__c = true,
            Data_Id__c = recordId // Include record in bypass list
        );
        insert automationControl;
        
        Test.startTest();
        Map<Id, Boolean> result = AutomationPreference.validateExecution('SBQQ__Quote__c', quotes);
        Test.stopTest();
        
        // Should bypass trigger (false) for matching Data_Id__c
        System.assertEquals(false, result.get(recordId), 'Should bypass trigger (false) for matching Data_Id__c');
    }
    
    /**
    * @description Tests that automation execution is allowed (returns true) when Automation_Controls__c
    *              Data_Id__c does not match the record ID. This validates that records not in the
    *              Data_Id__c list are not bypassed and automation executes normally.
    **/
    @isTest
    static void testBypassWithDataIdNotMatch() {
        // Get test quote
        List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id recordId = quotes[0].Id;
        
        // Create Automation Controls with non-matching Data_Id__c
        Automation_Controls__c automationControl = new Automation_Controls__c(
            SetupOwnerId = UserInfo.getUserId(),
            Active__c = true,
            Bypass_Triggers__c = true,
            Quote_Bypass__c = true,
            Data_Id__c = 'someOtherId' // Different ID, so record should not be bypassed
        );
        insert automationControl;
        
        Test.startTest();
        Map<Id, Boolean> result = AutomationPreference.validateExecution('SBQQ__Quote__c', quotes);
        Test.stopTest();
        
        // Should allow trigger (true) if Data_Id__c does not match
        System.assertEquals(true, result.get(recordId), 'Should allow trigger (true) if Data_Id__c does not match');
    }
    
    /**
    * @description Tests that automation execution is allowed (returns true) when Automation_Controls__c
    *              is inactive, even if bypass flags are set to false. This validates that inactive
    *              controls do not affect automation execution and execution is allowed by default.
    **/
    @isTest
    static void testBypassFalseControlInactive() {
        // Get test quote
        List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        
        // Create Automation Controls with Active__c = false (inactive)
        Automation_Controls__c automationControl = new Automation_Controls__c(
            SetupOwnerId = UserInfo.getUserId(),
            Active__c = false, // Inactive control should not affect execution
            Bypass_Triggers__c = false,
            Quote_Bypass__c = false
        );
        insert automationControl;
        
        Test.startTest();
        Map<Id, Boolean> result = AutomationPreference.validateExecution('SBQQ__Quote__c', quotes);
        Test.stopTest();
        
        // Should allow trigger (true) when bypass flags are false or control is inactive
        System.assertEquals(true, result.get(quotes[0].Id), 'Should allow trigger (true) when bypass flags are false');
    }
    
    /**
    * @description Tests that CPQ trigger control methods (disable and enable) can be executed
    *              without errors. This validates the integration with DisableCPQtriggers and
    *              EnableCPQtriggers utility classes.
    **/
    @isTest
    static void testValidateCPQTriggerControls() {
        Test.startTest();
        DisableCPQtriggers.disableCPQTriggerExecutions();
        EnableCPQtriggers.enableCPQTriggerExecutions();
        Test.stopTest();
        
        // Verify methods executed without exception
        System.assert(true, 'CPQ trigger control methods should execute successfully');
    }
    
}