Doc/force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for POC, will hold Account information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Captures full Address of the Account</description>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This will return Address Country value.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Address__c/fields/Default_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Default_Shipping_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Shipping Address</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Address__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Governance&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>BIZ-64132. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(SBQQ__Account__r.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures valid shipping account</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Ship To Account)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures Ship To address</description>
    <label>Ship To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Ship_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Quotes (Ship To Address)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:The Frayman Group, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:Intapp Singapore Pte. Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>42:Intapp Employee Compliance, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>44:Intapp Germany GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>08:Intapp Pty, Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>40:Intapp Ireland Limited</fullName>
    </customValue>
    <customValue>
        <fullName>46:Intapp Netherlands B.V.</fullName>
    </customValue>
    <customValue>
        <fullName>50:TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Delphai Subsidiary (placeholder)</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet Subsidiary</fullName>
        <isActive>false</isActive>
        <label>TermSheet Subsidiary</label>
    </customValue>
    <customValue>
        <fullName>46:Transform Data International</fullName>
        <isActive>false</isActive>
        <label>46:Transform Data International</label>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>42:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
        <isActive>false</isActive>
        <label>05:400 TFG - US</label>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
        <isActive>false</isActive>
        <label>28:OnePlace Pte Ltd</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandlerTestPooja.cls
@isTest
public class QuoteTriggerHandlerTestPooja {
	
    
    @isTest
    static void testUpdateSubsidiary_ForAustria() {
        // Arrange
        //Opportunity opp = getOpportunity();
    
        // Create subsidiary Account
        Account acc = new Account(Name = 'Intapp Ireland Limited', Type = AccountConstants.TYPE_PROSPECT);
        insert acc;
        // Create subsidiary Account
        Account acc1 = new Account(Name = 'Intapp Ireland Limited', Type = AccountConstants.TYPE_PROSPECT);
        insert acc1;
        
        // Create test Opportunities
        List<Opportunity> opp = (List<Opportunity>)TestFactory.createSObjectList(
            new Opportunity(
                Name = 'Test Opportunity',
                StageName = 'Prospecting',
                CloseDate = Date.today().addMonths(1),
                AccountId = acc.Id
            ), 1, 'OpportunityDefaults'
        );
    
        // Create Address using your data factory
        List<Address__c> addrList = TestDataFactory.createAddress(1, false, acc.Id);
        Address__c addr = addrList[0];
    
        // Update the Address to represent Austria
        addr.Status__c = 'Verification Approved';
        addr.Address__CountryCode__s = 'AT';   // ISO code for Austria
        //addr.Country__c = 'Austria';           // Explicit country name (for mapping logic)
        addr.Address__City__s = 'Vienna';
        addr.Address__PostalCode__s = '1010';
        addr.Address__Street__s = 'Mariahilfer Straße';
        addr.Address__StateCode__s = '';
        addr.Account__c=acc.Id;
        insert addr;
        
        addr.Default_Shipping_Address__c = true;
        addr.Country__c = 'Austria';
    	update addr;
        
        System.debug('addr -> ' + addr);
        Map<Id, Address__c> addressMap = new Map<Id, Address__c>(
            [SELECT Id, Country__c, Address__c, Address__CountryCode__s FROM Address__c]
        );
    	System.debug('addressMap -> ' + addressMap);
        
        addr.Country__c = 'Austria'; 
        update addr;
        
        // Update Account to "Verification Approved" to meet logic conditions
        acc.Status__c = 'Verification Approved';
        update acc;
    
        // Create a Quote that triggers the subsidiary mapping
        SBQQ__Quote__c austriaQuote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp[0].Id,
            SBQQ__Account__c = acc.Id,
            Ship_To_Account__c = acc.Id
        );
        insert austriaQuote; // Trigger calls updateSubsidiary internally
    
        // Act
        Test.startTest();
        
        austriaQuote.Ship_To_Address__c = addr.Id;
        austriaQuote.SBQQ__Account__c = acc1.Id;
        update austriaQuote;
        Test.stopTest();
    
        // Assert
        SBQQ__Quote__c result = [
            SELECT Id, Subsidiary__c, Account_Type__c
            FROM SBQQ__Quote__c
            WHERE Id = :austriaQuote.Id
        ];
    
        System.assertEquals(
            '40:Intapp Ireland Limited',
            result.Subsidiary__c,
            'Subsidiary__c should match the subsidiary name for Austria.'
        );
    }
}