Doc/force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Account with whom we have the billing relationship.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
            <value>
                <fullName>Renewal Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/OP4I_Entitlement_View__c.object-meta.xml
<CustomObject>
    <label>OP4I Entitlement View</label>
    <nameField>
        <label>OP4I Entitlement View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OP4I Entitlement Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Quarterly Y1 Only</fullName>
            </value>
            <value>
                <fullName>Semi-annual Y1 Only</fullName>
            </value>
            <value>
                <fullName>Invoice Plan</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>No Software</fullName>
            </value>
            <value>
                <fullName>XXXXX</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLI_Product__c.field-meta.xml
<CustomField>
    <fullName>DLI_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLI Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLI Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views1</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLIP_Product__c.field-meta.xml
<CustomField>
    <fullName>DLIP_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLIP Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLIP Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>This is the date that the billing pause ends and the billing restarts.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Migration Contract)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date the the billing pause begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>BIZ-64132. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Services Discount</fullName>
            </value>
            <value>
                <fullName>Software Discount (Recurring)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Training Discount</fullName>
            </value>
            <value>
                <fullName>Early Adopter</fullName>
            </value>
            <value>
                <fullName>Software Discount (One-Time)</fullName>
            </value>
            <value>
                <fullName>Tax Only</fullName>
            </value>
            <value>
                <fullName>Services (Recurring)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
    <inlineHelpText>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewable</fullName>
                <default>true</default>
                <label>Renewable</label>
            </value>
            <value>
                <fullName>One-time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (Migration Contract)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:The Frayman Group, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:Intapp Singapore Pte. Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>42:Intapp Employee Compliance, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>44:Intapp Germany GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>08:Intapp Pty, Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>40:Intapp Ireland Limited</fullName>
    </customValue>
    <customValue>
        <fullName>46:Intapp Netherlands B.V.</fullName>
    </customValue>
    <customValue>
        <fullName>50:TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Delphai Subsidiary (placeholder)</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet Subsidiary</fullName>
        <isActive>false</isActive>
        <label>TermSheet Subsidiary</label>
    </customValue>
    <customValue>
        <fullName>46:Transform Data International</fullName>
        <isActive>false</isActive>
        <label>46:Transform Data International</label>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>42:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
        <isActive>false</isActive>
        <label>05:400 TFG - US</label>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
        <isActive>false</isActive>
        <label>28:OnePlace Pte Ltd</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/classes/OpportunityQuoteMigrationBatchTest.cls
/********************************************************************************     
 *  Name             :  OpportunityQuoteMigrationBatch
 *  Author           :  Snehal Choudhary
 *  Description      :  Test Class for OpportunityQuoteMigrationBatch
 *                   
 *  Change history   :
 *  Date               Author             Description
 *  02/11/2023    Snehal Choudhary          Created
 ********************************************************************************/

@isTest
private class OpportunityQuoteMigrationBatchTest {    
    @testSetup static void setup() {
    Account acc = IntappTestObjectFactory.createaccount(true);
    Account billingAccount = IntappTestObjectFactory.createaccount(true);

    Product2 prodObj = IntappTestObjectFactory.createProduct(true);
    prodObj.Name = 'TestProd';
    update prodObj;
    
    Contract con = IntappTestObjectFactory.createcontract(acc.Id);
    con.Billing_Account__c = billingAccount.Id;
    insert con;
    
    SBQQ__Quote__c quoteObj = IntappTestObjectFactory.createSBQQQuote();
    insert quoteObj;
    
    OP4I_Entitlement_View__c entitlement = new OP4I_Entitlement_View__c();
    entitlement.Associated_OSA__c = con.id;
    entitlement.Start_Date__c = Date.newInstance(2021, 4, 1);
    entitlement.End_Date__c = Date.newInstance(2022, 3, 31);
    entitlement.Sale_Price__c = 20.22;
    entitlement.Product_Type__c = 'Software';
    entitlement.DLI_Product__c = prodObj.id;
    entitlement.DLIP_Product__c = prodObj.id;
    entitlement.Billing_Frequency__c = 'Annual';
    insert entitlement;
    }  
  
  @isTest 
  private static void testMethod1() {
    test.startTest();
    product2 prodTest = [Select Id FROM Product2 WHERE Name = 'TestProd' LIMIT 1] ;
    prodTest.IsActive = true;
    prodTest.SBQQ__SubscriptionPricing__c = 'Fixed Price';
    prodTest.SBQQ__SubscriptionTerm__c = 12;
    prodTest.SBQQ__SubscriptionType__c = 'Renewable';
    prodTest.SBQQ__ChargeType__c = 'Recurring';
    prodTest.SBQQ__BillingFrequency__c = 'Annual';
    prodTest.SBQQ__BillingType__c = 'Arrears';
    update prodTest;

    Contract contr = [Select Id,Processing_Status__c FROM Contract LIMIT 1];
    contr.Status = 'Activated';
    update contr;
    contr.Status = 'In Force';
    contr.Subsidiary__c = '05:The Frayman Group, Inc.';
    contr.Migration_Status__c = 'Ready';
    update contr; 
    OpportunityQuoteMigrationBatch oppQuoteObj = new OpportunityQuoteMigrationBatch();
    database.executebatch(oppQuoteObj,1);
    test.stopTest();  
    Contract contrUpd = [Select Id,Processing_Status__c FROM Contract WHERE Id =: contr.Id LIMIT 1];
    System.assertEquals('Quote Created',contrUpd.Processing_Status__c);
  }
  
  @isTest 
  private static void testMethod2() {
    test.startTest();
    product2 prodTest = [Select Id FROM Product2 WHERE Name = 'TestProd' LIMIT 1] ;
    prodTest.IsActive = true;
    prodTest.SBQQ__SubscriptionPricing__c = 'Fixed Price';
    prodTest.SBQQ__SubscriptionTerm__c = 12;
    prodTest.SBQQ__SubscriptionType__c = 'Renewable';
    prodTest.SBQQ__ChargeType__c = 'Recurring';
    prodTest.SBQQ__BillingFrequency__c = 'Annual';
    prodTest.SBQQ__BillingType__c = 'Arrears';
    update prodTest;

    Contract contr = [Select Id,Processing_Status__c FROM Contract LIMIT 1];
    contr.Status = 'Activated';
    update contr;
    contr.Status = 'In Force';
    contr.Subsidiary__c = '05:The Frayman Group, Inc.';
    contr.Migration_Status__c = 'Ready';
    update contr;

    SBQQ__Quote__c quoteObj = [Select Id FROM SBQQ__Quote__c LIMIT 1];
    quoteObj.Migration_Contract__c = contr.id;
    update quoteObj;
    
    Opportunity oppObj = IntappTestObjectFactory.createOpportunity();   
    oppObj.Migration_Contract__c = contr.id;
    insert oppObj;
        
    OpportunityQuoteMigrationBatch oppQuoteObj = new OpportunityQuoteMigrationBatch();
    database.executebatch(oppQuoteObj,1); 
    test.stopTest();
    Contract contrUpd = [Select Id,Processing_Status__c FROM Contract WHERE Id = :contr.Id LIMIT 1];
    System.assertEquals('Quote Created',contrUpd.Processing_Status__c);  
  }
}