Doc/force-app/main/default/objects/Account/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Silver)</fullName>
                <default>true</default>
                <label>Standard (Silver)</label>
            </value>
            <value>
                <fullName>Premium (Gold)</fullName>
            </value>
            <value>
                <fullName>Premium (Platinum)</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Legacy_Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Quote_Id__c</fullName>
    <description>Reference to previously linked SBQQ__Quote__c record.</description>
    <label>Legacy Quote Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
            <value>
                <fullName>Renewal Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/OP4I_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_ID__c</fullName>
    <description>Custom field made to populate the Deal Id on contract record from op4i.
Built according to US # BIZ-46098</description>
    <label>OnePlace ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/OP4I_Entitlement_View__c.object-meta.xml
<CustomObject>
    <label>OP4I Entitlement View</label>
    <nameField>
        <label>OP4I Entitlement View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OP4I Entitlement Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Additional_Discount__c.field-meta.xml
<CustomField>
    <fullName>Additional_Discount__c</fullName>
    <label>Additional Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Quarterly Y1 Only</fullName>
            </value>
            <value>
                <fullName>Semi-annual Y1 Only</fullName>
            </value>
            <value>
                <fullName>Invoice Plan</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>No Software</fullName>
            </value>
            <value>
                <fullName>XXXXX</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLI_Id__c.field-meta.xml
<CustomField>
    <fullName>DLI_Id__c</fullName>
    <label>DLI Id</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLI_Product__c.field-meta.xml
<CustomField>
    <fullName>DLI_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLI Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLI Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views1</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLIP_Product__c.field-meta.xml
<CustomField>
    <fullName>DLIP_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLIP Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLIP Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views2</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Include_in_Select_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Select_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Select Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/OP4I_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Id__c</fullName>
    <label>OP4I Deal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Parent_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent_Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Segment_Index__c.field-meta.xml
<CustomField>
    <fullName>Segment_Index__c</fullName>
    <label>Segment Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Subscription_Term__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Term__c</fullName>
    <label>Subscription Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Services Discount</fullName>
            </value>
            <value>
                <fullName>Software Discount (Recurring)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Training Discount</fullName>
            </value>
            <value>
                <fullName>Early Adopter</fullName>
            </value>
            <value>
                <fullName>Software Discount (One-Time)</fullName>
            </value>
            <value>
                <fullName>Tax Only</fullName>
            </value>
            <value>
                <fullName>Services (Recurring)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Doc/force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
    <inlineHelpText>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewable</fullName>
                <default>true</default>
                <label>Renewable</label>
            </value>
            <value>
                <fullName>One-time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Include_in_Select_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Select_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Select Bundle?</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubscriptionsMigrationBatch_test.cls
/**
 * @description Test class for SubscriptionsMigrationBatch_test.
 * @author      Manisha
 * @date        2025-05-06
 * @jira        BIZ-69719
 */
@isTest
public class SubscriptionsMigrationBatch_test {
    @TestSetup
    static void setup() {
        Account a = IntappTestObjectFactory.createaccount(true);
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Pricebook2 customPricebook = new Pricebook2(
            Name = Label.MigrationPriceBookName,
            IsActive = true
        );
        insert customPricebook;
        
        List<SBQQ__Quote__c> quotes = (List<SBQQ__Quote__c>)TestFactory.createSObjectList(
            new SBQQ__Quote__c(
                SBQQ__Account__c = a.Id,
                Deal_Type__c = 'Renewal'
            ), 3, 'SBQQQuoteDefaults'
        );
        
        Product2 prodObj = IntappTestObjectFactory.createProduct(true);
        prodObj.Name = 'Intapp Select Bundle';
        prodObj.isActive= true;
        update prodObj;

        Product2 prodObj1 = IntappTestObjectFactory.createProduct(true);
        prodObj1.Name = 'TestProd1';
        update prodObj1;
        
        Product2 prodObj2 = IntappTestObjectFactory.createProduct(true);
        prodObj2.Name = 'One-Time';
        prodObj2.SBQQ__ChargeType__c = 'One-Time';
        update prodObj2;
        
        PricebookEntry standardPbe1 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prodObj.Id, UnitPrice = 1000, IsActive = true);
        insert standardPbe1;
        
        PricebookEntry standardPbe2 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prodObj1.Id, UnitPrice = 1000, IsActive = true);
        insert standardPbe2;
        
        PricebookEntry pbe1 = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = prodObj.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        insert pbe1;
        
        PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = prodObj1.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert pbe2;
        
        SBQQ__Dimension__c priceBookDimension1 = TestDataFactory.createPricebookDimension(prodObj.Id,true);
        
        SBQQ__Dimension__c priceBookDimension2 = TestDataFactory.createPricebookDimension(prodObj1.Id,true);
        
        Contract con1= new Contract();
        con1.Migration_Status__c = 'Ready';
        con1.AccountId = a.Id;
        con1.SBQQ__Quote__c = quotes.get(0).Id;
        con1.Processing_Status__c = 'Parent Subscription Created';
        con1.Legacy_Quote_Id__c = 'test legacy';
        insert con1;
        
        Contract con2 = new Contract();
        con2.Migration_Status__c = 'Ready';
        con2.AccountId = a.Id;
        con2.SBQQ__Quote__c = quotes.get(1).Id;
        con2.Processing_Status__c = 'Parent Subscription Created';
        con2.Legacy_Quote_Id__c = 'test legacy';
        insert con2;
        
        Contract con3 = new Contract();
        con3.Migration_Status__c = 'Ready';
        con3.AccountId = a.Id;
        con3.SBQQ__Quote__c = quotes.get(2).Id;
        con3.Processing_Status__c = 'Parent Subscription Created';
        con3.Legacy_Quote_Id__c = 'test legacy';
        insert con3;
        
        
        OP4I_Entitlement_View__c entitlement0 = new OP4I_Entitlement_View__c();
        entitlement0.Associated_OSA__c = con3.id;
        entitlement0.Deal_Type__c = 'Renewal';
        entitlement0.Name = 'Test Entitlement';
        entitlement0.Start_Date__c = null;
        entitlement0.End_Date__c = null;
        entitlement0.Sale_Price__c = 20.22;
        entitlement0.Product_Type__c = 'Software';
        entitlement0.DLI_Product__c = prodObj.id;
        entitlement0.DLIP_Product__c = prodObj1.id;
        entitlement0.Billing_Frequency__c = 'Annual';
        entitlement0.Processing_Status__c = 'Parent Subscription Created';
        entitlement0.Include_in_Select_Bundle__c = false;
        entitlement0.Additional_Discount__c = 20.12;
        entitlement0.Quote__c = quotes.get(0).Id;
        entitlement0.Segment_Index__c = 1;
        insert entitlement0;
        
        OP4I_Entitlement_View__c entitlement = new OP4I_Entitlement_View__c();
        entitlement.Associated_OSA__c = con1.id;
        entitlement.Deal_Type__c = 'Renewal';
        entitlement.Name = 'Test Entitlement';
        entitlement.Start_Date__c = Date.newInstance(2021, 4, 1);
        entitlement.End_Date__c = Date.newInstance(2022, 3, 31);
        entitlement.Sale_Price__c = 20.22;
        entitlement.Product_Type__c = 'Software';
        entitlement.DLI_Product__c = prodObj.id;
        entitlement.DLIP_Product__c = prodObj1.id;
        entitlement.Billing_Frequency__c = 'Annual';
        entitlement.Processing_Status__c = 'Parent Subscription Created';
        entitlement.Include_in_Select_Bundle__c = true;
        entitlement.Additional_Discount__c = 20.12;
        entitlement.Quote__c = quotes.get(0).Id;
        entitlement.Segment_Index__c = 1;
        insert entitlement;
        
        OP4I_Entitlement_View__c entitlement1 = new OP4I_Entitlement_View__c();
        entitlement1.Associated_OSA__c = con2.id;
        entitlement1.Deal_Type__c = 'Renewal';
        entitlement1.Name = 'Test Entitlement1';
        entitlement1.Start_Date__c = Date.newInstance(2021, 4, 1);
        entitlement1.End_Date__c = Date.newInstance(2022, 3, 31);
        entitlement1.Sale_Price__c = 20.22;
        entitlement1.Product_Type__c = 'Software';
        entitlement1.DLI_Product__c = prodObj.id;
        entitlement1.DLIP_Product__c = prodObj.id;
        entitlement1.Billing_Frequency__c = 'Annual';
        entitlement1.Processing_Status__c = 'Parent Subscription Creation failed';
        entitlement1.Include_in_Select_Bundle__c = true;
        entitlement1.Additional_Discount__c = 20.12;
        entitlement1.Quote__c = quotes.get(0).Id;
        entitlement.Segment_Index__c = 1;
        insert entitlement1;
        
        OP4I_Entitlement_View__c entitlement2 = new OP4I_Entitlement_View__c();
        entitlement2.Associated_OSA__c = con2.id;
        entitlement2.Name = 'Test Entitlement2';
        entitlement2.Deal_Type__c = 'Renewal';
        entitlement2.Start_Date__c = System.today();
        entitlement2.End_Date__c = System.today().addYears(1);
        entitlement2.Sale_Price__c = 20.22;
        entitlement2.Product_Type__c = 'Software';
        entitlement2.DLI_Product__c = prodObj.id;
        entitlement2.DLIP_Product__c = prodObj.id;
        entitlement2.Billing_Frequency__c = 'Annual';
        entitlement2.Processing_Status__c = 'Parent Subscription Creation failed';
        entitlement2.Include_in_Select_Bundle__c = false;
        entitlement2.Additional_Discount__c = 20.12;
        entitlement2.Quote__c = quotes.get(0).Id;
        entitlement.Segment_Index__c = 1;
        insert entitlement2;
        
        OP4I_Entitlement_View__c entitlement3 = new OP4I_Entitlement_View__c();
        entitlement3.Associated_OSA__c = con1.id;
        entitlement3.Name = 'Test Entitlement3';
        entitlement3.Deal_Type__c = 'Renewal';
        entitlement3.Start_Date__c = null;
        entitlement3.End_Date__c = null;
        entitlement3.Sale_Price__c = 20.22;
        entitlement3.Product_Type__c = 'Software';
        entitlement3.DLI_Product__c = prodObj2.id;
        entitlement3.Billing_Frequency__c = 'Annual';
        entitlement3.Additional_Discount__c = 20.12;
        entitlement3.Quote__c = quotes.get(0).Id;
        entitlement.Segment_Index__c = 1;
        insert entitlement3;
        
        OP4I_Entitlement_View__c entitlement4 = new OP4I_Entitlement_View__c();
        entitlement4.Associated_OSA__c = con2.id;
        entitlement4.Include_in_Select_Bundle__c = false;
        entitlement4.Name = 'Test Entitlement3';
        entitlement4.Deal_Type__c = 'Renewal';
        entitlement4.Start_Date__c = System.today();
        entitlement4.End_Date__c = System.today().addYears(1);
        entitlement4.Sale_Price__c = 20.22;
        entitlement4.Product_Type__c = 'Software';
        entitlement4.DLI_Product__c = prodObj2.id;
        entitlement4.DLIP_Product__c = prodObj2.id;
        entitlement4.Billing_Frequency__c = 'Annual';
        entitlement4.Additional_Discount__c = 20.12;
        entitlement4.Quote__c = quotes.get(0).Id;
        entitlement4.Segment_Index__c = 1;
        insert entitlement4;
        
        OP4I_Entitlement_View__c entitlement5 = new OP4I_Entitlement_View__c();
        entitlement5.Associated_OSA__c = con2.id;
        entitlement5.Include_in_Select_Bundle__c = false;
        entitlement5.Name = 'Test Entitlement3';
        //entitlement5.Deal_Type__c = 'Renewal';
        entitlement5.Start_Date__c = null;
        entitlement5.End_Date__c = null;
        entitlement5.Sale_Price__c = 20.22;
        entitlement5.Product_Type__c = 'Software';
        entitlement5.DLI_Product__c = prodObj.id;
        entitlement5.DLIP_Product__c = prodObj.id;
        entitlement5.Billing_Frequency__c = 'Annual';
        entitlement5.Additional_Discount__c = 20.12;
        entitlement5.Quote__c = quotes.get(0).Id;
        entitlement5.Segment_Index__c = 1;
        insert entitlement5;
    }

    @isTest
    public static void testSubscriptionBatch(){
       List<Contract> contracts = [SELECT ContractNumber,Migration_Status__c FROM Contract];
        List<String> contractNumbers = new List<String>();
        for (Contract con : contracts) {
            contractNumbers.add(con.ContractNumber.substring(con.ContractNumber.length() - 1));
        } 
        List<String> emailAddresses = new List<String>{('testdata@gmail.com')};
        
        
        SubscriptionsMigrationBatch sm = new SubscriptionsMigrationBatch(contractNumbers, emailAddresses);
        Test.startTest();
        ID batchProcessId = Database.executeBatch(sm);
        OP4I_Entitlement_View__c ent = [SELECT Id, Associated_OSA__c, Associated_OSA__r.AccountId, OP4I_Deal_Id__c, Parent_Subscription__c,
                                       DLI_Product__c, DLI_Product__r.Id, DLIP_Product__c, DLIP_Product__r.SBQQ__PricingMethod__c, DLIP_Product__r.SBQQ__SubscriptionPricing__c,
                                       DLIP_Product__r.SBQQ__SubscriptionType__c,
                                       DLIP_Product__r.SBQQ__ChargeType__c,
                                       DLIP_Product__r.SBQQ__BillingType__c,
                                       DLIP_Product__r.Product_Type__c,
                                       Quantity__c, Sale_Price__c, Additional_Discount__c,
                                       CurrencyIsoCode, Segment_Index__c,
                                       Start_Date__c, End_Date__c,
                                       Product_Instance__c,
                                       DLI_Id__c, DLIP_Id__c,
                                       Entitlement_Id__c,
                                       Support_Level__c, Meter_Type__c,
                                       Subscription_Term__c
                                FROM OP4I_Entitlement_View__c limit 1];
        Map<String, Id> pricebookMap = new Map<String, Id>();
        //pricebookMap.put('USD'+ent.DLIP_Product__c, 'fakePbeId');
        Map<String, Id> dimMap = new Map<String, Id>();
        //dimMap.put('USD'+ent.DLIP_Product__c, 'fakeDimId');
        Map<String, Date> contractEndDateMap = new Map<String, Date>();
        contractEndDateMap.put(ent.Associated_OSA__c, Date.today().addMonths(12));
        
        
        new SubscriptionsMigrationBatch().createChildSubscription(ent, pricebookMap, dimMap, contractEndDateMap );
        Test.stopTest();
        System.assertEquals('Ready', contracts[0].Migration_Status__c);
    }
}