Doc/force-app/main/default/objects/Contract/fields/Consolidated_Quote__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as Part for BIZ-47457. To store the consolidated quote in case of renewal contract consolidation.</description>
    <label>Consolidated Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Consolidated Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Exclude_from_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Auto_Renewal__c</fullName>
    <description>Flag to indicate the contract should auto-renew or not. Created w.r.t BIZ-72045</description>
    <formula>If(SBQQ__Quote__r.Exclude_from_Auto_Renewal__c,true,Exclude_from_Auto_Renewal_Override__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Select this if the contract should not auto-renew. The flag flows from Quote to Contract and disables auto-renewal.</inlineHelpText>
    <label>Exclude from Auto-Renewal?</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Is_Migrated_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_Migrated_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Migrated Contract</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Renewals_Pause__c.field-meta.xml
<CustomField>
    <fullName>Renewals_Pause__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field pauses the auto-renewals and automatic generation of renewal letters. Created as part of BIZ-66329</description>
    <label>Renewals Pause [DO NOT USE]</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__Evergreen__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Evergreen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the contract is evergreen.</description>
    <inlineHelpText>Indicates whether the contract is evergreen.</inlineHelpText>
    <label>Evergreen</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalForecast__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalForecast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
    <inlineHelpText>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</inlineHelpText>
    <label>Renewal Forecast</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalOpportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Renewal opportunity generated to track the renewal of this contract.</description>
    <inlineHelpText>Renewal opportunity generated to track the renewal of this contract.</inlineHelpText>
    <label>Renewal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Renewal Contracts</relationshipLabel>
    <relationshipName>RenewedContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalQuoted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalQuoted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
    <inlineHelpText>Select this option to automatically generate a renewal quote on renewal opportunities.</inlineHelpText>
    <label>Renewal Quoted</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Renewals_Pause__c.field-meta.xml
<CustomField>
    <fullName>Renewals_Pause__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Renewal Hold flag on the Renewal Opportunity. Source of truth for hold state. Updated as part of BIZ-82935 (was synced from Contract via BIZ-75580).</description>
    <label>Renewal Hold</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>BIZ-64132. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Exclude_from_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Auto_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate the contract should auto-renew or not. Created w.r.t BIZ-72045</description>
    <inlineHelpText>Select this if the contract should not auto-renew. The flag flows from Quote to Contract and disables auto-renewal.</inlineHelpText>
    <label>Exclude from Auto-Renewal?</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story. Changes as part of BIZ-67362</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Consolidated_Quote__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Quote__c</fullName>
    <description>Formula field for consolidated quote on subscription from Contract
Created as part of BIZ-51592</description>
    <formula>CASESAFEID(SBQQ__Contract__r.Consolidated_Quote__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consolidated Quote</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

Doc/force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:The Frayman Group, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:Intapp Singapore Pte. Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>42:Intapp Employee Compliance, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>44:Intapp Germany GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>08:Intapp Pty, Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>40:Intapp Ireland Limited</fullName>
    </customValue>
    <customValue>
        <fullName>46:Intapp Netherlands B.V.</fullName>
    </customValue>
    <customValue>
        <fullName>50:TermSheet</fullName>
    </customValue>
    <customValue>
        <fullName>Delphai Subsidiary (placeholder)</fullName>
    </customValue>
    <customValue>
        <fullName>TermSheet Subsidiary</fullName>
        <isActive>false</isActive>
        <label>TermSheet Subsidiary</label>
    </customValue>
    <customValue>
        <fullName>46:Transform Data International</fullName>
        <isActive>false</isActive>
        <label>46:Transform Data International</label>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>42:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
        <isActive>false</isActive>
        <label>05:400 TFG - US</label>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
        <isActive>false</isActive>
        <label>28:OnePlace Pte Ltd</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RenewalQuotecreationBatch.cls
/**
* @description Batch class for Creating Renewal Quotes.
* @author Suresh Somu
* @jira BIZ-68091
**/
public without sharing class RenewalQuotecreationBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

    private String originalTransactionId;

    /***********************************************************************************************
    *
    * props
    *
    ***********************************************************************************************/
    private String query;
    private Integer scopeSize;
    private Date currentDate = Date.today();

    /***********************************************************************************************
    *
    * Constructors
    *
    ***********************************************************************************************/
    /**
    * @description Default Constructor
    **/
    public RenewalQuotecreationBatch() {
        this.query = getDefaultQuery();
        this.scopeSize = 1;
    }

    /**
    * @description parameterized Constructor
    * @param query
    * @param scopeSize
    **/
    public RenewalQuotecreationBatch(String query, Integer scopeSize) {
        // Set the query and scope size
        this.query = query ?? getDefaultQuery();
        this.scopeSize = scopeSize ?? 1;
    }

    /***********************************************************************************************
    *
    * Public Methods
    *
    ***********************************************************************************************/
    /**
    * @description Method that can be used to override the query and scope size
    * @param query
    * @param scopeSize
    **/
    public void executeBatch(String query, Integer scopeSize) {
        RenewalQuotecreationBatch obj = new RenewalQuotecreationBatch(query, scopeSize);
        Database.executeBatch(obj, scopeSize);
    }

    /***********************************************************************************************
    *
    * Batch Methods
    *
    ***********************************************************************************************/
    /**
    * @description start method
    * @param bc
    * @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Each batchable method runs in a separate transaction,
        // so store the first transaction ID to later relate the other transactions
        this.originalTransactionId = Nebula.Logger.getTransactionId();
        
        Nebula.Logger.info('Starting RenewalQuotecreationBatch with scope size: ' + this.scopeSize)
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');
        Nebula.Logger.debug('Query being executed: ' + this.query)
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');
        
        // Query Quotes that need to be processed
        String query = this.query;
        Database.QueryLocator queryLocator = Database.getQueryLocator(query);
        
        Nebula.Logger.info('Query executed successfully, starting batch processing')
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');
        Nebula.Logger.saveLog();
        return queryLocator;
    }

    /**
    * @description execute method
    * @param bc
    * @param renewalContracts
    **/
    public void execute(Database.BatchableContext bc, List<Contract> renewalContracts) {
        // One-time call (per transaction) to set the parent log
        Nebula.Logger.setParentLogTransactionId(this.originalTransactionId);
        
        Nebula.Logger.info('Processing batch of ' + renewalContracts.size() + ' renewal contracts')
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');

        Map<Id, Contract> mapOfContracts = new Map<ID, Contract>();
        Set<Id> setOfProcessedContractIds = new Set<ID>();
        // Process each renewal Contract
        for (Contract renewalContract : renewalContracts) {
			mapOfContracts.put(renewalContract.Id, renewalContract);
        }
        
        List<SBQQ__Subscription__c> renewableSubscriptions = RenewalQuoteCreationService.getRenewableSubscriptions(mapOfContracts.keySet());
        Nebula.Logger.debug('Processing ' + renewableSubscriptions.size() + ' renewable subscriptions')
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');

        for(SBQQ__Subscription__c subscription : renewableSubscriptions){
            // Added SBQQ__Contract__r.Exclude_from_Auto_Renewal__c check as part of BIZ-72045
            if(!setOfProcessedContractIds.contains(subscription.SBQQ__Contract__c) && !subscription.SBQQ__Contract__r.Exclude_from_Auto_Renewal__c){
                Contract renewalContract = mapOfContracts.get(subscription.SBQQ__Contract__c);
                Date opportunityRenewalDate = renewalContract.EndDate.addDays(-395);

                Nebula.Logger.debug('Evaluating contract ' + renewalContract.Id +
                    ': EndDate=' + renewalContract.EndDate +
                    ', StartDate=' + renewalContract.StartDate +
                    ', opportunityRenewalDate=' + opportunityRenewalDate +
                    ', currentDate=' + currentDate)
                    .addTag('RenewalQuotecreationBatch')
                    .addTag('AutoRenewal')
                    .setRecordId(renewalContract.Id);

                // Create renewal when there are 395 days or fewer remaining until contract end date,
                // even if the contract has not yet started (BIZ-68091)
                Boolean shouldCreateRenewal = (currentDate >= opportunityRenewalDate);

                if (!shouldCreateRenewal) {
                    Nebula.Logger.debug('Skipping contract ' + renewalContract.Id + ' - not within 395 days of end date (renewal date threshold: ' + opportunityRenewalDate + ')')
                        .addTag('RenewalQuotecreationBatch')
                        .addTag('AutoRenewal')
                        .setRecordId(renewalContract.Id);
                }

                if (shouldCreateRenewal) {
                    Nebula.Logger.info('Contract ' + renewalContract.Id + ' qualifies for renewal - within 395 days of end date (EndDate: ' + renewalContract.EndDate + ', threshold: ' + opportunityRenewalDate + ')')
                        .addTag('RenewalQuotecreationBatch')
                        .addTag('AutoRenewal')
                        .setRecordId(renewalContract.Id);
                    RenewalQuoteCreationService.checkRenewalQuoteCreation(renewalContract);
                }
                setOfProcessedContractIds.add(subscription.SBQQ__Contract__c);
            } else {
                Nebula.Logger.debug('Skipping subscription ' + subscription.Id + ' - contract already processed or excluded from auto renewal')
                    .addTag('RenewalQuotecreationBatch')
                    .addTag('AutoRenewal')
                    .setRecordId(subscription.SBQQ__Contract__c);
            }
        }
        
        Nebula.Logger.saveLog();
    }

    /**
    * @description finish method
    * @param bc
    **/
    public void finish(Database.BatchableContext bc) {
        // The finish method runs in yet-another transaction, so set the parent log again
        Nebula.Logger.setParentLogTransactionId(this.originalTransactionId);
        
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedDate, CompletedDate
                           FROM AsyncApexJob WHERE Id = :bc.getJobId()];
        
        Nebula.Logger.info('RenewalQuotecreationBatch completed. Status: ' + job.Status + ', Items Processed: ' + job.JobItemsProcessed + '/' + job.TotalJobItems + ', Errors: ' + job.NumberOfErrors)
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');
        
        if (job.NumberOfErrors > 0) {
            Nebula.Logger.error('Batch completed with ' + job.NumberOfErrors + ' errors')
                .addTag('RenewalQuotecreationBatch')
                .addTag('AutoRenewal')
                .addTag('BatchError');
        }
        
        Nebula.Logger.info('Finishing running RenewalQuotecreationBatch')
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal');
        Nebula.Logger.saveLog();
    }

    /***********************************************************************************************
    *
    * Schedulable Methods
    *
    ***********************************************************************************************/
    /**
    * @description execute method
    * @param sc
    **/
    public void execute(SchedulableContext sc) {
        Nebula.Logger.info('Scheduled execution of RenewalQuotecreationBatch triggered')
            .addTag('RenewalQuotecreationBatch')
            .addTag('AutoRenewal')
            .addTag('Scheduled');
        Nebula.Logger.saveLog();
        // Execute the batch job
        executeBatch(this.query, this.scopeSize);
    }

    /***********************************************************************************************
    *
    * Private Methods
    *
    ************************************************************************************************ 
    /**
    * @description set the default query
    * @return String
    **/
    private String getDefaultQuery() {

        // Set the default query based on the business logic
        String defaultQuery = 'SELECT Id, Subsidiary__c, SBQQ__RenewalQuoted__c, StartDate, EndDate, ContractTerm, ' + 
                              'Status, SBQQ__RenewalOpportunity__c,SBQQ__RenewalTerm__c, ' +
            				  'SBQQ__RenewalForecast__c, SBQQ__Evergreen__c,SBQQ__RenewalOpportunity__r.StageName, SBQQ__RenewalOpportunity__r.IsClosed, ' +
                              'Deal_Type__c, Is_Migrated_Contract__c, ' + // BIZ-82935: Renewals_Pause__c removed — hold managed at Opportunity level
                              'Consolidated_Quote__c, Consolidated_Quote__r.SBQQ__Opportunity2__r.StageName ' +
                              'FROM Contract ' +
                              'WHERE Subsidiary__c != null AND SBQQ__RenewalQuoted__c = false ' +
                              ' AND Status != \''+ContractConstants.STATUS_CANCELLED_LAPSED+'\'' +
                              ' AND Status != \''+ContractConstants.STATUS_SUPERSEDED_BY_NEWER_CONTRACT+'\'' +
                              ' AND (SBQQ__RenewalForecast__c = false OR SBQQ__Evergreen__c = false) '+
                              ' AND Deal_Type__c != \''+ContractConstants.DEAL_TYPE_PARTNER_FEE+'\'' +
                              ' AND (Deal_Type__c != \''+ContractConstants.DEAL_TYPE_ADD_ON+'\' OR Is_Migrated_Contract__c = false)' +
                              ' AND (Consolidated_Quote__c = null OR Consolidated_Quote__r.SBQQ__Opportunity2__r.StageName != \''+OpportunityConstants.STAGE_CLOSED_WON+'\')' +
                              ' AND Id IN (SELECT SBQQ__Contract__c FROM SBQQ__Subscription__c)';
        return defaultQuery;
    }
}