Doc/force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <customValue>
        <fullName>Amendment_to_Supercede</fullName>
        <label>Amendment to Supercede</label>
    </customValue>
    <customValue>
        <fullName>Partner_Fee</fullName>
        <label>Partner Fee</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <isActive>false</isActive>
        <label>Platform_Fee</label>
    </customValue>
    <customValue>
        <fullName>AddOn</fullName>
        <isActive>false</isActive>
        <label>AddOn</label>
    </customValue>
    <customValue>
        <fullName>Platform Fee</fullName>
        <isActive>false</isActive>
        <label>Platform Fee</label>
    </customValue>
    <description>Modified as part of BIZ-46501.</description>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractUtil.cls
/**
 * @description       : Util class for contracts
**/
public inherited sharing class ContractUtil {

    /**
     * @description Returns the open NYMY Opportunities and Renewal Opportunities from the contracts
     * @param contractIds
     * @return List<Opportunity>
     */
    public static List<Opportunity> getNymyAndRenewalOpportunitiesFromContracts(Set<Id> contractIds){
        List<Opportunity> renewalAndNymyOpporty = [
            SELECT Id, 
                Deal_Type__c,
                Associated_Contract_OSA__c,
                SBQQ__RenewedContract__c, 
                StageName
            FROM Opportunity
            WHERE  
                (
                    (Associated_Contract_OSA__c IN :contractIds AND Deal_Type__c = :OpportunityConstants.DEAL_TYPE_NYMY) 
                    OR 
                    (SBQQ__RenewedContract__c IN :contractIds AND Type = :OpportunityConstants.TYPE_RENEWAL)
                )
                AND (NOT StageName LIKE '%closed%')
        ];
        

        return renewalAndNymyOpporty;
    }

    /**
     * @description Returns the active contract count on the account.
     * @param accountIds
     * @return Map<Id, Integer> 
     */
    public static Map<Id, Integer> getActiveContractCountOnAccount(Set<Id> accountIds) {
        Map<Id, Integer> accountIdToContractCountMap = new Map<Id, Integer>();
    
        if (accountIds == null || accountIds.isEmpty()) {
            return accountIdToContractCountMap;
        }
    
        for (AggregateResult ar : [
            SELECT AccountId, COUNT(Id) contractCount
            FROM Contract
            WHERE AccountId IN :accountIds
              AND Status = :ContractConstants.STATUS_INFORCE
            GROUP BY AccountId
        ]) {
            accountIdToContractCountMap.put(
                (Id) ar.get('AccountId'),
                (Integer) ar.get('contractCount')
            );
        }
    
        return accountIdToContractCountMap;
    }
}