Doc/force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
            <value>
                <fullName>Renewal Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalForecast__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalForecast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
    <inlineHelpText>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</inlineHelpText>
    <label>Renewal Forecast</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalQuoted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalQuoted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
    <inlineHelpText>Select this option to automatically generate a renewal quote on renewal opportunities.</inlineHelpText>
    <label>Renewal Quoted</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/Contract/fields/SBQQ__RenewalUpliftRate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalUpliftRate__c</fullName>
    <description>Rate of renewal price increases.</description>
    <inlineHelpText>Rate of renewal price increases.</inlineHelpText>
    <label>Renewal Uplift (%)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores all the custom exceptions coming from Apex Code</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/OP4I_Entitlement_Renewal_View__c.object-meta.xml
<CustomObject>
    <label>OP4I Entitlement Renewal View</label>
    <nameField>
        <label>OP4I Entitlement Renewal View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OP4I Entitlement Renewal Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/OSA__c.field-meta.xml
<CustomField>
    <fullName>OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Renewal Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Renewal_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Product_Instance__c.field-meta.xml
<CustomField>
    <fullName>Product_Instance__c</fullName>
    <label>Product Instance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Renewal_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Deal_Id__c</fullName>
    <label>Renewal Deal Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Renewal_DLIP_Id__c.field-meta.xml
<CustomField>
    <fullName>Renewal_DLIP_Id__c</fullName>
    <label>Renewal DLIP Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OP4I Entitlement Renewal Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Renewal_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_Renewal_View__c/fields/Renewal_Uplift__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Uplift__c</fullName>
    <label>Renewal Uplift</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContractsRenewalMigrationBatch.cls
global class ContractsRenewalMigrationBatch implements Database.Batchable<sObject>{
    List<string> lstOfContractAssignment;
    global ContractsRenewalMigrationBatch() {}

    global ContractsRenewalMigrationBatch(List<string> lstOfContractNumbers){
        lstOfContractAssignment = lstOfContractNumbers ;
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        string endCondition;
        if (lstOfContractAssignment != null && !lstOfContractAssignment.isempty()) {
            for (string endDigit : lstOfContractAssignment) {
                endCondition = endCondition != null? (endCondition +  ' OR ContractNumber like \'%' + endDigit + '\'') :' ContractNumber like \'%' + endDigit + '\'';
            }
        } 
        String query = 'SELECT Id,Processing_Status__c,SBQQ__RenewalForecast__c,Enddate,SBQQ__RenewalQuoted__c FROM Contract WHERE Migration_Status__c = \'Renewal Ready\'';
        query = endCondition != null? query + ' AND (' + endCondition + ')' : query;
        system.debug('Start Query' +query);   
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext bc, List<Contract> lstOfContracts){
        List<Contract> lstOfUpdatedContracts = new List<Contract>();
        List<OP4I_Entitlement_Renewal_View__c> lstOfEntitlementRecords = new List<OP4I_Entitlement_Renewal_View__c>();
        Map<String,OP4I_Entitlement_Renewal_View__c> mapOfOsaToEntitlementRecords = new Map<String,OP4I_Entitlement_Renewal_View__c>(); 
        List<OP4I_Entitlement_Renewal_View__c> lstOfEntitlementRecordsUpd = new List<OP4I_Entitlement_Renewal_View__c>();
        set<string> setOfContractIds = new set<string>();
        Map<String,Decimal> mapOfOsaToRenewalUplift = new Map<String,Decimal>();
        if(!lstOfContracts.IsEmpty())
        {
            lstOfEntitlementRecords = [Select Id,Error_Log__c,OSA__c,OSA__r.Processing_Status__c,Product_Id__c,Product_Instance__c,
                                       Quantity__c,Renewal_Deal_Id__c,Renewal_DLIP_Id__c,Renewal_Opportunity__c,Renewal_Uplift__c
                                       FROM OP4I_Entitlement_Renewal_View__c 
                                       WHERE OSA__c IN: lstOfContracts];
                                       
            if(!lstOfEntitlementRecords.IsEmpty()){ 
              for(OP4I_Entitlement_Renewal_View__c entitlemnt : lstOfEntitlementRecords)
              {
                mapOfOsaToEntitlementRecords.put(entitlemnt.OSA__c,entitlemnt);
                mapOfOsaToRenewalUplift.put(entitlemnt.OSA__c,entitlemnt.Renewal_Uplift__c);            
              }
            }
            
            if(!lstOfContracts.IsEmpty() && lstOfContracts.size() > 0){
              for(Contract contrObj : lstOfContracts){
                if(mapOfOsaToRenewalUplift.get(contrObj.id) != null){             
                contrObj.SBQQ__RenewalUpliftRate__c = mapOfOsaToRenewalUplift.get(contrObj.id); 
                }               
                contrObj.SBQQ__RenewalForecast__c = true;
                if(system.today().daysBetween(contrObj.Enddate) < 90){
                contrObj.SBQQ__RenewalQuoted__c = true;                         
                }
                lstOfUpdatedContracts.add(contrObj);
              }                             
            }
            
            if(lstOfUpdatedContracts.size() > 0){
            updateContract(lstOfUpdatedContracts,mapOfOsaToEntitlementRecords);
            }                      
        }   
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
    global static void updateContract(List<Contract> lstOfUpdatedContracts,Map<String,OP4I_Entitlement_Renewal_View__c> mapOfOsaToEntitlementRecords){
        Database.SaveResult[] updateContractResult = Database.update(lstOfUpdatedContracts, false); 
        map<string,string> resultMap = HandleCustomException.logMigrationDatabaseError(
            updateContractResult,
            mapOfOsaToEntitlementRecords,
            'Id',
            lstOfUpdatedContracts
        );   
        string keyFields = 'OSA__c';
        for(OP4I_Entitlement_Renewal_View__c entitlement : mapOfOsaToEntitlementRecords.values()) {          
            string key = HandleCustomException.getKey(keyFields, entitlement);
            if (resultMap.containsKey(key)) {
                entitlement.Error_Log__c = resultMap.get(key);
                entitlement.OSA__r.Processing_Status__c = 'Contract Updation Failed';
            }
        }
        
        Database.SaveResult[] entitlementLst = Database.update(mapOfOsaToEntitlementRecords.values(), false);
        HandleCustomException.logDatabaseErrorsForEntitlements(entitlementLst,mapOfOsaToEntitlementRecords);  
    }
}