Doc/force-app/main/default/objects/Contract/fields/OP4I_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Contract_Number__c</fullName>
    <description>OP4I Contract Number mapped from quote::BIZ-50998</description>
    <formula>IF(
  NOT(ISBLANK(SBQQ__Quote__r.Override_OP4I_ContractNumber__c)),
  SBQQ__Quote__r.Override_OP4I_ContractNumber__c,
  SBQQ__Quote__r.OP4I_Contract_Number__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Contract Number</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Contract_Number__c</fullName>
    <description>OP4I Contract Number mapped from primary quote:BIZ-50998</description>
    <formula>SBQQ__PrimaryQuote__r.OP4I_Contract_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Contract Number</label>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/Opportunity/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Opportunity Line Item is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/DLIP_OP4I_ID__c.field-meta.xml
<CustomField>
    <fullName>DLIP_OP4I_ID__c</fullName>
    <description>Created as part of BIZ-68739</description>
    <label>DLIP OP4I ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/OP4I_System_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_System_Id__c</fullName>
    <description>For syncing Opportunity Products Items with OP4I Deal Line Item, BIZ-45223</description>
    <label>OP4I System Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Parent_of_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Parent_of_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Twin field, enabled to true for Select and Static Parent SKU&apos;s</description>
    <label>Parent of Bundle</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this Opportunity Product.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Indicates the subscription type to determine contract&apos;s pricing.</description>
    <inlineHelpText>Indicates the subscription type to determine contract&apos;s pricing.</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__SubscriptionType</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/OpportunityLineItem/fields/Segment_Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-68140 - Reference to the parent Static Bundle Opportunity Line Item for segmentation tracking of Static Components.</description>
    <label>Segment Bundle Line</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product (Segment Bundle Line)</relationshipLabel>
    <relationshipName>Segment_Bundle_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Quote Line is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Item_Key__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Key__c</fullName>
    <description>BIZ-68140 - A unique identifier for the Quote Line item.</description>
    <label>Line Item Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Parent_of_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Parent_of_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator field for Parent Static and Select Bundle, created as per BIZ-48496</description>
    <label>Parent of Bundle</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Segment_Bundle_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line_Id__c</fullName>
    <description>BIZ-68140 - Identifies the associated Segment Bundle Line for the Quote Line, linking it to the relevant bundle configuration.</description>
    <label>Segment Bundle Line Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/CPQ_Option_Type__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Option_Type__c</fullName>
    <description>BIZ-68140 - Indicates whether the Subscription is a Static Bundle, Static Component, or other CPQ option type for segmentation and bundling logic.</description>
    <label>CPQ Option Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPQ_Option_Type</valueSetName>
    </valueSet>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/OP4I_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Contract_Number__c</fullName>
    <label>OP4I Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/OP4I_Entitlement_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Entitlement_Id__c</fullName>
    <label>OP4I Entitlement Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/OP4I_Error__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Error__c</fullName>
    <description>BIZ-54439
This field will be populated if there’s an error in the integration to OP4I and will be updated again (cleared) if error resolved and data came through to OP4I successfully.</description>
    <label>OP4I Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Original_Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Original_Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created w.r.t BIZ-68888</description>
    <label>Original Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Parent_Of_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Parent_Of_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Twin field, enabled true for Select and Static Bundle Parent SKU&apos;s</description>
    <label>Parent Of Bundle</label>
    <type>Checkbox</type>
</CustomField>

Doc/force-app/main/default/objects/SBQQ__Subscription__c/fields/Segment_Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Segment_Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-68140 - Reference to the parent Static Bundle Subscription for segmentation tracking of Static Components.</description>
    <label>Segment Bundle Line</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions (Segment Bundle Line)</relationshipLabel>
    <relationshipName>Segment_Bundle_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

Doc/force-app/main/default/globalValueSets/CPQ_Option_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Static Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Static Component</fullName>
    </customValue>
    <description>BIZ-68318</description>
    <masterLabel>CPQ Option Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubscriptionTriggerHelper.cls
/**
* @description       : This class is a Helper class for SubscriptionTrigger.
* @author            : Sonali Kakade
* @last modified on  : 06-23-2025
* @last modified by  : Sonali Kakade
* Modifications Log
* Ver   Date         Author            Modification
* 1.0   06-23-2025   Sonali Kakade     Initial Version via BIZ-67339
* 2.0 	07-23-2025   Manisha S		   Queried fields in after insert via BIZ-71406
**/
public class SubscriptionTriggerHelper {
    
    /***********************************************************************************************
    *
    * public methods
    *
    ***********************************************************************************************/
    
	/**
    * @description Handles the before insert logic for `SBQQ__Subscription__c` records.
    *              Looks up the OpportunityLineItem linked to the subscription's original quote line
    *              and stamps the `Original_Opportunity_Product__c` field on the subscription.
    * @param subNewList A list of newly inserted `SBQQ__Subscription__c` records (before insert context).
    **/
    public static void populateOriginalOpportunityProduct(List<SBQQ__Subscription__c> subNewList) {
        Set<Id> quoteLineIds = new Set<Id>();
        for (SBQQ__Subscription__c sub : subNewList) {
            if (sub.SBQQ__QuoteLine__c != null) {
                quoteLineIds.add(sub.SBQQ__QuoteLine__c);
            }
        }

        if (quoteLineIds.isEmpty()) {
            return;
        }

        Map<Id, Id> quoteLineToOppProductMap = new Map<Id, Id>();
        for (OpportunityLineItem oli : [
            SELECT Id, SBQQ__QuoteLine__c
              FROM OpportunityLineItem
             WHERE SBQQ__QuoteLine__c IN :quoteLineIds
        ]) {
            quoteLineToOppProductMap.put(oli.SBQQ__QuoteLine__c, oli.Id);
        }

        for (SBQQ__Subscription__c sub : subNewList) {
            if (sub.SBQQ__QuoteLine__c != null
                && quoteLineToOppProductMap.containsKey(sub.SBQQ__QuoteLine__c)) {
                sub.Original_Opportunity_Product__c = quoteLineToOppProductMap.get(sub.SBQQ__QuoteLine__c);
            }
        }
    }

	/**
    * @description Handles the logic after the insertion of `SBQQ__Subscription__c` records. 
    *              It updates the `Segment_Bundle_Line__c` field for segmented bundles, 
    *              filters eligible subscriptions, and publishes them for integration.
    * @param subNewList A list of newly inserted `SBQQ__Subscription__c` records.
    **/
    public static void subscriptionAfterInsert(List<SBQQ__Subscription__c > subNewList) { 

        updateSegmentedBundleId(subNewList);
        if(!subNewList.isEmpty()) {
            set<Id> subSet = new Set<id>();
            for(SBQQ__Subscription__c subObj : subNewList) {
                if(subObj.SBQQ__SubscriptionType__c != 'One-time' && subObj.Parent_Of_Bundle__c == false && subObj.CPQ_Option_Type__c != 'Static Bundle') {
                    subSet.add(subObj.id);
                }
            }

            if(subSet.size() > 0 && !subSet.isEmpty()) {
                String query = buildSubscriptionQuery(subSet);
                List<SBQQ__Subscription__c> subscriptionList  = Database.query(query);
                IntegrationUtility.publishsObjectRecords(subscriptionList, 'SBQQ__Subscription__c');
            }
        }
    } 
    
    /**
    * @description Handles the logic after the update of `SBQQ__Subscription__c` records.
    *              It identifies subscriptions eligible for processing based on changes in 
    *              key fields such as contract number and entitlement ID. The method triggers 
    *              event processing for the updated subscriptions.
    * @param subNewList A list of newly updated `SBQQ__Subscription__c` records.
    * @param subOldMap A map of old values of the `SBQQ__Subscription__c` records.
    **/
    public static void subscriptionAfterUpdate(List<SBQQ__Subscription__c > subNewList, Map<Id, SBQQ__Subscription__c > subOldMap) {
        List<SBQQ__Subscription__c> subsEligibleList = new List<SBQQ__Subscription__c>();
        Set<Id> subscriptionSet = new Set<Id>();
        if(!subNewList.isEmpty()) {
            for(SBQQ__Subscription__c sub : [SELECT Id, OP4I_Contract_Number__c, Parent_Of_Bundle__c,
                                             		OP4I_Entitlement_Id__c, SBQQ__Contract__r.OP4I_Error__c
                                               FROM SBQQ__Subscription__c
                                              WHERE ID IN: subNewList and CPQ_Option_Type__c != 'Static Bundle' and 
                                            	OP4I_Contract_Number__c != null and Parent_Of_Bundle__c = false]) {
				if(sub.OP4I_Entitlement_Id__c != null || sub.SBQQ__Contract__r.OP4I_Error__c != null) {
                	subscriptionSet.add(sub.Id);
                }
        	}
        }
        if(!subscriptionSet.isEmpty()) {
            processEvents(subscriptionSet, subOldMap, true);
        }
    }
    
    /**
    * @description Processes events for the given set of `SBQQ__Subscription__c` records.
    *              This method dynamically constructs a SOQL query to retrieve subscription data 
    *              and publishes eligible subscription records for integration.
    * @param subSet A set of subscription IDs that require event processing.
    * @param subOldMap A map of old subscription records used for comparison during processing.
    * @param sendLines A boolean flag indicating whether to include line items in the processing.
    **/
    public static void processEvents(Set<Id> subSet, Map<Id,SBQQ__Subscription__c > subOldMap, Boolean sendLines){
        List<SBQQ__Subscription__c> subscriptionList = new List<SBQQ__Subscription__c>();
        if(subSet != null) {
            if(sendLines) {
                String query = buildSubscriptionQuery(subSet);
                subscriptionList = Database.query(query);
            }
            if(subscriptionList.size() > 0) {
                IntegrationUtility.publishEligibleSobjectRecords(subscriptionList,subOldMap, 'SBQQ__Subscription__c');
            }
        }
    }

    /**
    * @description Updates the `Segment_Bundle_Line__c` field for subscriptions that are 
    *              part of a segmented bundle relationship. It associates static components 
    *              with their respective static bundle parent based on the bundle relationship.
    * @param lstNewSubscriptions A list of newly inserted or updated `SBQQ__Subscription__c` records.
    **/
    public static void updateSegmentedBundleId(List<SBQQ__Subscription__c> lstNewSubscriptions) {
        Map<String, Id> mapStaticBundleMap = new Map<String, Id>();
        List<SBQQ__Subscription__c> lstOrderProductsToUpdate = new List<SBQQ__Subscription__c>();
        lstNewSubscriptions = getSubscriptions(lstNewSubscriptions);
        // Exit early if the list is empty
        if(lstNewSubscriptions.isEmpty()) {
            return;
        }
        
        //Identify most parent products and segmented bundle parents
        for(SBQQ__Subscription__c sub : lstNewSubscriptions) {
            if(sub.CPQ_Option_Type__c == OpportunityProductConstants.OPTION_TYPE_STATIC_BUNDLE && sub.SBQQ__QuoteLine__r.Line_Item_Key__c != null) {
                // Segmented Bundle Parent
                mapStaticBundleMap.put(sub.SBQQ__QuoteLine__r.Line_Item_Key__c, sub.Id);
            }
        }
        for(SBQQ__Subscription__c sub : lstNewSubscriptions) {
            if(sub.CPQ_Option_Type__c == OpportunityProductConstants.OPTION_TYPE_STATIC_COMPONENT && sub.SBQQ__QuoteLine__r.Segment_Bundle_Line_Id__c != null ) {  
                String unique = sub.SBQQ__QuoteLine__r.Segment_Bundle_Line_Id__c;
                // Segmented Bundle Parent
                if(mapStaticBundleMap.containsKey(unique)) {
                    lstOrderProductsToUpdate.add(new SBQQ__Subscription__c(Id = sub.Id, Segment_Bundle_Line__c = mapStaticBundleMap.get(unique)));
                }
            }
        }
        update lstOrderProductsToUpdate;
        // Update Opportunity Line Item
        List<Database.SaveResult> updateSubscriptionResults = Database.update(lstOrderProductsToUpdate, false);
        Set<Id> subscriptionsNotUpdated = ResultHandler.logErrors('SubscriptionTriggerHandler Update Subscriptions', lstOrderProductsToUpdate, updateSubscriptionResults);
    }

    /**
    * @description Getter for Subscription records based on Ids.
    * 			   Filters records where CPQ_Option_Type__c, Line_Item_Key__c, and Segment_Bundle_Line_Id__c are not null.
    * @param lstNewSubscriptions List of SBQQ__Subscription__c records
    * @return List<SBQQ__Subscription__c> Filtered list of subscriptions
    **/
    private static List<SBQQ__Subscription__c> getSubscriptions(List<SBQQ__Subscription__c> lstNewSubscriptions) {
        return [
            SELECT Id, CPQ_Option_Type__c, SBQQ__QuoteLine__r.Line_Item_Key__c, 
                   SBQQ__QuoteLine__r.Segment_Bundle_Line_Id__c
              FROM SBQQ__Subscription__c 
             WHERE Id IN :lstNewSubscriptions
               AND CPQ_Option_Type__c != null AND SBQQ__QuoteLine__c != null
        ];
    }

    /**
    * @description Builds the dynamic subscription query used by multiple methods.
    * @param subSet Set of subscription IDs to fetch
    * @return String A SOQL query string
    **/
    private static String buildSubscriptionQuery(Set<Id> subSet) {
        Schema.SObjectType targetObjType = Schema.getGlobalDescribe().get('SBQQ__Subscription__c');
        Map<String, Schema.SObjectField> fieldMap = targetObjType.getDescribe().fields.getMap();
        List<String> fields = new List<String>(fieldMap.keyset());

        // Additional fields (relationships)
        String additionalFields = '';
        additionalFields += ', Original_Opportunity_Product__r.OP4I_System_Id__c';
        additionalFields += ', Original_Opportunity_Product__r.DLIP_OP4I_ID__c';
        additionalFields += ', SBQQ__Product__r.Intapp_ID__c';
        additionalFields += ', SBQQ__RevisedSubscription__r.OP4I_Entitlement_Id__c';

        String query = 'SELECT ' + String.join(fields, ',') + additionalFields + 
                       ' FROM SBQQ__Subscription__c WHERE Id IN :subSet';
        return query.remove('{').remove('}');
    }
}